### ISSUE TITLE
Remote Design Sprints

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Meta#1]
```meta
Title: Remote Design Sprints
Status: Draft
Type: Process
```
## Abstract
>_“The outcome of every Design Sprint Week is a high-fidelity interactive prototype, tested by real users, and with clear insights on where to go next.”_
>— AJ&Smart

## Motivation
Engage people in the community, technical and non technical to explore Bitcoin design challenges.

### Setup
- Define focus topic
- Recruit Designers
- Recruit Technical Experts
- Recruit Test Participants

### Schedule
_Can be done daily or split into several weeks as it requires a large time commitment._

#### Session 1
| Exercise | Duration | Output |
| -------- | -------- | ------ |
|          |          |        |
|          |          |        |
|          |          |        |

#### Session 2
| Exercise | Duration | Output |
| -------- | -------- | ------ |
|          |          |        |
|          |          |        |
|          |          |        |

#### Session 3
| Exercise | Duration | Output |
| -------- | -------- | ------ |
|          |          |        |
|          |          |        |
|          |          |        |

#### Session 4
| Exercise | Duration | Output |
| -------- | -------- | ------ |
|          |          |        |
|          |          |        |
|          |          |        |

#### Session 5
| Exercise | Duration | Output |
| -------- | -------- | ------ |
|          |          |        |
|          |          |        |
|          |          |        |

### Tools
- Miro
- Figma

**Comment by danielnordh** [comment]
Closing this issue for now. We can reopen if necessary.
