### ISSUE TITLE
OpenSats website

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#108]
We had a [design review call](https://github.com/BitcoinDesign/Meta/issues/102) with Ben from [OpenSats](https://opensats.org) on May 25, 2021. OpenSats is a portal to facilitate donations and sponsoring of open-source Bitcoin contributions (for more background, listen to this [podcast episode](https://stephanlivera.com/episode/278/)). Ben is looking for design support for the project to help with figuring out onboarding flows for different audiences and overall site design. The [review call recording](https://www.youtube.com/watch?v=KtV0l6NsJZs) provides a great overview.

There is a designer helping out, but probably not on a long-term basis, so it would be ideal to find someone who could help establish good foundations during this important initial MVP phase. The current work-in-progress design can be found [here in Figma](https://www.figma.com/file/xnHALAneAU7JUQqkd6wLw2/OS-1-Copy?node-id=0%3A1), and in this [Figma community file](https://www.figma.com/community/file/979950664343155665/Open-Sats-Initiative).

Per our [collaboration playbook](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md), I think this falls into 3 categories:

**[1. Resources and consultation](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md#1-resources--consultation)**
General feedback on not only the site design, but also how OpenSats could serve designers on open-source Bitcoin well.

**[2. Solve a specific problem](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md#2-solve-a-specific-problem)**
We could put out briefs for these to see if anyone wants to help out.
1. Usability tips
2. Overall web design

**[5. Find a designer](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md#5-find-a-designer)**
With this issue, posts in Slack and the newsletter, we could give the project more visibility to help find a designer to tackle what's described above.

Those are my thoughts from the call yesterday. Feel free to add.

**Comment by GBKS** [comment]
Tanner worked on Logo explorations in this [Figma file](https://www.figma.com/file/dRCt9qnrIkSsQZH7bOAfj2/open-sats-design?node-id=0%3A1).

@barefoot-88 is working on the website design [here](https://www.figma.com/file/r7iu1Ph8qz5zGmtcbz4LlQ/_OpenSats?node-id=14%3A0).

We discussed the design work in the [Design Review Call #15](https://github.com/BitcoinDesign/Meta/issues/103), you can watch the [recording here](https://www.youtube.com/watch?v=Ih-VTp6Hz-k).

**Comment by pavlenex** [comment]
Should we close this? There's now a new site?

**Comment by GBKS** [comment]
Still the old site. OpenSats as an entity is doing things, but not sure what the status is on the web project. Maybe they'd like some open-source design contributions? We could ask Ben to see if he wants to revive this...

**Comment by GBKS** [comment]
Closing this one for now. We can re-open if there's new activity.
