### ISSUE TITLE
Figma crash course #2

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#11]
```meta
Date: 2020-08-26
Time: 5pm CEST
```

![1*jNGdZPcjAINHhBERw_gwPA](https://user-images.githubusercontent.com/695901/91145245-6ff4ba80-e6b5-11ea-856e-676b5a6f90e7.jpeg)

### Agenda

An overview of how Figma can be used to collaborate on designing applications. Still working out the details, but here are some things I'll try to cover:
- Introduction to Figma
- Basic tools
- Good practices for structuring files 
- Collaboration
- Tools for developers
- Using Figma for open-source

The call will be recorded. I'll try to balance a mix of a structured agenda and answering questions on the go.

### Check your timezone

https://everytimezone.com/s/997be44a

### Join the call

https://meet.google.com/gzv-asoh-are

### Calendar invite

[Via Google Calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MW5wN2J2Z3A0aWVsaHFvZWloOTB2aHQ1MmUgNms5cnF2c2dtamJmZGphaWppYzk4cnY3aW9AZw&tmsrc=6k9rqvsgmjbfdjaijic98rv7io%40group.calendar.google.com)

**Comment by Bosch-0** [comment]
Keen!

**Comment by GBKS** [comment]
And here's the recording, with only a few minor issues (cursor didn’t get recorded, I didn’t capture or repeat questions that were asked, and my recording app broke a few minutes before we were done). https://youtu.be/_B_Yotf9Qqs

Surprisingly tricky to record a video call and a screen share at the same time. Will have to improve this in the future.
