### ISSUE TITLE
Bitcoin Core GUI call #2

### ISSUE THREAD

**Issue by michaelfolkson** [BitcoinDesign/Meta#12]
```meta
Date: 2020-09-03
Time: 8:00am CEST for 1 hour
```

Transcript of previous Bitcoin Core GUI call: https://diyhpl.us/wiki/transcripts/bitcoin-design/2020-08-20-bitcoin-core-gui/

### Agenda

Add links in the comments for what you would like to discuss

### Check your timezone

- https://everytimezone.com/s/31249bf8

### Join the call

- https://meet.jit.si/bitcoindesign

**Comment by michaelfolkson** [comment]
Understanding the history of Core GUI changes: https://github.com/BitcoinDesign/Guide/issues/16

**Comment by hebasto** [comment]
Topic: Font policy.

1) Embedded (platform independent) fonts or system ones (defined by platform)
2) When do use and do not use monospaced fonts
3) ...

Context:
- https://github.com/bitcoin-core/gui/pull/79
- https://bitcoindesign.slack.com/archives/C018PM159JS/p1598567309121600

**Comment by Bosch-0** [comment]
On-boarding Wizard V1: https://github.com/bitcoin-core/gui/issues/81 

Would also like to discuss V2 and V3 concepts I have in mind. 

Not a major priority but re-working the icon set is something I'd like to discuss briefly - personally I think using [material icons](https://material.io/resources/icons/?style=baseline) would suffice, it covers pretty much all bases and aligns with the minimalist style of the GUI. I was going to post a issue for this on the GUI repo but would prefer all your input first.

**Comment by hebasto** [comment]
One more topic from me. Is it allowed?
"Current state of the GUI migration from Widgets to QML"

Ref: https://github.com/bitcoin/bitcoin/pull/16883#issuecomment-683817472

**Comment by michaelfolkson** [comment]
Sure. We may need to be organized to fit everything into the hour.

**Comment by Bosch-0** [comment]
Just added my comments on that PR @hebasto

**Comment by hebasto** [comment]
One more topic :)
"How designers could review the GUI PRs"
