### ISSUE TITLE
Design Review call #1

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Meta#14]
```yaml
Date: 2020-09-14
Time: 12:00pm GMT for 1 hour approx
```
### Agenda
1. [V2 of the guide website](https://github.com/BitcoinDesign/Guide/issues/11)
2. [Bitcoin Core GUI onboarding ](https://www.figma.com/file/FJ02rY3m8V9ZCDvoXjW39W/Bitcoin-Core?node-id=462%3A733)
3. [Multisig Concept](https://www.figma.com/file/RcMFUM87Adz8jnVZPQoXNj/Multisig?node-id=0%3A1)
4. [Coin Control Concept](https://www.figma.com/file/mPoRMRTBOvi61M8psIp4XY/Coin-Control?node-id=0%3A1)

Please leave a comment if you would like something reviewed in this session.

### Check your timezone
https://everytimezone.com/?t=5f5eb280,294

### Join the call 
https://meet.jit.si/bitcoindesign

**Comment by Bosch-0** [comment]
Usually available between 10AM AWST to 10PM AWST all days except Sunday

**Comment by ConorOkus** [comment]
**Summary**

**V2 of the Guide Website** (Alexa Aker, Christoph Ono)
We looked through the amazing work on designs for version 2 of the design guide website. The heading consists of an illustration that uses the traditional Bitcoin icon and emphasises the decentralized nature of the network. We spoke about an alternative symbol to represent satoshi's as the current implementation might be confused with the USD dollar. The concept of having a coin icon representing the heading in each section went down well but some of the terminology such as "belong" could be changed to something more welcoming e.g "join".

**Bitcoin Core GUI onboarding** (Bosch)
Some great work being done here to simplify onboarding for those wanting to run their own nodes. The key takeaway is the use of the original Bitcoin logo and branding being used inconsistently around Bitcoin core. You can follow the discussion on this [here](https://github.com/bitcoin-core/gui/issues/89).

**Multisig Concept** (Nuno)
Positive start on developing a multi-signature wallet here. We had a lot of discussion about some of the concepts being surfaced in the UI e.g "vault", "seed", "wallet". Multi sig is hard! We talked about comparing a multi-sig wallet to a joint account in the real world and whether we can frame this type of wallet in reference to this. The bottom sheet pattern looks good from a visual point of view. 

**Coin Control Concept** (Nuno)
Nice concept to differentiate the different UTXO's for selection by using different colours. Some slight confusion around the use of labels, do they represent where the coins have come from or where they are being sent to?

**Comment by jonatack** [comment]
Thanks for the summary. I'll try to make the next call to watch and listen.
