### ISSUE TITLE
Choosing a license and handling open design contributions

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Meta#15]
Wanted to start the discussion around how we handle the licensing to the guide, and other community initiatives.
We definitely need some legal peoples to also chime in.

### Current State: No License
> _When you make a creative work (which includes code), the work is under exclusive copyright by default_

> _Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose._

### Project Content / Software License
- How do we handle derivatives, do we use a copyleft or more permissive software license?
- What happens if the project gets copied rebranded, attributions removed, and relicensed?
- What happens if some YouTuber decides to create a course out of the content and charge for it?

### ~~Contributor License Agreement~~
- ~~What happens if someone contributes copyrighted material and it gets merged?~~
- ~~What protections are given to other contributors?~~
- ~~What happens if an anon on a Design Review Call #14 contributes a sketch or idea. Do they need to sign a CLA?~~

### ~~Compliance Tools~~
~~CLA Assistant is a tool that is used to add a status check on a PR which prompted the contributor to sign the agreement so checks can pass and the contribution can be merged. It only needs to be done on the first contribution, and will apply to all others unless the agreement is updated. If the agreement does change, CLA Assistant will trigger the agreement to be resigned by all contributors.~~
- ~~https://cla-assistant.io~~

**EDIT: We don't need a CLA.** [Read why](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/)

### REF
- The legal side of open source - https://opensource.guide/legal
- https://choosealicense.com

**Comment by Bosch-0** [comment]
Core has this doc for icon licensing - https://github.com/bitcoin/bitcoin/blob/master/contrib/debian/copyright

May be useful to see how they do it.

**Comment by moneyball** [comment]
Rust-lightning just adopted a dual-license approach which I'd recommend for this community. MIT provides permissiveness and Apache provides language around patents. https://github.com/rust-bitcoin/rust-lightning/blob/master/LICENSE.md

**Comment by AlexaAker** [comment]
It should follow bitcoin's principles and be open to anyone who would like to use it. 

Agree with the MIT & Apache licensing with specific labeling for copyrighted materials used, as Steve suggests.

It should probably include a Commons License too for illustrations or photographs.

We should add it to the website's footer.

**Comment by GBKS** [comment]
After doing some studying, here is what I found:

The [MIT license](https://choosealicense.com/licenses/mit/) does not protect from patent litigation. That was apparently not a big problem when it was created, and the [Apache 2.0 license](https://choosealicense.com/licenses/apache-2.0/) addresses this. 

For images, as Alexa suggested, it would be good to also offer a Creative Commons license as that is more applicable to creative work. Figma community files are licensed under [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/), while Mastering Bitcoin by Andreas Antonopoulos is licensed under [Creative Commons Attribution-ShareAlike 4.0 International](https://github.com/bitcoinbook/bitcoinbook/blob/develop/LICENSE). The difference is that any work that builds on Mastering Bitcoin has to use the same license as the original. Remixes of Figma files can be distributed under other licenses also (same as MIT and Apache 2.0 licenses). Any thoughts on this?

I spliced together some text from a few sources to come up with a suggestion. References:
- [Declaring multiple licences in a GitHub project](https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project)
- [StackExchange comment](https://softwareengineering.stackexchange.com/a/318783) about including an extra license for images
- [Rust-lightning license](https://github.com/rust-bitcoin/rust-lightning/blob/master/LICENSE.md)

```
This project is free software. There is no warranty; not even for
merchantability or fitness for a particular purpose.

Some files retain their own copyright notice, however, for full authorship
information, see version control history.

Except as otherwise noted in individual files, or LICENSE files in source code 
directories, all files in this repository are licensed under the [Apache License, Version 2.0](LICENSE-APACHE) 
or the [MIT license](LICENSE-MIT], at your option.

In addition, you may -- at your option -- use, copy, modify and redistribute all
images included in this distribution under the directory named `assets`
according to the terms and conditions of the [Creative Commons Attribution 4.0
International License](LICENSE-CC-BY).

You may not use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of this software or any files in this repository except in
accordance with one, both, or all three of these licenses.
```

Once we have setup a license file, we can then install the CLA assistant Johns linked to for getting all contributions/contributors automatically on the right licensing model.

That's what I gathered from reading up on this today. I'm sure I missed things, so please let me know what your take is. It's a balance of being permissive so others can contribute and improve things, but also being a bit defensive so nobody can easily abuse or profit from the effort of the community.

I'll also look into best practices for attributing sources and references on rendered content pages but I think that's a separate task.

**Comment by moneyball** [comment]
Thank you for researching this! I lean toward as permissive as possible so ShareAlike doesn't sound consistent with community goals.

**Comment by danielnordh** [comment]
Thanks Christoph! 
Why offer a choice of MIT or Apache, wouldn't it be simpler to just stick with Apache?
Agree with Steve that ShareAlike seems unnecessary.

**Comment by moneyball** [comment]
Is there an example of any project that gives contributors choices of
license? That seems like it would create massive confusion to me. What is
controversial about supporting dual or triple licenses? What is the
drawback?

**Comment by GBKS** [comment]
@moneyball rust-lightning, which you referenced further up, uses a dual-license approach.

We're essentially saying that when somebody uses this content and publishes it elsewhere, that they can choose one of those licenses for that new publication. So if they are worried about patents, they can use Apache. Or if they come from a design background and are more familiar with creative commons, they can choose that one.

None of those licenses include anything about warranty or liability (see [here](https://choosealicense.com/licenses/)), that's why I included that first sentence (also copied from a reference). Otherwise, I am not sure what type of problems are likely to come up. Are you aware of any incidents or discussions on what can go wrong with different licenses?

**Comment by moneyball** [comment]
ok i think i see where the (my?) confusion is. _contributors_ agree to all
licenses. _users_ can choose.

**Comment by GBKS** [comment]
That's my understanding, too. Contributors state that their work is good to be published under all licenses as described. Users can choose under which license they want to use the code/content for their own purposes.

**Comment by GBKS** [comment]
I created a PR for this license update [here](https://github.com/BitcoinDesign/Guide/pull/32). Please take a look.

**Comment by johnsBeharry** [comment]
Closing this off as all aspects have been addressed. We don't need a CLA or use a compliance tool like CLA Assistant either since it's a fully open source community -- [read more](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/).
