### ISSUE TITLE
Bitcoin Core / Improve Beginner Onboarding

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#17]
Converted this issue from a note for Bosch as he is working on this.

**Comment by Bosch-0** [comment]
Current designs for 1.0 on-boarding for Bitcoin Core GUI - https://github.com/bitcoin-core/gui/issues/81

Just a note on why I have chosen to do this in stages - simply put, posting a whole on-boarding process would be overwhelming for developers and wouldn't really align with the conservative / incremental way changes are made on Bitcoin Core. This is something to keep in mind when contributing anything to Bitcoin Core whether code or designs. This is a great, plain English explanation of contributing to core everyone interested should read - https://bitcointechtalk.com/a-gentle-introduction-to-bitcoin-core-development-fdc95eaee6b8. 

2.0 Designs will implement some basic create wallet options and possibly HWI integration depending how testing progresses around https://github.com/bitcoin-core/gui/pull/4. If any designers want a walk through how to compile and test this PR give me a message - happy to walk anyone through it. Will likely write up a small guide targeted at designers for how to do this as well in the coming week.

**Comment by GBKS** [comment]
@Bosch-0 do you still need or use this issue?

**Comment by Bosch-0** [comment]
Not currently no, can close this for now and will re-open once I begin working on this again (likely be a different approach focusing on a QML based GUI).
