### ISSUE TITLE
Hello Bitcoin Video #4 Jam Session

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#174]
```meta
Date: 2021-10-20
Time: 6:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-10-20 18:00 UTC
```

![hello-bitcoin-poster](https://user-images.githubusercontent.com/2414177/135768230-3e438453-4b43-4093-914d-baf0aa02145e.png)

### Agenda

In this call, we will share progress on Hello Bitcoin video 4 and discuss next steps in the project.

### Check your timezone

https://everytimezone.com/s/e5679f42

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by GBKS** [comment]
Can this be closed? The call was a month ago.
