### ISSUE TITLE
Bitcoin Core / Research the history of Core GUI changes through Github issues

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Meta#19]
### Abstract
In order to start a redesign of Bitcoin Core GUI, we should try to understand design constraints, and technical decisions that have lead to its current state.

The way we do this would be to start gathering links to issues that may be relevant to any redesign efforts so designers coming in do not make assumptions and waste time on things that are not practical, or have already explored.

### Motivation
We would need to come up with a strategy to get designers involved in the ongoing UI/UX decisions made to the GUI, and find out if it's practical to make more substantial improvements to the UI, and understanding how to go about doing so.

### Issues
- https://github.com/bitcoin/bitcoin/pull/16883
- https://github.com/bitcoin-core/gui/issues/24
- https://github.com/bitcoin/bitcoin/pull/14810#issuecomment-635804151

---

### REF

- [Bitcoin Core GUI / Design Jam Notes](https://hackmd.io/XdI-wmBMRES96HL8x_KDCQ)
- [Discussion on Slack](https://bitcoindesign.slack.com/archives/C0174N5KUF9/p1596267094004700)

**Comment by jonatack** [comment]
> Every new feature gets implemented as a RPC call, then after about 2 releases (once stability is confirmed) it is implemented in the GUI.

This seems generally true. Yet open source is an ad-hoc, scratch-your-own-itch process and in practice I have the impression there are quite a few exceptions that can depend on the initiative of each contributor. Two examples I've been involved with, for an idea:

- the GUI has displayed the number of in and out peer connections for years; the same via the RPC (`getnetworkinfo`) and a CLI option (`-getinfo`) was only just now merged into Bitcoin Core master for the next release in November

- the experimental Asmap feature info was first exposed via both the RPC (`getpeerinfo`) and the GUI (peers detail window) in the same release

That said, the general concept you've expressed is very good.

**Comment by danielnordh** [comment]
Is this issue still relevant?
@Bosch-0 has been doing work elsewhere on Core UI.
