### ISSUE TITLE
Wallet review call #5

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Meta#195]
```meta
Date: 2021-12-02
Time: 4:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-12-02 16:00 UTC
```

### Agenda

1. To be determined in #194 

### Check your timezone

https://everytimezone.com/s/527fbe87

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by sbddesign** [comment]
We discussed the [Bitcoin Beach wallet](https://galoy.io/bitcoin-beach/) by [Galoy](https://galoy.io/) from the perspective of new users, including the onboarding process, sending, and receiving bitcoin.

- [Call Notes](https://docs.google.com/document/d/1SjsT4cZrM74AJnz8KBehV5d0lK93lGsah-B56t4P01I/edit?usp=sharing)
- [Watch on YouTube](https://youtu.be/Aot8zRJ5Zd0)
- [Watch on BitcoinTV](https://bitcointv.com/w/34B6VEC4goCm3PpihiETHy)
