### ISSUE TITLE
Wallet review call #6: Muun

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Meta#196]
```meta
Date: 2021-12-09
Time: 4:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-12-09 16:00 UTC
```

![wallet-improvement-project-muun-211208](https://user-images.githubusercontent.com/695901/145178368-6886ed62-45b4-44d6-865b-de6c0a271116.jpg)

### Agenda

We'll discuss the user experience of [Muun](https://muun.com/). If possible, please download and try out the app in advance and come prepared with notes.

### Check your timezone

https://everytimezone.com/s/10c4cd6d

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by sbddesign** [comment]
Let's talk about [Muun Wallet](https://muun.com/).

**Comment by esneider** [comment]
Hello there 👋 

Are there any meeting notes that we can check? We’d love to hear suggestions on how to fix or improve Muun!

**Comment by sbddesign** [comment]
- [Call Notes](https://docs.google.com/document/d/1-od06SZav8jvoN6luSzadqRMOZcuApk7bDmaSv6sI0U/edit#)
- [YouTube](https://youtu.be/S4SxVlZ4TnQ)
- [BitcoinTV](https://bitcointv.com/w/29WP2yjCr2ogySGGTfurWg)

**Comment by sbddesign** [comment]
> Hello there 👋
> 
> Are there any meeting notes that we can check? We’d love to hear suggestions on how to fix or improve Muun!

@esneider Overall, we had a very positive experience with Muun, but we documented questions and friction points. See above comment for call recording as well as a Google Doc with notes. Let us know if you'd like to continue this conversation. We could start a thread in Slack or have a Jitsi call sometime.

If it's helpful, we can open up clearly scoped issues or feature requests in your GitHub repos.
