### ISSUE TITLE
Welcome New Members Dec2021

### ISSUE THREAD

**Issue by dulcedu** [BitcoinDesign/Meta#209]
```meta
Date: 2021-12-16
Time: 5:00pm
Timezone: UTCTime
Duration: 1h
UTCTime: 2021-12-16 17:00 UTC
```
![New Members Mixer](https://user-images.githubusercontent.com/11275066/145860204-c18f1cb3-7568-4e59-a78f-3c5c6dd44391.jpg)

### Agenda

1. Introductions
2. What is Bitcoin Design Community? 
3. Where you can start contributing? 
 3.1 Bitcoin Design projects that need help and how you can contribute
4. Q&A 

### Check your timezone

https://everytimezone.com/s/d28c5525

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here.](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar)

**Comment by Bosch-0** [comment]
I could see this call getting quite large of which may crash Jitis, should we do a Twitter Space for this?

**Comment by dulcedu** [comment]
In ChainCode study groups, jitsi hosted more than 50 people without a problem. If it crashes we can move to zoom I have access to a non-profit account with webinar access. The advantage of using Jitsi or Zoom is that we can share screens and explain where exactly is the information.

**Comment by sbddesign** [comment]
> I could see this call getting quite large of which may crash Jitsi, should we do a Twitter Space for this?

@Bosch-0 I don't think Twitter spaces is a good fit. We will want to be able to do desktop screen sharing to discuss projects that people can help out with. Additionally, I don't think the stage/audience dichotomy is fully compatible with a meet-and-greet.

But you have a reasonable concern. We can use a backup platform if Jitsi crashes. If we have enough people to crash Jitsi, then that will be an exciting amount of new contribs. 🙂

**Comment by GBKS** [comment]
Closing this one out. Call recordings are available on [BitcoinTV](https://bitcointv.com/w/pZPyj9riUeMc1ULK9tWs5W) & [YouTube](https://youtu.be/U1c7nUHqvXg).
