### ISSUE TITLE
Slack link is no longer active

### ISSUE THREAD

**Issue by jurjendevries** [BitcoinDesign/Meta#215]
Dear community,

When I click the slack link (found it by Alby) I got a "This link is no longer active" error.
I don't know the new link, so I can't update it on the pages.

Beside that I am curious why a BTC community is using Slack which is closed centralized non-community based company, while for example Matrix.org is more in the values of BTC with its free open source decentralized protocol, server and clients. So maybe a good moment to switch? Curious how governance about that is working.

Best,
Jurjen

**Comment by moneyball** [comment]
Thanks for reporting. Last I checked the expiration date from Slack was
literally in the year 2,300 :)

I now discovered a way to generate a link that never expires, so let's try
adding this to the website:

https://join.slack.com/t/bitcoindesign/shared_invite/zt-10sxfovaq-isViijl4RThKRs_TsAQnuA
