### ISSUE TITLE
Wallet Design Improvement Project: Blixt Design Sprint Call #2

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#227]
```meta
Date: 2022-02-15
Time: 17:00 
Timezone: UTC
Duration: 2h
UTCTime: 2022-02-15 17:00 UTC
```

![wallet-design-improvement-project-blixt-design-sprint-call-2](https://user-images.githubusercontent.com/695901/154055642-965cd2e0-d821-42c8-9c53-b188d7c2ac75.jpg)

### Agenda

- Conduct a design sprint based on our earlier research. Lasts for 2 hours.
- Design sprint template that we'll use
- Design sprint demo video to familiarize yourself with a process
- Requirements: Miro account, paper and sharpie.

### Roles
- Faciliatotor: Johns
- Assistant: Pavlenex
- Designers (anyone welcome to join and help us tackle wicked problems)

### Check your timezone

https://everytimezone.com/s/254ad18f

### Join the call

The call will be hosted via Jitsi:
https://meet.jit.si/bitcoindesign

### Calendar

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by sbddesign** [comment]
Call recording available here:
- [BitcoinTV](https://bitcointv.com/w/eoLhGYizDT4QRPiY9jGNjR)
- [YouTube](https://youtu.be/1PKMrML-sR0)
