### ISSUE TITLE
Design Review call #2

### ISSUE THREAD

**Issue by ConorOkus** [BitcoinDesign/Meta#23]
```yaml
Date: 2020-09-28
Time: 1pm PT (Approx 1 hour)
```
### Agenda TBC
 - Multi-Signature Wallet, @thibistaken
 - [Coinjoin UX session](https://miro.com/app/board/o9J_knmJ_C0=/) - @johnsBeharry 
 - UX collaboration on [Firma](https://github.com/RCasatta/firma) - @RCasatta

Please leave a comment if you would like something reviewed in this session.

### Check your timezone TBC
https://everytimezone.com/zones?t=5f712780,4b0

### Join the call 
https://meet.jit.si/bitcoindesign

**Comment by Bosch-0** [comment]
Although no designs exist yet, would @Rcasatta want to discuss how we as designers could help his project [firma](https://github.com/RCasatta/firma)? Sorry if this is out of the scope of these review calls.

**Comment by RCasatta** [comment]
If the broader team thinks it's in scope and if the time it's not in conflict with my agenda/sleeping hours I would love to join

**Comment by johnsBeharry** [comment]
Would like to get some feedback on some of the work we've been doing in these [coinjoin ux sessions](https://miro.com/app/board/o9J_knmJ_C0=/) I've been doing with @nothingmuch and other wallet developers. It touches on coin control and privacy but deals more with documentation and the design thinking process.

**Comment by jonatack** [comment]
Added to my calendar for now.

**Comment by ConorOkus** [comment]
@Bosch-0 @RCasatta I think the project looks great, I would like to see people presenting something visual even if it's just a diagram of a flow, as the goal at least from my perspective is for the person or group to get UX/UI related feedback. Just my thoughts, not sure how others feel...?

**Comment by GBKS** [comment]
Also would love to discuss the potential for a UX collaboration on Firma.

**Comment by RCasatta** [comment]
@ConorOkus I am not familiar with tools to present something visual, maybe someone could help by bootstrapping it with the current android app?

A little introduction for someone who wants to take the task:
Firma is clearly divided between online and offline flow. I would let aside the online flow for now since at the moment it's only command-line based while the offline flow could be done also on android.
Firma testnet is available to download on the store https://play.google.com/store/apps/details?id=it.casatta.testnet&hl=en, to properly try it you will need some example data since we skipped the initial setup and the online flow, data available here https://github.com/RCasatta/firma/tree/master/android#example.
Note that the version currently in the store break at sign, I already uploaded version 1.12 but it's not available in the store yet

**Comment by ConorOkus** [comment]
No worries @RCasatta come along and we can just have an open discussion around and take it from there 👍

**Comment by ConorOkus** [comment]
**Summary**

**Multi-Signature Wallet - @thibistaken**
Thibm took us through his prototype for a Multi-Signature coordinator application aimed at fairly advanced Bitcoin users who have been using hardware wallets and dollar-cost averaging. The wallet aims to support various hardware wallets including ledger, trezor, coldcard and cobo. There are options for a 2-3 or a 3-5 setup. The prototype takes you through a very easy to understand setup process with each step being clearly defined. There was some conversation around verifying Xpubs, it's unlikely someone will check every character is correct so is it okay to for the UI to lead them in the direction of checking the first 8 or so characters, is that sufficient? There were also comments about the order in which you set up the hardware devices, the UI perhaps hinted that you would need to do one before the other when that is not necessarily the case. Some nice use of tooltips to highlight important but not mission-critical information as well. We briefly looked a wonderful looking dashboard which would show you the balance and allow you to send and receive. Didn't have much time to dig in to so would love to see that in a future review.    

**Coinjoin UX session - @johnsBeharry**
Johns has been doing some incredible work in partnership with some of the Wasabi and WabiSabi team members. He took us through his extremely detailed design sprint which can be found [here](https://miro.com/app/board/o9J_knmJ_C0=/). The overarching theme is, how do we get more designers to understand enough of the technical implementations such that we can build UI's that are able to surface features that are true enough to these complex privacy-focused protocols? Can we create educational resources for designers so that each individual designer doesn't have to dig deep into the protocol to understand its possibilities? We want to put privacy at the core of the design process and not an afterthought. Please reach out the John is you have any questions or ideas on how we can make this happen.
