### ISSUE TITLE
Wallet Design Improvement Call #2: Blixt Introduction

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Meta#232]
```meta
Date: 2021-02-01
Time: 4:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-02-01 16:00 UTC
```

![wallet-design-improvement-project-2](https://user-images.githubusercontent.com/695901/152112994-70a4363d-3185-4a76-9e74-84764341555b.jpg)

The goal of this call is to ask as many questions and learn about Blixt, it’s goals, target-users, known problems, how we may help the project, etc.

Some really good reading materials for preparation - feel free to make your own doc, write questions and whatever you think is necessary to learn more about the Blixt on the resources already available. There are no really rules on how we learn about Blixt before call, experimentation is welcome. Make sure to write as many questions that come to your mind, Blixt maintainer Hampus will be there with us answering them.

### Agenda

[https://docs.google.com/document/d/1bgd1uI0PKAn0GFZTtqLY_rzlMdYxEk-7g6KiP0QzkLU/edit?usp=sharing](https://docs.google.com/document/d/1bgd1uI0PKAn0GFZTtqLY_rzlMdYxEk-7g6KiP0QzkLU/edit?usp=sharing)

[LINK FOR TIMEZONE e.g. from everytimezone.com](https://everytimezone.com/s/731a800d)

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

[LINK TO CALENDAR INVITE]

**Comment by GBKS** [comment]
Thanks to all who joined the call. It was really good to connect with Hampus, hear about the project from the person who created it, and ask lots of questions. Recordings are now available via [BitcoinTV](https://bitcointv.com/w/3Msh1axhTMEx5qgxHesJ1B) and [YouTube](https://youtu.be/GYw3bEN10Q8).
