### ISSUE TITLE
... Design Call #0

### ISSUE THREAD

**Issue by Sadeghi1017** [BitcoinDesign/Meta#235]
```meta
Date: 2021-MM-DD
Time: 4:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2021-MM-DD 16:00 UTC
```

[Incredibly well-designed event cover image, see other call issues for inspiration but feel free to put your own touch on it. Landscape formats work best.]

### Agenda

1. ...

### Check your timezone

[LINK FOR TIMEZONE e.g. from everytimezone.com]

### Join the call

[LINK FOR CALL]

### Calendar invite

[LINK TO CALENDAR INVITE]

**Comment by GBKS** [comment]
Howdy. Was this intentionally created?
