### ISSUE TITLE
Bitcoin Design Sprints

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Meta#244]
This is a tracker issue for Bitcoin Design Sprints, formerly known as the `Wallet Improvement Project`.

The mission is to run design sprints for community projects, currently with a focus on mobile Lightning wallets. A group gets together to research, brainstorm, concept, and propose solutions to improve the project at hand. More about [design sprints](https://www.gv.com/sprint/).

**Comment by GBKS** [comment]
Creating a tracker comment here for the Blixt project:

Calls:
- [Introduction](https://github.com/BitcoinDesign/Meta/issues/232)
- [Sprint #0](https://github.com/BitcoinDesign/Meta/issues/236) to define the scope and focus
- [Sprint #1](https://github.com/BitcoinDesign/Meta/issues/225)
- [Sprint #2](https://github.com/BitcoinDesign/Meta/issues/227)

Files:
- [Initial project doc](https://docs.google.com/document/d/1bgd1uI0PKAn0GFZTtqLY_rzlMdYxEk-7g6KiP0QzkLU/edit?usp=sharing)
- [Figjam sprint board](https://www.figma.com/file/spI8SQHoHA174tmnEH16aS/Blixt-Design-Sprint?node-id=0%3A1)
- [Figma base storyboard by Johns](https://www.figma.com/file/myGOlIs03amNtK5g6MzNty/Blixt-Onboarding?node-id=0%3A1)
- [Figma by Stephen](https://www.figma.com/file/9qKXtl3F0orwUCPgJ9ujgO/Blixt-Wallet-Designs?node-id=0%3A1) (Feb 24)
- [Figma by Raj](https://www.figma.com/file/Y8OKn4R3ZAQ9JzGv5C8pEg/Blixt-UI?node-id=0%3A1) (Feb 27)
- [Figma by Mili](https://www.figma.com/file/PkLRYKcqTiIrxxXiedRTwr/Blixt-Design-Sprints?node-id=3152%3A73685) (Mar 3)

We can keep updating this with links as needed. Just thought it'd be good to have these in one place.

**Comment by GBKS** [comment]
Brief update on this [by Mili](https://bitcoindesign.slack.com/archives/C02VCHSQECT/p1650638128477989). Herself, Mo, and Hampus reviewed the latest designs and decided on various tweaks to the onboarding content. Once those are resolved, they will move to high-fidelity designs.

**Comment by GBKS** [comment]
The project has continued in the [#wallet-improvement](https://bitcoindesign.slack.com/archives/C02VCHSQECT) channel via several calls. Goal is at the moment to finalize the onboarding flow, create and test a clickable prototype, and wrap things up nicely with a case study.

- [Call recording](https://www.youtube.com/watch?v=CwRuGdfd51s) from June 29
- [Call recording](https://www.youtube.com/watch?v=sEfT8hbuX78&t=588s) from May 25
- [Call recording](https://www.youtube.com/watch?v=Z5XFKR3q_xU) and [issue](https://github.com/BitcoinDesign/Meta/issues/258) from March 18

**Comment by GBKS** [comment]
The team has now put together a [prototype](https://www.figma.com/proto/myGOlIs03amNtK5g6MzNty/Blixt-Onboarding?node-id=897%3A26857&scaling=scale-down&page-id=897%3A25291&starting-point-node-id=897%3A26857) that will be tested with users.

**Comment by ShalomOhuegbe** [comment]
@GBKS I see that this project is presently in the user testing phase. Can I help test the product with users? Is there a team of UX testers already? If yes, I am very interested in joining that team and documenting the key takeaways. I can also help with creating a testing script

**Comment by GBKS** [comment]
Hi Shalom. Thanks for your interest. This is the same project you already commented on [here](https://github.com/BitcoinDesign/Guide/issues/927). @mouxdesign is currently wrapping it the final summary case study, so the design and research work is complete.

Are you looking to contribute to bitcoin research projects specifically?

**Comment by ShalomOhuegbe** [comment]
@GBKS Yes, i am research focused so i am looking for research projects/UX projects to contribute to. Thanks

**Comment by GBKS** [comment]
With the [Blixt case study page](https://bitcoin.design/guide/case-studies/blixt-wallet/) now live (via [this PR](https://github.com/BitcoinDesign/Guide/pull/937)), we have wrapped up our first sprint. It ended up taking much longer and more involved than originally planned. Part of this was also scope creep. Instead of just doing the initial brief sprint, a few people continued to go through multiple full design iterations and testing (super cool they did).

We don't have any plans for further sprints, so should we close this one? Does anyone feel strongly that we should continue this format as a series (an alternate approach would be to do sprints in the context of projects as they come up - instead of a continuous series)?

**Comment by sbddesign** [comment]
First and foremost, somebody needs to love doing this and own this. If somebody wants to step up and lead this effort, it would be cool. And they should be scoped more tightly and limited in time.

Nothing wrong with a long-form design project. These sorts of long-form projects can be really nice, but then it becomes like any other Community project collaboration, e.g. Alby, Zeus, Bitcoin Core, etc. and sort of has its own project management structure.

So if nobody is stepping up to lead this effort, let's close it.

**Comment by johnsBeharry** [comment]
Agree it should be very tightly scoped. I think Mo was working on something regarding a new proposal to the format. My own format is 8 days. In our open design format it seems to have broken down when entering the prototyping phase, so I would suggest next time if we continue this for that activity to be really strict to the sprint question that were settled on during the interactive sessions with the wallet maker.

**Comment by mouxdesign** [comment]
Happy to close this one as well. I think that the lesson learnt is that there are alot of projects which pop up in the community which reach out and request some form of collaborative effort. Lessons learnt:

-  It feels much more relaxed doing these collaborative efforts when the project themselves are invested in the redesign process. So often a project reaching out is an indication of their dedication/openness to redesigning (versus the community reaching out to a project and offering help)
- Time constraints: a project setting up their own slack channel/inviting us to their Discord is also a nice continuous way of working with/alongside these projects. 
- Oppurtunites to learn: The original way of doing a sprint would be to use a design sprint format. I love using a structured approach however I have also learnt that we can learn alot from different open source projects by gaining some insight into how they would choose to do the re-design. We can learn from these projects/methodologies and ideally share them as case studies in the guide. 

A good approach would be documenting these and sharing them as case studies in the guide as a time investment versus spending time approaching projects to sprint with. Allow the projects that are currently moving forward consistently to shine and learn from them and help them in any way we can.

**Comment by GBKS** [comment]
Alright, I think it's time to close this issue now. We are still working with plenty of projects directly, just not as a series of sprints in the format outlined here but more based on need and context. If you'd like to open this issue up again for some reason, please state so and we can do that.
