### ISSUE TITLE
Add Wallet Improvement Project to Projects page

### ISSUE THREAD

**Issue by moneyball** [BitcoinDesign/Meta#246]
As discussed here: https://bitcoindesign.slack.com/archives/C02VCHSQECT/p1644452786804979

FWIW someone reached out to me today asking me where to find info about this. I think it'd be easier to find with this suggested change.

<img width="410" alt="Screen Shot 2022-02-14 at 9 14 06 PM" src="https://user-images.githubusercontent.com/326147/153996947-63e9e959-f6a5-4a02-b49f-81113839f24f.png">

**Comment by Bosch-0** [comment]
https://github.com/BitcoinDesign/Guide/pull/665 addresses this
