### ISSUE TITLE
Galoy project call #1

### ISSUE THREAD

**Issue by daviroo** [BitcoinDesign/Meta#247]
```meta
Date: 2022-02-23
Time: 6:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-02-23 18:00 UTC
```

![image](https://user-images.githubusercontent.com/3502409/154054819-edf9f95e-810d-4bef-bd0c-e4788e61e655.png)

### Agenda

The first in a regularly scheduled series of calls between Galoy team members, representatives from the communities who run on Galoy software and the bitcoin design community.  [Galoy](https://galoy.io/products) provide an open source Bitcoin banking solution for communities and institutions - most famously the [bitcoin beach wallet](https://galoy.io/bitcoin-beach-wallet) is powered by Galoy.

For our first call we will present a proposed change to our receive bitcoin flow for merchants and the UI/UX challenges which we have found while trying to display different [receive request types](https://bitcoin.design/guide/payments/request/#reusable-payment-requests) in a way which makes sense to users who are unfamiliar with the underlying technologies at play.

### Check your timezone

https://everytimezone.com/s/2a8402ee

### Join the call

https://meet.jit.si/moderated/92c5f09ddcbebb15eb99eb5f6ec33714f0745eea1acd1ecd82e273dae18370f5

### Calendar invite

https://calendar.google.com/event?action=TEMPLATE&tmeid=MjFtN2c2ZjJtZTJ0bmlxcmd0amhtYmg3MjBfMjAyMjAyMjNUMTgwMDAwWiBjX2kzZGpydW9vOTVqb3ZpdXV0NjZoYW1lZmhzQGc&tmsrc=c_i3djruoo95joviuut66hamefhs%40group.calendar.google.com&scp=ALL

**Comment by GBKS** [comment]
Recordings are now up on [BitcoinTV](https://bitcointv.com/w/faJPxMXrTAW1mJ1WVykC56) and [YouTube](https://youtu.be/dJquKMR03PA).
