### ISSUE TITLE
Galoy Project Call #2

### ISSUE THREAD

**Issue by daviroo** [BitcoinDesign/Meta#252]
```meta
Date: 2022-02-23
Time: 6:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-03-09 18:00 UTC
```

![image](https://user-images.githubusercontent.com/3502409/154054819-edf9f95e-810d-4bef-bd0c-e4788e61e655.png)

### Agenda

The second in a regularly scheduled series of calls between Galoy team members, representatives from the communities who run on Galoy software and the bitcoin design community.  [Galoy](https://galoy.io/products) provide an open source Bitcoin banking solution for communities and institutions - most famously the [bitcoin beach wallet](https://galoy.io/bitcoin-beach-wallet) is powered by Galoy.

For our second call we will present a proposed change to our mobile app design to incorporate multiple wallets.  We have been working hard on a new feature for our tech stack to introduce the ability for users to store value in USD.  We enable this on the backend by hedging the sats against USD on an exchange.  This call will focus on our proposed design to include USD wallets into our mobile app which currently only has a single satoshi value wallet.

### Check your timezone

https://everytimezone.com/s/c509d38f

### Join the call

https://meet.jit.si/moderated/92c5f09ddcbebb15eb99eb5f6ec33714f0745eea1acd1ecd82e273dae18370f5

### Calendar invite

https://calendar.google.com/event?action=TEMPLATE&tmeid=MjFtN2c2ZjJtZTJ0bmlxcmd0amhtYmg3MjBfMjAyMjAyMjNUMTgwMDAwWiBjX2kzZGpydW9vOTVqb3ZpdXV0NjZoYW1lZmhzQGc&tmsrc=c_i3djruoo95joviuut66hamefhs%40group.calendar.google.com&scp=ALL

**Comment by secondl1ght** [comment]
Was hoping to make the call tomorrow but something came up, will have to jump on the next one!

**Comment by GBKS** [comment]
Call recordings are now available on [BitcoinTV](https://bitcointv.com/w/qsd5DqNiaXTLbnMwzZa7uB) and [YouTube](https://youtu.be/2BatSDiNGNw).
