### ISSUE TITLE
Learning Bitcoin and Design: SPV, Neutrino, & Electrum and payment request formats

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#253]
```meta
Date: 2022-03-08
Time: 7:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-03-08 19:00 UTC
```

![learning-bitcoin-and-design](https://user-images.githubusercontent.com/2414177/156608033-33ee575b-76ef-429b-b983-f6077b7a083a.jpg)

### Agenda

This call is intended to help you learn new concepts about Bitcoin, Lightning, and design. The general format will be to focus on a specific topic or read-through a document together and discuss (like a chapter of the Design Guide, or something that will help us learn about Bitcoin and Lightning).

This week's topic is TBD.

### Check your timezone

https://everytimezone.com/s/c8b30da1

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by ghanbak** [comment]
I've been digging into Lightning and multisig wallets. 
I'm curious about how to design for opening and closing lightning channels and how to design for shared wallets using multisig. 🙂

**Comment by sbddesign** [comment]
This call, we touched briefly on the comment from @ghanbak, discussed different forms of SPV like Neutrino and Electrum, and looked the use cases for different types of payment request formats. See the recordings here:

- [BitcoinTV](https://bitcointv.com/w/xAKj3tvekh84P3SoyKqBjy)
- [YouTube](https://youtu.be/IiBLmVCaKro)

**Comment by dhwanipatel15** [comment]
Hi, is it possible to access the recording of this event?

**Comment by GBKS** [comment]
@dhwanipatel15 recordings are linked in the message above yours, [see here](https://github.com/BitcoinDesign/Meta/issues/253#issuecomment-1067881979).

**Comment by dhwanipatel15** [comment]
> @dhwanipatel15 recordings are linked in the message above yours, [see here](https://github.com/BitcoinDesign/Meta/issues/253#issuecomment-1067881979).

Thank you!
