### ISSUE TITLE
Wallet Design Improvement Project: Blixt Design Sprint Call #3

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Meta#258]
```meta
Date: 2022-03-16
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-03-16 17:00 UTC
```

![wallet-design-improvement-project-blixt-design-sprint-call-3](https://user-images.githubusercontent.com/695901/158988748-3710c80f-b17d-4200-9a70-5a8d267a844e.jpg)

### Agenda

In this call we'll do an overview of various prototypes and try to come up with a final prototype(s).

### Check your timezone

https://everytimezone.com/s/0016774b

### Join the call

https://meet.jit.si/bitcoindesign

**Comment by johnsBeharry** [comment]
We can structure this as a design review with hampus + some voting on "the best parts" which we can these use to bring the best solutions into a single prototype.

**Comment by pavlenex** [comment]
Makes perfect sense @johnsBeharry , I love that idea.

**Comment by GBKS** [comment]
Good session. Recordings are now live on [YouTube](https://www.youtube.com/watch?v=Z5XFKR3q_xU) and [BitcoinTV](https://bitcointv.com/w/9UD2EXt6ofNrfGxuEzH9VW).
