### ISSUE TITLE
New Member Mixer Call #2

### ISSUE THREAD

**Issue by dulcedu** [BitcoinDesign/Meta#270]
```meta
Date: 2022-03-23
Time: 16:30pm
Timezone: UTC
Duration: 30 min
UTCTime: 2022-03-23 16:30 UTC
```

![mixerscolors](https://user-images.githubusercontent.com/11275066/158880795-6060d555-fbad-4add-a8ea-2ad973432a6b.jpg)

### Goal
Let’s celebrate the new members that joined recently and the newest version of the [Bitcoin Design Guide](https://bitcoin.design/guide/) by chatting about **lightning**! The intention is to have a casual chance to meet, learn, and maybe even experiment on design concepts together.

### Agenda

1. Welcome and short introductions
3. Present the Bitcoin Design Guide V2
5. What do we already know about lightning?
6. What changes as designers get more involved in layer 2 solutions?
7. Q&A
8. After this call we invite you to join the community call on Twitter spaces 
https://twitter.com/i/spaces/1BdGYwPMDMyxX 

### Check your timezone

https://everytimezone.com/s/02fa9fe5

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [bitcoin design calendar](https://bitcoin.design/calendar/).

### Credits

Photo in the cover background via [Miguel Padriñán](https://pixabay.com/users/padrinan-1694659)

**Comment by GBKS** [comment]
Really enjoyed this one. Was super interesting to hear from everyone, what brought them in, what their interests are, etc. We did not record it, FYI.
