### ISSUE TITLE
Add `bolt.fun` to projects page

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#272]
Not currently listed on this section of the website, would this be considered a community project or collaboration? 

@johnsBeharry

**Comment by GBKS** [comment]
I think we can add it, but maybe up to Johns. Could also add [https://bitcoinqr.dev](https://bitcoinqr.dev) while we're at it.

**Comment by johnsBeharry** [comment]
it would be an honour 🙏 !
