### ISSUE TITLE
Create a `social-media-guidelines.md` file

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#274]
Several discussions have occurred recently, notable in the [#spread-the-word](https://bitcoindesign.slack.com/archives/C01PRLDBCBA) Slack channel and this [Google doc](https://docs.google.com/document/d/1APoP7rLVd2IcBqhuVcwIscWxVVgRxCtvE5q32NalBpI/edit), around how best how best to manage / post / share content on social media such as the community's [Twitter account ](https://twitter.com/bitcoin_design).

We should create a social media guidelines doc to live is in this repo that outlines how best to do this. 

Post your ideas suggestions below.

**Comment by sbddesign** [comment]
My quick take:

- It's OK to highlight when products, services, and brands:
  - adopt strategies from the Guide
  - do things that’s good for open source bitcoin or open design processes
- It's OK to highlight what people in the Community are working on.
  - This shouldn't come across as "we are telling you to do this", this should be "here's what some of our peeps are doing, what do you think?"
- Keep direct criticism to personal accounts
- Keep direct promotion to personal accounts

This isn't the greatest social media writing the world has ever see, but here are some basic examples.

## Good

- ABC Wallet just launched a new version with an improved UI. It's a perfect example of techniques from the Onboarding section of the Guide!
- Just wrapped up another awesome design sprint with XYZ Wallet. Thanks for being so open to collaboration with the Bitcoin Design Community!
- Several members of the Design Community participated in this podcast about DEF Wallet to talk about this Lightning backups. What do you think about this topic?
- MNO Exchange just launched an initiative to provide grant funding to people working on open source bitcoin projects. Calling all designers!

## Bad

- GHI Wallet has a pretty bad UI. Shame they haven't read the Guide.
- Gee, JKL Wallet, would it kill you to join a Design Review call?
- PQR Wallet is the best. You should all download it now!
- STU Wallet has a promotion going on where you can get free sats for downloading their app.

**Comment by GBKS** [comment]
This was addressed in #288.
