### ISSUE TITLE
Learning Bitcoin and Design: Open Design

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#275]
```meta
Date: 2022-04-19
Time: 4:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-04-19 16:00 UTC
```

![learning-bitcoin-and-design_2022-04-19](https://user-images.githubusercontent.com/2414177/160943057-2d982267-1669-4cf6-83fd-60be93a93fdd.jpg)

### Agenda

This call is intended to help you learn new concepts about Bitcoin, Lightning, and design. The general format will be to focus on a specific topic or read-through a document together and discuss (like a chapter of the Design Guide, or something that will help us learn about Bitcoin and Lightning).

This week, we will look at the concept of "open design" and how to get involved in open source communities. We can use the [Open Design](https://bitcoin.design/guide/designing-products/open-design/) page from the Bitcoin Design Guide as a centerpiece for the discussion. If you have time, read it before attending the call.

### Check your timezone

https://everytimezone.com/s/115ba3ca

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by GBKS** [comment]
Recordings are up on [BitcoinTV](https://bitcointv.com/w/1pSR3iza4mmvMNQ5kYmA36) & [YouTube](https://www.youtube.com/watch?v=1FYruvp4Cbo).

This was a wide-ranging discussion around open design, from the big idea to practical tips.

00:02:00 - everyones perspectives on open design
00:06:00 - open collaboration
00:10:00 - designer protectionism
00:21:00 - design contribution guidelines
00:25:00 - hackathons for designers
00:31:45 - practical contribution questions
00:45:50 - UX research when and how
00:49:20 - current projects in the community
00:54:10 - the broader mission of improving bitcoin UX

There was a lot of interest in continuing this conversation, either on Slack (via the #open-design channel) or another call.
