### ISSUE TITLE
Bitcoin Design StratumV2 Call #1 - Designing visuals, branding & website 

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Meta#277]
```meta
Date: 2022-04-12
Time: 3:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-04-12 15:00 UTC
```

<img width="1280" alt="161747463-67101632-34ff-4b3f-9f32-9e88f25b082e" src="https://user-images.githubusercontent.com/36959754/161757453-7ffb264c-aeaa-4ed2-bfad-d9e9c36e7e2f.png">

### Agenda

The goal of StratumV2 collaboraiton is to help the project come up with branding visuals and a website design. 

On this call we'll try to understand Stratum V2 protocol on a high-level so that we can come up with clean design suggestions for logo, social media visuals, and in the end website. We will only be designing but if there's a front-end dev here, we can then for sure come up with a website itself.

To learn more about stratum v2, it's [recommended to watch this video ](https://www.youtube.com/watch?v=xrdhtQPHg2o) and optionally read this [document](https://docsend.com/view/szk48syby33q28zq).

### Check your timezone

https://everytimezone.com/s/8745460e

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by enyipreshious** [comment]
<img width="1280" alt="Bitcoin StratumV2 Call#1" src="https://user-images.githubusercontent.com/57605607/161747463-67101632-34ff-4b3f-9f32-9e88f25b082e.png">

@pavlenex does this call event cover work? Happy to make any changes or corrections there might be.

**Comment by pavlenex** [comment]
Great work @enyipreshious I've added it, thanks, looks dope.

Also a note that a call has been re-scheduled for next week.

**Comment by GBKS** [comment]
Recordings are up on [BitcoinTV](https://bitcointv.com/w/7r9CmtELAuTifGvJPx1Abg) and [YouTube](https://youtu.be/4wr5k0IOV1M). Call notes are [here](https://docs.google.com/document/d/1rEYGTJvC7EB05oLtCnKb5rdIVhrsijgtWNAts68-3Zo/edit?usp=sharing).
