### ISSUE TITLE
Galoy Project Call #3

### ISSUE THREAD

**Issue by daviroo** [BitcoinDesign/Meta#289]
```meta
Date: 2022-04-20
Time: 5:00pm
Timezone: UTC
Duration: 30 mins
UTCTime: 2022-04-20 17:00 UTC
```

![image](https://user-images.githubusercontent.com/3502409/154054819-edf9f95e-810d-4bef-bd0c-e4788e61e655.png)

### Agenda

Galoy has been working on a new merchant portal and we would like to show the design to the community.  Since the design is quite small I've reduced the length of the call to 30 mins.

### Check your timezone

https://everytimezone.com/s/a055688e

### Join the call

https://meet.jit.si/moderated/92c5f09ddcbebb15eb99eb5f6ec33714f0745eea1acd1ecd82e273dae18370f5

### Calendar invite

https://calendar.google.com/event?action=TEMPLATE&tmeid=MjFtN2c2ZjJtZTJ0bmlxcmd0amhtYmg3MjBfMjAyMjAyMjNUMTgwMDAwWiBjX2kzZGpydW9vOTVqb3ZpdXV0NjZoYW1lZmhzQGc&tmsrc=c_i3djruoo95joviuut66hamefhs%40group.calendar.google.com&scp=ALL

**Comment by GBKS** [comment]
Recordings are now up on [BitcoinTV](https://bitcointv.com/w/xvCRJziBFkNRCc37Xe4pAd) and [YouTube](https://www.youtube.com/watch?v=IOuxTomnkg8).
