### ISSUE TITLE
Galoy Project Call #4: Bitcoin Jungle's "Mercado" Design Walk-through

### ISSUE THREAD

**Issue by agbegin** [BitcoinDesign/Meta#299]
```meta
Date: 2022-05-04
Time: 18:00 
Timezone: UTC
Duration: 1h
UTCTime: 2022-05-04 18:00 UTC
```
![mercado-project-call](https://user-images.githubusercontent.com/90297599/166064576-19792341-9c9e-4c84-8c58-ca27437e023b.jpg)

### Agenda
Prem from [Bitcoin Jungle](https://bitcoinjungle.app/) will be walking through a new feature called "Mercado." See note from Prem below: 
"Hello everyone, we wanted to share something we have been working on. Project Mercado (Marketplace) that will hopefully replace the current Maps functionality in the Galoy mobile wallet.

https://www.figma.com/file/SdcllXJyXvvpTl3R8fKQcA/Bitcoinjungle-App?node-id=0%3A1 

Would love to hear thoughts from others here as there will be a lot of important architectural decisions to be made here."

### Check Your Timezone
https://everytimezone.com/s/f93d5575

### Join the call
https://meet.jit.si/moderated/6a17835b6bb3e5326d62772294570f431aa2b6ccca3cc69d77a4911144d0e5d6

### Calendar invite
[View the invite and add to your calendar invite](https://calendar.google.com/event?action=TEMPLATE&tmeid=MWRpZTQxMzNiMGdsb2RvZTl2bDRhaWppYW4gYW5kcmV3QGdhbG95Lmlv&tmsrc=andrew%40galoy.io)

**Comment by GBKS** [comment]
Great conversation as always. The recordings are now up on [BitcoinTV](https://bitcointv.com/w/8hXadw6yRxzmKUdUKBY8hn) and [YouTube](https://youtu.be/cTHA6zClzbI).
