### ISSUE TITLE
Proposal for a COSCUP 2022 presentation

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#303]
The [Conference for Open Source Coders, Users and Promoters](https://coscup.org/2022/en/landing) (COSCUP) is an annual conference held by Taiwanese Open Source community. There were 2800 attendees last year, dates are July 30 to 31. They have a track about Open Design and this years focus is "Cultivating the next generation of Open Source Contributors". They reached out and asked if we are interested in presenting. Considering this is about open design collaboration, I think it would be ideal for the proposal and presentation also to be prepared together and in public.

From the invite:
> We want to invite proposals that focus on having more designer involvement in open source projects and think about how to make OS contributions more rewarding and attractive for designers and work on improving the design of open source projects. We are interested in your experience in the open design field and you are among many contributors to the Bitcoin Design Guide, which aims to help both designers and developers create better Bitcoin experiences faster. Your idea inspires people to consider helping designers from every conceivable angle. In Open Design Track, we invite you to share more of your experience about how the Bitcoin Design Community works in the open design field and what problems Bitcoin solves. Bitcoin Design raises increasingly the importance of the open design field in open source projects by empowering non-technical people to contribute. This deeply resonates with our Open Design Track theme. Hence, We believe your presence would be a critical addition to the COSCUP design track this year.

Some facts:
- The format is a pre-recorded with live QA, just like the FOSDEM presentations
- Talk duration is 30 minutes (not sure if this includes the live QA)
- Due date for proposals is May 23
- This is not a paid talk

Some links:
- [Call for proposals](https://blog.coscup.org/2022/04/coscup-x-kcd-taiwan-2022-cfp-is-now.html)
- [Some info](https://gcn.com/2020/09/hacking-the-pandemic-how-taiwans-digital-democracy-holds-covid-19-at-bay/314994/) regarding Civic Tech in Taiwan
- [Photos from previous conferences](https://www.flickr.com/photos/coscup/albums)

Our first step should probably be to gather ideas for topics we want to discuss. Then we can turn that into a proposal and if we get accepted we can focus on the presentation itself.

Previous presentation proposal issues for [FOSDEM 2022](https://github.com/BitcoinDesign/Meta/issues/210) ([recording](https://www.youtube.com/watch?v=MyaflySHp9U)), [FOSDEM 2021](https://github.com/BitcoinDesign/Meta/issues/58) ([recording](https://www.youtube.com/watch?v=LI-lpMgNSig)), and [Figma Config 2021](https://github.com/BitcoinDesign/Meta/issues/71) ([recording](https://www.youtube.com/watch?v=30E65z9v9S0)).

**Comment by GBKS** [comment]
The proposal is due Monday. I prepped copy for the submission, see the Google Doc shared in Slack (don't want to share here since the link has public edit access). I'll keep revising this, and then submit on Monday afternoon.

**Comment by GBKS** [comment]
I just submitted a presentation proposal.

**Title**
Supporting open design in bitcoin

**Abstract**
“Design bitcoin for everyone”. That is the slogan of the [Bitcoin Design Community](https://bitcoin.design/), which formed in the middle of 2020. It is an open community with the goal of making bitcoin more intuitive and accessible. Our central community project is the [Bitcoin Design Guide](https://bitcoin.design/guide), which is full of best practices and references to help both designers and developers create better bitcoin experiences faster. We also work to promote the idea of [open design](https://bitcoin.design/guide/getting-started/open-design/), to bring more designers and other contributors into the space, help open-source projects adopt better design processes, and create more inclusive outcomes. This presentation will provide an overview of community efforts, practical stories of what has worked and what hasn’t, where we are, and what the future might hold.

@johnsBeharry has graciously offered up to tag-team on the presentation again, and Felix (on Slack) offered to help with the presentation slides. I'll share another update here and on Slack once I hear back on whether we got accepted or not.

**Comment by DanGould** [comment]
One of the organizers came to @TaiwanBitdevs looking for bitcoin presenters. I'll be going in person and am available to help


He shared an interest in stable derivatives using DLCs too

**Comment by GBKS** [comment]
Alright, the schedule is live and we're on for a panel on [Open Design](https://coscup.org/2022/en/session/CWP3DG) and a presentation on [Supporting open design in bitcoin](https://coscup.org/2022/en/session/LGMK9R).

Both are 30-minute sessions. They asked us to do pre-recordings to avoid potential streaming issues. I'll ask and clarify whether we'll still have Q&A sessions afterwards, which would then define how long the actual panel/presentation will be (e.g. 20 minute panel/presentation then 10 minutes Q&A).

**Comment by GBKS** [comment]
Our panel and presentation are tomorrow, Saturday July 30, starting at 5:00 UTC. Getting exciting.

**Comment by GBKS** [comment]
Alright, [COSCUP](https://coscup.org/2022/en/) is a wrap. We had some good questions in the Q&A sessions, and I hope the info we presented was interesting and useful. Big thanks to Julia and Paula for organizing and making this possible. And thanks to Bosch, Conor, Ed, and Stephen for participating in the panel.

Recordings are also uploaded:
- Open design panel discussion on [BitcoinTV](https://bitcointv.com/w/uJ1DSV72ysyHyMzW68SvbY) and [YouTube](https://youtu.be/EBEsQcL6oj4)
- Supporting open design in bitcoin presentation on [BitcoinTV](https://bitcointv.com/w/sEUb5QewMfdYvfdJ47wGCR) and [YouTube](https://youtu.be/p93gGB5dUBI). Slides are up on [Figma Community](https://www.figma.com/community/file/1135942724353140890).

@DanGould how was the conference for you?
