### ISSUE TITLE
Learning Bitcoin and Design: Accessibility testing

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#307]
```meta
Date: 2022-05-31
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-05-31 17:00 UTC
```

![learning-bitcoin-and-design](https://user-images.githubusercontent.com/2414177/170127455-8f51ba8a-17c4-4768-8ed2-8be6c466472f.jpg)

### Agenda

This call is intended to help you learn new concepts about Bitcoin, Lightning, and design. The general format will be to focus on a specific topic or read-through a document together and discuss (like a chapter of the Design Guide, or something that will help us learn about Bitcoin and Lightning).

### Check your timezone

https://everytimezone.com/s/f17cdf0d

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by sbddesign** [comment]
Links from the call:
- A11y page Pull Request - https://github.com/BitcoinDesign/Guide/pull/821
- A11y page deploy preview - https://deploy-preview-821--sad-borg-390916.netlify.app/guide/designing-products/accessibility/
- Apply VoiceOver phone gestures - https://support.apple.com/guide/iphone/learn-voiceover-gestures-iph3e2e2281/ios
- How to Check a Readability Score with Microsoft Word - https://www.troy.edu/_assets/graduate-school/_documents/irb/readability-score.pdf
- Christoph and Mogashni's a11y goole doc - https://docs.google.com/document/d/1zIuLvUPgGfKVIo_WBBteGhzTEUyn9fbbvtUUpEa7QSw/edit?usp=sharing
- Christoph's figma file - https://www.figma.com/file/vWxA4SRJq7RdXWiKrB032y/Bitcoin-app-accessibility-tests?node-id=52%3A1797

**Comment by GBKS** [comment]
Recordings are up on [YouTube](https://youtu.be/dQc2YWxOB6A) and [BitcoinTV](https://bitcointv.com/w/b6Y4hnWzrTaLHjp6TjT2pT). Copying the description here for reference.

In this workshop-style call, we each set up our smartphones for mobile accessibility testing, tested a few different bitcoin apps and discussed our findings. 

00:00:00 Intro
00:05:00 Setting up an iPhone for testing
00:12:50 Example of screen readers labels
00:15:00 Testing and discussion
00:28:15 Test options on Android
00:31:30 Discussion of testing for cognitive disabilities
00:37:00 What switch controls are
00:40:25 Discussion of testing for hearing
00:42:27 Filing issues/PRs for our findings
00:44:08 QR codes, addresses and accessibility
