### ISSUE TITLE
Galoy Project Call – Merchant interaction design & enabling every display currency – June 14 2022 at 8PM UTC / 4PM Eastern

### ISSUE THREAD

**Issue by agbegin** [BitcoinDesign/Meta#319]
```meta
Date: 2022-06-14
Time: 8:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-06-14 20:00 UTC
```

![2302](https://user-images.githubusercontent.com/90297599/173137408-16fc2db1-216c-4a4d-a551-36a4484306ce.jpg)

### Agenda

1. Mili will share some merchant POS UX she's been working on 
2. FaBu will share the Bitcoin Lake POS he has built that enables setting payment amount in any currency: pagar.bitcoinlake.io
3. Galoy team will share thoughts on how multi-currency functionality can be built into Galoy platform

### Check your timezone

https://everytimezone.com/s/cf239696

### Join the call

https://us02web.zoom.us/j/7238135719?pwd=endva0dIVzhsUTRFMElLL1p2aHpCQT09

### Calendar invite

https://calendar.google.com/event?action=TEMPLATE&tmeid=MTliOXRpOTlqYmc4aWE3NWxuNDdxdDM1NnIgYW5kcmV3QGdhbG95Lmlv&tmsrc=andrew%40galoy.io

**Comment by sbddesign** [comment]
Here are recordings of the call and links we discussed during the call:

- [YouTube recording](https://youtu.be/S21hOiIcgwg)
- [BitcoinTV recording](https://bitcointv.com/w/25tKpqtNqCq2K8RuTVtD6T)
- [Mili's Figma file](https://www.figma.com/file/gyMRxQVykiMrkNOQGlsvlD/Merchants-Cash-Register?node-id=135%3A4926)
- [FaBu's Lago Bitcoin POS](https://pagar.bitcoinlake.io/fabu)
- [Arvin's thoughts on multiple display currencies](https://github.com/GaloyMoney/galoy/discussions/1280#discussioncomment-2941523)
- [Stephen's Bitcoin Lake notes](https://www.figma.com/file/j6rpzRzxEEYKGXEV5SBwI8/Lago-Bitcoin-Issues?node-id=0%3A1)
