### ISSUE TITLE
Conduct a Bitcoin Design Guide survey

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#320]
Now that the Bitcoin Design community is almost 3 years old and we have the Bitcoin Design Guide in pretty good shape (for mobile lightning wallets anyways) I was thinking it would be worthwhile to conduct a survey with the community to uncover a few things:

- What could we do better with the guides current content?
- Have you applied or found the guides content useful, is so what and how? 
- Have you found anything in the guide you dislike? 
- Have you contributed to the guide? If so, why? Was the barrier to entry too high? What could we do better?
- What new content would you like to see in the guide?
- Other ideas, nothing is too crazy! 

I recommending doing this anonymously and collecting no personal information (or have that optionally opt-in only) to stick with our ethos.

I was thinking we keep focused on the guide for this initial survey but also would see some value in doing a community survey later on which discusses the more meta points of Bitcoin Design, thoughts?

**Comment by moneyball** [comment]
Two years old😁

**Comment by mouxdesign** [comment]
@Bosch-0 Love this initiative! And it follows 100% about putting the users first which is what good UX design is all about. 
We can only know what users really want by getting closer to them and by speaking with them.

If I were to take this one step further I think actually speaking to projects that used the design guide in their product development process would be also super practical, allowing them to feely express themselves and collect some qualitative data. 

Do you guys know of any projects/companies/Foss projects that have directly mentioned that they are using/use the bitcoin design guide? I'll name some that I know of here:

1. Alby
2. Cashapp
3. 


Idea...could the survey be perhaps focused on **quantitative data**, some examples of quantitative questions are:

1. How many times per week do you use the bitcoin design guide?

2. How many projects have you built where you directly used the bitcoin deign guide for advice/guidance?

I would like to add on some more questions and would be more than happy to analyze the data we collect together with you and anyone else. 

**Qualitative questions:** (we could ask by interviewing)
This open conversation will  also allow the people talking to say and express things abut the guide that we may not have thought about ourselves.....

1. What could we do better with the guides current content?

2. Have you applied or found the guides content useful, is so what and how?

3. Have you found anything in the guide you dislike?

4. Have you contributed to the guide? If so, why? Was the barrier to entry too high? What could we do better?

5. What new content would you like to see in the guide?

6. Other ideas, nothing is too crazy!

We can create a simple Googledoc with a list of these qualitative and quantitative questions.

**Comment by mouxdesign** [comment]
# Goal
The bitcoin design guide was established 2 years ago with the goal of helping builders build more intuitive accessible products. We would like to understand if we are achieving this goal as well as what we can do make the guide more valuable.

> We would like to create more user driven content and value. To do this we must get closer to users as we continue to develop the guide.

We would like to understand:
* If there is adoption of the bitcoin design guide 
* How we can increase adoption
* How can we increase implementation of the design guide
* Pain paints of users
* How the bitcoin design guide can improve its user experience<br/>

A combination of both qualitative as well as quantitative research techniques can be used to collect an in depth overview. Below is a rough collection of both types of questions which can be used to collect data to drive future decisions.<br/>
## Qualitative:

* What could we do better with the guides current content?

* Have you applied or found the guides content useful, if so what and how?

* Have you found anything in the guide you dislike?

* What could we do better?

* What new content would you like to see in the guide?

* What type of content would be helpful for you in helping you to understand your users? (UX research)

* Do you have any specific questions right now that you would like the design guide to answer?

* Other ideas, nothing is too crazy!<br/>


## Quantitative:

How often do you use the bitcoin design guide?
* Weekly
* Daily
* Monthly

Have you contributed to the guide?
* Yes
* No
* If so, why? 

Do you know how to contribute to the bitcoin design guide?
* Yes
* No

How many projects have you built where you directly used the bitcoin design guide for advice/guidance?

How regularly do you have questions during your product development process that you seek answers to?
* Weekly
* Monthly
* Daily

**Comment by GBKS** [comment]
Great idea. As Mo suggested, I would couple this with direct conversations with project contributors. A survey can cast a broad net, but is standardized by necessity. In a 1-1 conversation, you can directly discuss the specific needs of the designer and project and have a bit of a back and forth.

It would be helpful to know a few facts about the respondent to better understand their answers, like what type of product they are working on, how experienced they are, etc. We could also ask how they go about solving design problems when they cannot find information in the guide.

**Comment by mouxdesign** [comment]
Some very good points from Christoph. I've updated the [google doc](https://docs.google.com/document/d/1MYviGIhcn39Iw3o9AwEHx-Y7s2rogodUtWvNt7nbKB8/edit?usp=sharing) to include;
* Person interviewed: 

* Project name:

* Project role:

* Length of time they have been working in this role: 

Added in qualitative question; 
How do you solve design problems when you are unable to find the information in the guide?

Some additional questions to ask ourselves: 
1. Would we like to record the interviews if the people interviewed are comfortable with that, an audio recording could work as well.
2. The interviews can also be done with 2 people, one asking questions and the other taking notes, this then negating the need for it to be recorded. 

We can then: 
* Create a list of projects that we know have used the bitcoin design guide.

* Ask in Slack for projects that have sued the design guide that we might not be aware of.

**Comment by Bosch-0** [comment]
> Do you guys know of any projects/companies/Foss projects that have directly mentioned that they are using/use the bitcoin design guide? I'll name some that I know of here:

This is what I was hoping to unearth with the Survey initially. We can craft the survey in a way that starts with simple yes / no questions that then drives what questions follows. One being have you used the guide to build something. If no, it would go down a more general community path. If yes, it would go down a path focused more on the guides content. 

> could the survey be perhaps focused on quantitative data

If we frame the questions right I think we can get both quant and qual data from responses. Once we find out projects who have used the guide we should follow up with 1 on 1's for more in-depth answers. 

Cam across this survey tool that claims to be private, secure, and anonymous - maybe a good candidate to checkout for what tool to use for this: https://blocksurvey.io/. They seem to like bitcoin also!

**Comment by Bosch-0** [comment]
Created a Figjam file we can visually layout the survey on. Find these easier to plan things. Started with what we have now, feel free to add / change / comment.

https://www.figma.com/file/yVjOTCOli1GRWgmK0hqeF2/Untitled?node-id=0%3A1

**Comment by mouxdesign** [comment]
@Bosch-0 Has Created the survey here using Google survey and I have created a Readme file version of the survey upon the suggestion from Christoph for survey takers who might not want to use Google Survey.

[Survey](https://docs.google.com/forms/d/e/1FAIpQLScbrOrHJfSOZIbBXQxx3m211eR6vu2whzaY5VltoSTPQ9Y_GQ/viewform?usp=sf_link)

https://github.com/UXResearchBitcoin/BitcoinDesignGuideSurvey

**To do:**
Still to add in some images and send out the initial survey to the core team for some feedback, almost there!

**Comment by mouxdesign** [comment]
Quick update. @Bosch-0 have started doing interviews. We have done 3 so far and Bosch is currently reaching out to people and setting up more calls.

- We are keeping the interviews to 30mins.
- We are focusing on very basic questions and then digging deeper depending on the answers provided.
1. What are you working on at the moment? 
2. How do you use the design guide? 
Any issues (considered contributing if so?)
4. What type of content could we add to the guide to give you more value?


[Google doc](https://docs.google.com/document/d/1BTLCNmjfoTU6enEMxSt4-KC8oU7Gy-vElwQWP-t_ujs/edit?usp=sharing)
[List](https://docs.google.com/spreadsheets/d/1deQTtleBdLVT7HVqyYGfuFzbDWMj8baEkYwTadyorEg/edit?usp=sharing)

**Comment by mouxdesign** [comment]
Started to go through the interview videos and take [notes.](https://docs.google.com/document/d/1Bgwut2_cZTjCGQk2OeogomPmWJbGzJ8VnhlMRi2TWOg/edit?usp=sharing) 

Will eventually summarize these in the form of a report.

**Comment by mouxdesign** [comment]
Have gone through all of the interviews and updated the [notes.](https://docs.google.com/document/d/1Bgwut2_cZTjCGQk2OeogomPmWJbGzJ8VnhlMRi2TWOg/edit?usp=sharing) Will not look for some insights in the interviews and create that in the form of a report.

**Comment by mouxdesign** [comment]
![BDG Research Summary](https://user-images.githubusercontent.com/90313394/206401472-3315119b-bc53-4d67-9d96-344b6bac7949.jpg)


It's a wrap! Took all the content of the research and summarized it into 3 different ways. 

- [Video](https://biteable.com/watch/3780040/99d93a591451cf188875a0146a48f3b6)
- [PDF](https://drive.google.com/file/d/1zyH1k9l2WQ64oMiw1jbb7VM09yPzK-j0/view?usp=sharing)
- [Googledoc ](https://docs.google.com/document/d/1i6_RMW4SAWO61nmdVVzHY7mna6oDCllr6EP-iJyreZo/edit#heading=h.taavtgribm8p)
- [Interview Transcripts](https://docs.google.com/document/d/1Bgwut2_cZTjCGQk2OeogomPmWJbGzJ8VnhlMRi2TWOg/edit)

The Google doc contains all the extensive direct quotes from people we interviewed. While the PDF is a slightly more extended version and the Video the most succinct.

**Comment by sbddesign** [comment]
@mouxdesign, I have reviewed. Looks great. I have some typos I found and some typographical nitpicks. But content-wise, I think it's ready to distribute broadly.

- The video has 4 typos (I ignored text that was in the user's voice). I left comments on the video so you have it timestamped.
- PDF File
  - Page 5 - it's weird that "Educating new Designers" is the only bubble heading that is not title-cased
  - Page 7 - some of the bubble headings are title-cased and others are not
  - Page 9 - none of the bubble headings are title-cased, which is fine, but inconsistent with page 7 and 5. Maybe just no title-casing on any of the bubble pages?
  - Page 10 " Bullet lists" is the only heading no title-cased, but the other pages with the layout style have title-cased headings. Maybe make a global rule for the whole document, either title-casing or sentence-casing all through-out?

**Comment by sbddesign** [comment]
@mouxdesign When I look at the video link, I still see a bunch of typos. I left comments on them just in-case.
  
PDF looks great! My only nitpicky comment is that on page 10, "Naming conventions" and "Bullet lists" should be title-cased to match the title-casing on the other "Quotes" pages.

**Comment by sbddesign** [comment]
@mouxdesign Reviewed the video link you sent me out of band, LGTM.

**Comment by mouxdesign** [comment]
Thanks @sbddesign 

Adding in the updated links

- [Video](https://biteable.com/watch/3818719/655b74939024508a3aec283c53ad5888)

- [PDF Report](https://drive.google.com/file/d/1LvT7X6gq2r2zr0hy4cc3BM72TyRbyZzP/view?usp=sharing)

- [Summary of Quotes](https://docs.google.com/document/d/1i6_RMW4SAWO61nmdVVzHY7mna6oDCllr6EP-iJyreZo/edit#heading=h.taavtgribm8p)

- [Interview Transcripts](https://docs.google.com/document/d/1Bgwut2_cZTjCGQk2OeogomPmWJbGzJ8VnhlMRi2TWOg/edit?usp=sharing)

**Comment by GBKS** [comment]
Should we close this issue? If so, do we want to link to this survey from anywhere so it doesn't complete disappear into the void? There is a paragraph about "[Identifying what to fix](https://bitcoin.design/guide/contribute/propose-a-change/#identifying-what-to-fix)" in the contribute section of the guide where this could be referenced? It could also be a nice reference for the research kit.

**Comment by mouxdesign** [comment]
Agree with closing this issue. 
Also good to link it to the section Identifying what to fix. Some text could be:
The community has done some research on the Bitcoin Design guide, here's what we discovered. Or something along those lines.

**Comment by GBKS** [comment]
I created a [pull request](https://github.com/BitcoinDesign/Guide/pull/1017) to add that link. Please take a look and then we can close this issue.

**Comment by GBKS** [comment]
Alright, that PR is merged so I'm going to close this issue now. We could do another one of these surveys at some point. Anecdotally, I heard from lots of people at BTC Prague that they are familiar with the guide and they like/love it.
