### ISSUE TITLE
Bitcoin Crits #1 - VoltPay

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#321]
```meta
Date: 2022-06-30
Time: 1:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-06-30 13:00 UTC
```

![image](https://user-images.githubusercontent.com/55287964/174542291-4ebcffe7-d81a-4d11-85a1-867c46b103fa.png)

### Agenda

1. VoltPay Keypad crit

### Check your timezone

https://everytimezone.com/s/bdeefea2

### Join the call

https://meet.jit.si/BitcoinCrit

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by Bosch-0** [comment]
In this call I will be criting the number pad section of the [VoltPay](https://voltpay.app/) bitcoin POS app.

**Comment by GBKS** [comment]
Here are the links to the [recording](https://youtu.be/wqDvSX0xaJQ) and [Figma](https://www.figma.com/file/qldKmu6JlG2OW6aku4uYxZ/Bitcoin-Crit%3A-VoltPay?node-id=0%3A1).
