### ISSUE TITLE
🎯 Bitcoin Design Crits

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#322]
## What are Bitcoin Design Crits?

Bitcoin Design Crits are opportunities for bitcoin products to get design critiques (crits) on a particular page in their product. Actionable suggestions for improving usability, user interface, interaction, and visual aesthetics are given by members in the Bitcoin Design Community.

## How does it work?

1. A bitcoin product submits their page they want reviewed on Bitcoin Design Crits in the [#design-review](https://bitcoindesign.slack.com/archives/C015DQEPCHJ) Slack channel.

We only focus on a particular page so we can give the highest amount of value. Reviewing a whole product is an extensive and involved process that is better suited to be dealt with by a dedicated Product Designer. If you need a Product Designer for your bitcoin product, reach out in the [#opportunities](https://bitcoindesign.slack.com/archives/C016D659EU9) channel in our Slack.

2. A product is selected for the next upcoming Bitcoin Design Crit call by members of the community. If demand is high, we may have to include your product in a backlog.

3. Product designers interested in reviewing jump into a collaborative Figma file where they crit the product page submitted **PRIOR** to the Bitcoin Design Crit call. This will all be public and open for anyone to view in class open-source fashion.

4. Product designers who crit the product present their feedback to the product team in the scheduled Bitcoin Design Crit call.

5. Follow up help and suggestions on the feedback given is always available.

## Who can take part?

Anyone who is working on a bitcoin product. Whether its a new page you want reviewed before release, or an old page that needs polishing, Bitcoin Design Crits can help. Open-source products get priority over closed-source products.

Calls are recorded and open for anyone to join in and view the crit take place.

We greatly appreciate the pseudonymous and private nature of bitcoin and are more than happy to accommodate those who would prefer not to reveal their identity.

## When do these happen?

Once a week on Thursdays 2:00PM UTC time. Bitcoin Design Crits happen in our public Jitsi channel [here](https://meet.jit.si/BitcoinCrit). Calls are recorded and open for anyone to join in and view the crit take place. If you do not wish for the call to be recorded we can accommodate.

You can view past and upcoming Bitcoin Design Crits [here](https://github.com/BitcoinDesign/Meta/issues?q=is%3Aissue+in%3Atitle+%22Bitcoin+Crits+%23%22+).

## Past calls

#1 [VoltPay](https://github.com/BitcoinDesign/Meta/issues/321)
#2 [Oshi](https://github.com/BitcoinDesign/Meta/issues/336)
#3 [bolt.fun](https://github.com/BitcoinDesign/Meta/issues/346)
#4 [RoboSats](https://github.com/BitcoinDesign/Meta/issues/349)
#5 [Creating a wallet on Blockstream Green](https://github.com/BitcoinDesign/Meta/issues/361)
#6 [Machankura](https://github.com/BitcoinDesign/Meta/issues/367)

**Comment by GBKS** [comment]
Going to close this issue, since we are back to the design review format these days, outlined [here](https://github.com/BitcoinDesign/Meta/blob/master/Design-Reviews.md). If you have a good reason to keep this open, please share, and we can re-open.
