### ISSUE TITLE
Guide Merchants Content Kick-off

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#323]
```meta
Date: 2022-07-06
Time: 13:00
Timezone: UTC
Duration: 1h
UTCTime: 2022-07-06 13:00 UTC
```

![guide-merchants](https://user-images.githubusercontent.com/2414177/175050810-40297eb1-72cb-4ada-813a-680ebaa1567b.jpg)

### Agenda

We'll kick-off the merchants section content for the Bitcoin Design Guide (#292)! So far, we have a table of contents brainstorming document (linked in [this Slack post](https://bitcoindesign.slack.com/archives/C03C2CHHENA/p1651240607567329)) as well as a lot of UI design work from teams like Galoy and Lago Bitcoin.

On this call, we'll talk about defining the scope of the merchants section and how we should approach creating a reference design for a merchant POS terminal.

### Check your timezone

https://everytimezone.com/s/c7084eab

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by Bosch-0** [comment]
Excited for this! The Bitcoin Crit I am doing tomorrow night is on a bitcoin POS mobile app, come check it out as their will be a lot of relevant discussions for the merchant section. 

https://voltpay.app/ is the app I am criting, only focusing on the number pad screen though!

**Comment by sbddesign** [comment]
What we discussed on this call.

- [Collaborative group brainstorm document](https://docs.google.com/document/d/1FxODCEc85HJSBjGprBYjZHDdDb4t8sy_ouf98ngswPE/edit?usp=sharing)
- [Stephen's Table of Contents](https://docs.google.com/document/d/1FY2yMtAu4prxlWT280K8Sd_zkvrm1UkypVTnt5jFzLA/edit?usp=sharing)
- [Stephen's FigJam](https://www.figma.com/file/kRWeEEFCWBAiCli4R0rxTA/Merchants---Bitcoin-Design-Guide?node-id=0%3A1)
- Andrew: need content that gives an overview of merchant experience (e.g. business size, in-person vs. online, POS environment, etc.)
- Christoph: make smaller designs that solve specific problems, figure out how to organize or categorize it all later
- Case Study: one past idea is for Bitcoin Design Guide to have a "Case Studies" section that are overviews of real products and how they solved specific problems
  - The first case study could be an analysis of Galoy's lightning cash register that is in-progress
- Galoy can contribute their findings working on the lightning cash register to a case study, then learnings from that could inform other content in the Guide like a reference design
- Patricia: need content that is a resource for merchants struggling with their bitcoin setup. People don't always know where to go for help.
  - Christoph: consider having community around that, like how PlebNet is a community organized around helping each other with lightning problems
  - Stephen: consider turning this into a micro-site or community, source people from Bitcoin Design Community who want to help with this
- Immediate next steps:
  - Tracker issue to collect design work people do related to merchants
  - Issue for a "How it Works" installment involving fiat over bitcoin
  - Issue for "Multi-currency Display" page

Call Videos
- [YouTube](https://youtu.be/h53qw-y0HKk)
- [BitcoinTV](https://bitcointv.com/w/mLPfD1xssKng3JUQEb12Ss)

**Comment by ps5link007-hash** [comment]
look for down that marchant anywhere is not btc how to know the pipeline block for  txid marchant and how get log list for make facture and txid marchant btc only

**Comment by ps5link007-hash** [comment]
how buy real money any step you need start in yen 🃏🀄buy 💱 et acheter toute device comme acheter solana au complet solana = $ canadien ... how acheter toute l’argent des bank convertir a btc only for get the power litgh is the meme fisrt buffo. i try fix app so hackeur marathon canada continue to try ghost me

**Comment by ps5link007-hash** [comment]
https://github.com/user-attachments/assets/e08cfb3d-6213-4d00-b364-833608503b0a

https://github.com/user-attachments/assets/4e88ce07-6179-40b2-8a8a-7d7e1d07962b

https://github.com/user-attachments/assets/1a324efb-3851-4bf0-864d-93cc7bfafa68

https://github.com/user-attachments/assets/ddaaab5e-d689-415b-b777-33f720de9888

![alex_ai_master_flow_260826_180515.pdf](https://github.com/user-attachments/files/31695126/alex_ai_master_flow_260826_180515.pdf)

![Xpub statement 1_1 2026-07-19 - 2026-08-18 (2).pdf](https://github.com/user-attachments/files/31695125/Xpub.statement.1_1.2026-07-19.-.2026-08-18.2.pdf)

![macaron_1788154701094.jpg](https://github.com/user-attachments/assets/6fcf472d-8b2e-4f5f-8661-faea56840510)

![da3mon_stego_carrier_0xF82 (4).png](https://github.com/user-attachments/assets/59502a3e-a99c-44c2-a821-cfb16174c34e)

![Screenshot_20260831_025630_Chrome.jpg](https://github.com/user-attachments/assets/09db6c44-b8bb-41ba-a755-b34cd349bf6d)

![Screenshot_20260831_025714_Chrome.jpg](https://github.com/user-attachments/assets/50c5a5b8-9705-4fad-a80e-b4479cbbfc7f)

![Screenshot_20260831_030033_Chrome.jpg](https://github.com/user-attachments/assets/0fb96e48-79b4-4898-ac70-16f24be7b957)

![Screenshot_20260831_030031_Chrome.jpg](https://github.com/user-attachments/assets/e1bdbde6-a0aa-453d-8b1a-d6b4233cb844)

![Screenshot_20260831_054626_BlueWallet.jpg](https://github.com/user-attachments/assets/322f9a18-a94e-4818-bfa9-d1c36c7a62c6)

![Screenshot_20260831_044618_Samsung Browser.jpg](https://github.com/user-attachments/assets/9c7be361-6dd5-4f3b-b118-d84ba0437e1e)

![Screenshot_20260831_030211_GitHub.jpg](https://github.com/user-attachments/assets/8a227ee7-8660-41b3-9351-79f2b63c10cd)

![Screenshot_20260831_054618_BlueWallet.jpg](https://github.com/user-attachments/assets/8387bffd-38d5-40db-a3f9-e31f3cada638)

![Screenshot_20260831_054641_BlueWallet.jpg](https://github.com/user-attachments/assets/0b80d024-5a32-4b0d-a250-b86b8c086b08)

![Screenshot_20260831_054647_BlueWallet.jpg](https://github.com/user-attachments/assets/fd846752-0625-4e0f-823d-e67875f4cf6a)

![Screenshot_20260831_141846_Chrome.jpg](https://github.com/user-attachments/assets/50903f45-97d4-4ee9-a527-3cf2c18bf6cc)

![Screenshot_20260831_141850_Chrome.jpg](https://github.com/user-attachments/assets/91254a01-ca92-4544-a82a-4de1d4fd2858)

![Screenshot_20260831_141852_Chrome.jpg](https://github.com/user-attachments/assets/c8e0893b-f7ce-455e-8951-4df4ed8e400c)

![Screenshot_20260831_141909_Chrome.jpg](https://github.com/user-attachments/assets/8d8e4b96-d3b2-403a-9789-01b613dd32de)

![Screenshot_20260831_141918_Chrome.jpg](https://github.com/user-attachments/assets/4083e9e1-f52e-4bad-8c09-9c36d9e97f99)

![Screenshot_20260831_141914_Chrome.jpg](https://github.com/user-attachments/assets/b38a7789-deeb-47f2-9ed5-1d25121e1f78)

![Screenshot_20260831_141925_Chrome.jpg](https://github.com/user-attachments/assets/aa567def-d4b8-4670-9707-2d5260a08545)

![Screenshot_20260831_141921_Chrome.jpg](https://github.com/user-attachments/assets/eb3132be-39b5-47cd-98b3-3a50d001a99c)

![Screenshot_20260831_141932_Chrome.jpg](https://github.com/user-attachments/assets/b4df8736-90f0-4e90-afc2-27c51c4db281)

![Screenshot_20260831_141928_Chrome.jpg](https://github.com/user-attachments/assets/ce818309-ea57-4b6e-b7e9-2e4c52650792)

![Screenshot_20260831_141936_Chrome.jpg](https://github.com/user-attachments/assets/2b9a701d-0e85-49dd-af0f-471c16ed5717)

![Screenshot_20260831_142143_Chrome.jpg](https://github.com/user-attachments/assets/45778626-48f3-4af6-8564-14c7e3fdff50)

![Screenshot_20260831_141941_Chrome.jpg](https://github.com/user-attachments/assets/9940b1df-e872-433e-bb2d-c9f4396e0765)

![Screenshot_20260831_142134_Chrome.jpg](https://github.com/user-attachments/assets/d40b24e0-fdf1-42de-97b5-7ba2dd362a18)

![Screenshot_20260831_141947_Chrome.jpg](https://github.com/user-attachments/assets/28bcdc01-ccb3-431e-a4b7-c1c566e5b35a)

![Screenshot_20260831_142138_Chrome.jpg](https://github.com/user-attachments/assets/9c887018-fd37-4dfc-9261-a5341e0ebfff)

![Screenshot_20260831_142149_Chrome.jpg](https://github.com/user-attachments/assets/695f1af7-ecc0-4c0f-8791-50d2f64837df)

![Screenshot_20260831_174204_BlueWallet.jpg](https://github.com/user-attachments/assets/6594dbd9-b4b0-4cb0-a3c3-1b8a6f5ccaca)

![Screenshot_20260831_142146_Chrome.jpg](https://github.com/user-attachments/assets/9603da80-435e-4db3-b664-fe252666405a)

![Screenshot_20260831_142153_Chrome.jpg](https://github.com/user-attachments/assets/76a59656-d210-43d4-abc0-9c166b4b31fc)

![Screenshot_20260831_142945_Google Play services.jpg](https://github.com/user-attachments/assets/21047ac8-b54c-43e1-9fc8-f24620637331)

![Screenshot_20260831_142157_Chrome.jpg](https://github.com/user-attachments/assets/da3a7989-7f37-458b-9d5e-2f7dbc254888)

![Screenshot_20260831_054633_BlueWallet.jpg](https://github.com/user-attachments/assets/e624f5c7-3229-4d84-922c-9620b5a53875)

![Screenshot_20260831_141842_Chrome.jpg](https://github.com/user-attachments/assets/e3978875-3bcf-4e69-b8bd-9ed6d8883d1e)
 how use mywalletdoor.com  meme.mywalletdoor.com plume.mywalletdoor.com ♒️🔑💴💸💵🧾💳 informatiser l’argent token les devevis. comme token des arbre ou autre chose que la vie on besoin comme un assurance token de vie
