### ISSUE TITLE
UX Research Call #1: User personas

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#324]
```meta
Date: 2022-06-29
Time: 9:30pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-06-29  21:30 UTC
```

### Agenda

The goal of this call is to explore and understand how user persona's are used during the product development process. 
* Are they useful?
* How are they used?
* What can we used instead?

### Format of the call
2-3 people will be invited to speak and share in a practical way how they are currently using persona's to ensure that thier product dev process is in close alignment with the users needs. We will also open the floor to hearing from others who have different processes which achieve the same goal 
> Understanding the users needs, goals wants and desires. 

Jalissa from [Amber](https://amber.app/) will speak on how they use persona's.
Jonathan will share other methods that he has used as a senior UX designer. 

### Check your timezone

[[Time Zone converter](https://everytimezone.com/?t=62bce780,-96)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Recordings are now up on [BitcoinTV](https://bitcointv.com/w/tkAGb56c7qE7g1fMbaASBW) and [YouTube](https://youtu.be/6c-t4IDy8dg).
