### ISSUE TITLE
🎯 Bitcoin Design Crits #2 - Oshi

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#336]
```meta
Date: 2022-07-07
Time: 2:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-07-07 14:00 UTC
```

![image](https://user-images.githubusercontent.com/55287964/174542291-4ebcffe7-d81a-4d11-85a1-867c46b103fa.png)

### Agenda

1. We will be reviewing the landing view / home tab of the [Oshi app ](https://www.oshi.tech/)

### Check your timezone

https://everytimezone.com/s/6abf2d06

### Join the call

https://meet.jit.si/BitcoinDesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by Bosch-0** [comment]
Call recording: https://youtu.be/Ft_BUr-mJbQ

**Comment by sahilc0** [comment]
@Bosch-0 I wonder if it would make sense to link the Figma used here as well?

**Comment by Bosch-0** [comment]
Good idea: https://www.figma.com/file/vDK5haW90ApBFBnk0S1Eze/Bitcoin-Design-Crit%3A-Oshi?node-id=0%3A1
