### ISSUE TITLE
UX Research Call #2: User Stories

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#343]
```meta
Date: 2022-07-15
Time: 15:00
Timezone: UTC
Duration: 1h
UTCTime: 2022-07-15 15:00 UTC
```
![bitcoin-design-UX Research call](https://user-images.githubusercontent.com/90313394/178247031-a02b58fe-6f4a-44b8-b9b4-5d8907cebe86.jpg)

### Agenda

This call will be focused on User Stories. What are the various scenarios in which a user will be using our product? <br/><br/> A scenario can be very short and specific and tend to be contextual. Once we have all these realistic scenarios in which a person will be using our product we can then ensure that the interface allows the user to meet this goal in the most efficient/easiest way as possible. 

We will hear from:
1. Andrew from [Galoy](https://galoy.io/) at how he used user stories.
2. Diana from who developed user stories for[ Alby](https://getalby.com/).

<br/> Its going to be fun, interactive and we will all collaborate on Figjam together.

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/e28d0465)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Recordings are now up on [BitcoinTV](https://bitcointv.com/w/7vkqWgGV8x89TdW2PqBnMN) and [YouTube](https://youtu.be/HFhpH30A6xA).
