### ISSUE TITLE
Wallet Improvement  Project call: Blixt 

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#345]
```meta
Date: 2022-07-15
Time: 14:00
Timezone: UTC
Duration: 1h
UTCTime: 2022-07-15 14:00 UTC
```
![wallet-improvement-project-blixt-first-use-211022](https://user-images.githubusercontent.com/90313394/178252607-8f28a794-6804-4f90-bb3f-d17d1a9209f8.jpg)

### Agenda

The redesign of Blixt wallet is part of the wallet improvement project. So far we have done UX research and designed useflows based on this.

During this call we will:
* Discuss creating a prototype for Blixt.
* Discuss 1 or 2 user scenarios for which this prototype will be created for.
* Discuss how we can collaboratively conduct some usability tests on Blixt users.

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/f1d32bd5)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Recordings are now up on [BitcoinTV](https://bitcointv.com/w/i9X9brnLyYF1JufG28YdDB) and [YouTube](https://youtu.be/9IvELt1WzdM).
