### ISSUE TITLE
Community Chat Platform

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#348]
This issue is meant to collect discussion and ideas around the preferred community chat platform.

## Problem

Currently, the Community uses Slack. A frequent problem is losing our chat history on the Slack free plan and concerns over the Slack price for a paid plan.

While moving to another platform may help preserve chat history, one concern has been migrating as many folks over to the new platform as possible and not splitting the community.

## Proposed solutions

- Discord
- Mattermost
- Matrix protocol

**Comment by Bosch-0** [comment]
Just noting that I made a replica of the Slack in Discord already for those who want to get a feel for it: https://discord.gg/2Q2aq5Qt

**Comment by tilltonystark** [comment]
> Just noting that I made a replica of the Slack in Discord already for those who want to get a feel for it: https://discord.gg/apMmBqqtq7

Yeah! the server looks cool.
And on discord we can easily collaborate via voice and video channels as well. So, it can be a better solution. 
![image](https://user-images.githubusercontent.com/89836460/184009407-0707b491-ead6-4d79-b77c-77910f41aad7.png)

**Comment by Bosch-0** [comment]
Migrating 3k+ people is the issue </3

**Comment by GBKS** [comment]
After lots of discussion, the decision was to slowly migrate to Discord. This has been announced in the newsletter and there's a [PR](https://github.com/BitcoinDesign/Guide/pull/996) for updating links in the website accordingly.

**Comment by danielnordh** [comment]
Website updated with new Discord details
PR [#996](https://github.com/BitcoinDesign/Guide/pull/996)
