### ISSUE TITLE
UX Research: Add content about competitive analysis 

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#356]
Part of the UX research toolkit will include a competitive analysis. I thought it might be an idea to add in a write up of:
- Why competitive analysis is important in UX Research
- What we can learn from it
- How to conduct it

Then to link this to the Figma file itself of the UX research Toolkit. 

Created an initial [write up](https://docs.google.com/document/d/1LYfU2C0SgAkyk5cU04T9R17Yj3rRfEayAzhdWdrZv94/edit?usp=sharing), still very much in its early stages

**Comment by GBKS** [comment]
What do you want to achieve with this issue? Is it for feedback? Reads a bit like a personal note for yourself...?

**Comment by mouxdesign** [comment]
At the moment within the UX research toolkit the following tools have been created:

- Competitor analysis
- Usability analysis
- Usability testing
- User stories

It might be interesting to add content with regards to these UX Research processes within the design guide. At this early stage that might be in the form of:
1) Educational content- How to conduct a competitive analysis (why its beneficial, what results/insights you can gain from it)
2) Case study - a walk through how a competitive analysis was done and then show the steps and thought process

Since so far the users that we have been interviewing for the bitcoin design guide have mentioned wanting to see or learn from more case studies. It might be interesting to think how the learning is taken on best, whether that is seeing it in the form of a case study or in an educational write up. 

Do you think it is beneficial to have a call within the community to identify what sort of way they would like to see UX research incorporated into the guide?

**Comment by Bosch-0** [comment]
> It might be interesting to add content with regards to these UX Research processes within the design guide.

If this pertaisn to guide content this issue should be moved to the guide repo: https://github.com/BitcoinDesign/Guide

**Comment by mouxdesign** [comment]
Closed and opened [here ](https://github.com/BitcoinDesign/Guide/issues/888)
