### ISSUE TITLE
UX Research call #3

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#363]
```meta
Date: 2022-12-08
Time: 15:30
Timezone: UTC
Duration: 1h
UTCTime: 2022-08-12 15:30 UTC
```

![bitcoin-design-community-call-28](https://user-images.githubusercontent.com/90313394/183676228-71950368-a5ac-44b6-8df1-caa21d2796c5.jpg)

### Agenda

This will be a very practical call where we will be talking with the Galoy team who are planning on doing some usability testing. 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/69f277dc)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/UXResearchBitcoinDesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by tilltonystark** [comment]
Hey there! 
I'm Satyam, a jr. ui/ux designer and willing to contribute in this project. But I don't have much idea about the agenda of the call. So, just asking can I join this call.

**Comment by mouxdesign** [comment]
Hi @tilltonystark You are most welcome to join the call. The call is open to everyone. 

[Galoy](https://galoy.io/) is looking at doing some usability testing on their wallet and so this first call will be to discuss their goals and any ideas thay have around conducting those usability tests so that they can understand their users. So the agenda is pretty open at this point, however that will be the focus.

**Comment by Satyam-Gopal** [comment]
Thanks @mouxdesign for the clarification I'll be joining the future calls

**Comment by GBKS** [comment]
Recordings are up on [BitcoinTV](https://bitcointv.com/w/6rB2P51PC2J7d6rMUWZHgX) and [YouTube](https://youtu.be/qbRuBC6l68E).

**Comment by mouxdesign** [comment]
Thank you @GBKS
