### ISSUE TITLE
UX Research call #4

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#364]
```meta
Date: 2022-09-02
Time: 14:00
Timezone: UTC
Duration: 1h
UTCTime: 2022-09-02 14:00 UTC
```

![Group 2246 (1)](https://user-images.githubusercontent.com/90313394/184364240-7ff92a2b-a435-42c8-b4fa-5f88e23f408f.png)

### Agenda

This call will be to discuss adding user persona's to the bitcoin design guide. 

Diana from [GetAlby](https://getalby.com/) has been working on developing some personas for the Alby team. 
We will discuss how Diana created those as well as how we can create a format of these persona's that will be useful to other builders within the design guide. 

Link to [issue](https://github.com/BitcoinDesign/Guide/issues/557) on Github

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/823a037a)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/UXResearchBitcoinDesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by Bosch-0** [comment]
Didn't show up on my calendar, try changing time to 13:00

**Comment by GBKS** [comment]
Shows up correctly in my calendar.

**Comment by mouxdesign** [comment]
@GBKS Happy to hear it shows up on your calender. @Bosch-0 wonder what it might be then..it is showing up in my calender as well. Maybe re-add the bitcoin design guide calender and see if that works?

**Comment by GBKS** [comment]
Recordings are up on [BitcoinTV](https://bitcointv.com/w/uBubGV6wAJsiSTNV8RZjM5) and [YouTube](https://youtu.be/PSHJzIsEzKA).
