### ISSUE TITLE
Fedimint Design Call #1

### ISSUE THREAD

**Issue by humansinstitute** [BitcoinDesign/Meta#365]
```meta
Date: 2022-08-29
Time: 1:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-08-29 13:00 UTC
```

Please join for a community call to kick off work on contributions to the fedimint.org website. 

For review: https://fedimint.org & https://humansinstitute.github.io/wiki_fedimint/docs/intro

### Agenda

1. Intros
2. Review of Wiki Site
3. Review of Mood boards
4. Questions and Answers
5. Plan
6. All ideas welcome! 

### Check your timezone

https://everytimezone.com/s/2ccf2339

### Join the call

https://meet.jit.si/bitcoindesign-fedimint

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Recordings are up now on [BitcoinTV](https://bitcointv.com/w/cMQmuSTfP3AGPJ5pXGWCGd) and [YouTube](https://youtu.be/lIyodMBWv6c).
