### ISSUE TITLE
TABConf Builder Day Table

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#366]
![TAB_NG_building-builders_16x9](https://user-images.githubusercontent.com/2414177/185757678-7b549ad7-915d-4a41-968f-6a34baf93846.png)

I would like to host a Bitcoin Design table at TABConf Builder Day.

## What is TABConf?

Bitcoin dev-focused conference in Atlanta. See [this year's website.](https://2022.tabconf.com/)

## What is Builder Day?

Builder Day is the first day of the event. Participating projects claim a table and run their own programming: this can be stuff like hacking on an issue, teaching potential new contributors how to navigate their FOSS project, doing tutorials, or simple being available to answer questions. [Read more about it here](https://2022.tabconf.com/builder-day/).

## What should a Bitcoin Design table be?

I'm opening this issue so we can come up with ideas about what sort of programming we should run at our table. Let's discuss in the comments!

**Comment by sbddesign** [comment]
List of random ideas:

- Design-thinking workshop
- Bitcoin UI Kit crash-course
- "Hack" (design) on a project idea from the[ Bitcoin Design Exploration Weeks](https://docs.google.com/document/d/1a9O6Rkvx5aaLhOfqWJKpR1LNUrtQUfQuepRhIZslj8o/edit?usp=sharing) document
- Work on open issues in the Guide repo
- Just be there to chat with people, hand out stickers, and network with other FOSS projects and potential contributors

**Comment by GBKS** [comment]
This could also include design feedback sessions (or crits). People can bring their projects and get feedback.

To your third point, having a tie-in with our design event would be cool. We could try to get a few people to pick projects and organize/lead sessions that others can easily join in.

**Comment by sbddesign** [comment]
We ended up focusing on the Bitcoin Designathon. We did a design thinking session for coming up with project ideas and got more people into the Slack channel. More details about our day [in this slack message](https://bitcoindesign.slack.com/archives/C0402AVBLPQ/p1665601342083969).

**Comment by GBKS** [comment]
Super cool how you single-handedly made this happen. Mad props 🙇🏻
