### ISSUE TITLE
Add Stratum V2 to collaborations

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#371]
Not currently on the [collaborations](https://bitcoin.design/projects/#collaborations) page on the website

**Comment by sbddesign** [comment]
Seems like a good add. Stratum V2 channel has a lot of activity on the Slack.

**Comment by GBKS** [comment]
Should we still do this?

**Comment by sbddesign** [comment]
Yeah, I think so. Asked Pavlenex what he thinks.

**Comment by GBKS** [comment]
@pavlenex what's going on these days with Stratum V2? Good to add it here?

**Comment by pavlenex** [comment]
Sure! Website is done, and so is collab for now, feel free to add it 🙌
