### ISSUE TITLE
Bitcoin Designathon 2022

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#395]
The community decided to organize a designathon in October 2022 (about one month from creating this post), based on this [document](https://docs.google.com/document/d/1a9O6Rkvx5aaLhOfqWJKpR1LNUrtQUfQuepRhIZslj8o/edit?usp=sharing). This issue is intended as a central starting point for tracking the planning process, with the specific planning happening in other issues (or Google Docs, etc).

General buckets of things we need to organize:

**Ideas**
Crowd-sourced list of ideas to investigate and work-on. Not comprehensive, just suggestions. We need to figure out the process for submitting ideas (is a Slack comment enough?), and how elaborate this should be (a 5-minute video with some visuals might spark more enthusiasm).

**Teams**
Participants can work independently or form teams as they please. Keeping track of teams helps everyone understand more easily what is happening. Should this be called projects? How can we support participants in forming and finding teams? Do we want to provide some guidelines or tips (communication, tools, process, etc)?

**Schedule**
It's important for everyone to be aware of what is happening when so we have a smooth event. Most important dates can be sorted out right away, and it's likely that the schedule will change even during the event (let's say a team wants to put a research call on the schedule). Should be listed on the website. 

**Calls & workshops**
Calls we could organize:
- Kick-off and wrap-up calls (I assume we will have those)
- Mid-event update
- Workshops (research, design sprint, Figma & UI Kit into, technical topics...) 
- Jam sessions
We can reach out to the community and ask if anyone would like to host workshops and feedback sessions.

**Prizes**
In the community call, the group preferred things as prizes over money, as a token of appreciation. We can try to organize sponsors and identify prizes (and figure out things like shipping).

**Website & forms**
Ideally we have one website that works as a central go-to point before, during, and after the event. Also a form for registering teams.

**Coordinators**
It might be best to have 2-3 go-to people who actively help coordinate everything during the event. If someone has a question, they would go to those people. They would also keep up with the activity and update the website, connect people, etc.

**Cross-event coordination**
The bolt.fun tournament, TABConf and Bitcoin Amsterdam are starting the same day as the designathon. bolt.fun is a 2-month hackathon primarily focused on lightning. For example, there might be participants of that event that may want to start their project with a design sprint during our designathon. Stephen is hosting a design table at TABConf, which we can connect to the designathon. We can come up with ideas on how to connect the events and then organize.

**Social media**
We should ensure to publicly talk about the event, invite people to participate, and share updates as it happens.

---

Anything missing from the list above? Each category deserves its own time to discuss and plan. It might be best to create a separate issue for each one for more focused discussion.

 If there's something you'd like to be involved with or have thoughts you'd like to share, please leave a reply.

**Comment by cogentgene** [comment]
1. Ideas - can we use Twitter and newsletter to crowdsource ideas? Tweet responses and email replies could be submissions. Slack comments work too. Maybe we could also add a form that automatically sends the idea to the Slack channel? Some sort of integration perhaps .. google form, sortable, whatever. This way everyone can see the ideas incoming as they are submitted.

Side thought: Perhaps we should tap into developers to see if they know of anything that needs to be designed? Make it practical.

2. Maybe let people do their organizing when it comes to forming teams (or just going solo), but also create a space (maybe existing channel) to let people come in there and look for partners? 

3. Teams - Yes, projects is probably a better name since there may be solo designers. How would we keep track of what is happening on them? Thought: If we required people to join our community, they are more likely to stay on (helps everyone in the long run) and we can create a new channel for each project? 

4. Are schedules basically deadlines? This is how I am thinking about it at least. Have clear deadlines?

5. Calls - I won't be able to make any, but if others find them useful, sounds like a good idea! Probably depends on how many people decide to participate 🤔

6. Swag? That sure sounds nice!

7. Coordinators - how about posting to slack? One of us will likely be around at any time of the day. As for updating a website, what about just having an airtable embedded that shows the status of signups, status of projects etc... ? Then anyone in the slack can go in and edit it if we give them permissions. 

The only thing I can think of is the idea generation part. I have a feeling we may need to come up with some ideas for people as it may be difficult to know what to work on. I mean, if they do come up with something - great! But having some existing options is nice too.

**Comment by GBKS** [comment]
1. Totally, in the weeks ramping up to the event, we should put out a call for ideas and for participants. Plus, we should take a few and write proper briefs and maybe put short intro videos together to make it easier to start.
2. Just what I was thinking. Some people are self-motivated and will make teams/projects happen, others will be on the lookout for spots to join
3. Spoke to Johns about this yesterday. He suggested we could use the bolt.fun directory for registering projects. We would have a page like [this one](https://makers.bolt.fun/projects/category/11) that would list all projects, and each project has its own page to list project info, teams, links, etc.
4. Personally, I see the only deadline as the end of the event, and everything else being up to teams. For a schedule, we need something to indicate when it starts/ends, workshops, etc. If we don't have extra events, we won't need a general event schedule. We could offer a sample timeline for teams. For example, if someone is interested in doing a design sprint, we could provide an outline of how this be done during the course of the event. 
5. -
6. -
7. Ideally, people self-organize and we won't need much coordination once everything has kicked off. Pretty sure that will not be the reality though and there will be various questions. I was also thinking about using Airtable as a back-end for the website to make it super easy to update. I'll have to look into that.

Lots of stuff to sort through.

**Comment by Bosch-0** [comment]
**Ideas**

- We should use a form for idea submissions imo, could get hard to manage if lots of people just submit ideas on Slack. We can have this separate from registration form so we can have a pool of ideas we could give to teams if they are stuck on finding one. We should also create some of our own ideas for teams to use if they wish.

**Teams**

- Ask in the form above if they have a team, and if not, we can match-make people (unless they want to do it solo)
- As its a competition should we have team size limits? 
- Projects is better name for same reason as Gene

**Schedule**

- Again, with the form we can collect emails (opt-in) and keep people updated this way and on the website.

**Calls & workshops**

- Kick-off, mid-term, and ending calls would be good
- Judges could setup a Calendly and have slots available for drop-in chats if they need help / feedback outside of scheduled calls. I'd prefer this over jam sessions as it can be more async which caters better to more time-zones. 

- 4 workshops would be handy, could have one for each design phase (something like the double-diamond approach below, one workshop on each phase could be an idea). Could do first two between kick-off and mid event call and other two between mid-even and ending call.

![image](https://user-images.githubusercontent.com/55287964/190081467-ddc2a658-fc28-4289-a6d9-eab3ce55ab73.png)

**Prizes**

- Agree, could get some sponsorships on and get discounted hardware wallets or something?

**Coordinators**

- Like many things my time-zone isn't that suited for this role but will step in whenever I can.

**Cross-event coordination**

- Could this not be a problem starting at same time? Could limit peoples time / availability. Should be fine if we manage it all nicely just bringing that point up.
- Using bolt.fun is a good idea, good way to cross-pollinate with their hackathon. 

**Social media**

- Yep we should get a doc up to coordinate all the marketing efforts / time them.

**Comment by GBKS** [comment]
The website is now live at [event.bitcoin.design](https://event.bitcoin.design). A V2 update with basic info is almost complete. Additional updates have already been designed and will be rolled out as the event nears and progresses.

**Comment by GBKS** [comment]
And it's a wrap. We published a summary article today that talks about everything that went down. It includes a list of projects, links to presentations, and much more. [Check it out](https://bitcoindesign.medium.com/the-bitcoin-designathon-2022-e4a2428db613). Also, here's [the Figma file](https://www.figma.com/file/5LWQnQMoV9eyHWB0t7ewie/Bitcoin-Designathon?node-id=87%3A1097) for the website and assets.

I am planning to keep the website around (statically, without the Airtable integration). The site was continuously updated, almost 10 times I think, to reflect the state of the event. After we announced the prizes, all the language was changed to past tense, projects and winners move to the top, etc. That way we don't have an event page floating around that makes people think it's still upcoming.

**Comment by GBKS** [comment]
Going to close this issue now, as I think the event is organizationally also pretty much wrapped up. Just opened a [PR](https://github.com/BitcoinDesign/Guide/pull/935) to remove the banner from the home page, and add a link from the projects page for future reference/access.
