### ISSUE TITLE
Navigating the Bitcoin Design Community

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Meta#4]
```meta
Status: Draft
```

# Bitcoin Design Community

Anything related to group consensus and coordination of the Bitcoin Design Community.

### Getting Started
1. Pick existing [project](https://docs.google.com/document/d/1P20rPq6V6w78dXpBqLiiiB-kSypZOzXaG9ZUErYIq28/edit) in the space and do something small
2. If you are passionate. Just do it. Worst case you publish it on your own
3. Contribute to parts of the design guide and website even if it is a slower process to get things approved

### Projects

- Project list — [Doc](https://docs.google.com/document/d/1P20rPq6V6w78dXpBqLiiiB-kSypZOzXaG9ZUErYIq28/edit)

### Governance / Opensource Design

- Slack Channel — [#open-design](https://bitcoindesign.slack.com/archives/C015GFYSJNA)
- Discussions -- [Issues](https://github.com/BitcoinDesign/Meta/issues)

### Research

- Slack Channel — [#research](https://bitcoindesign.slack.com/archives/C015DQEPCHJ)
- User Surveys — [WIP Doc](https://docs.google.com/document/d/1Sjh9yZJOHfbrqmjpdiekDz361A9kWEsDrB0CggIoxU0/edit#)

### Guide

- Project Intro — [Doc v2.0.0](https://docs.google.com/document/d/1YiYeRIybGmxmErCOI4Jc8Qajz3JGM1JYVfUtpzyCzSk/edit?usp=sharing)
- Slack Channel — [#bitcoin-design-guide](https://bitcoindesign.slack.com/archives/C015856BDME)
- Github Repository — [guide](https://github.com/BitcoinDesign/Guide)
- Github Project Board — [guide/content](https://github.com/BitcoinDesign/Guide/projects/1)

**Comment by moneyball** [comment]
ACK

**Comment by GBKS** [comment]
Very useful information. What's the plan with this? For it to become a page on the website at some point? If so, we could already create a markdown document. It could then be read on Github even if we haven't build the site yet.

**Comment by johnsBeharry** [comment]
I haven't gotten lots of input on it since posting so what do you think about adding it as a readme on this repo?

**Comment by GBKS** [comment]
Eventually it would be great to have this as a page on the website so it's not hidden on Github. Might be best to start this as a markdown file in the repo (and then turn it into a page once we have a site up).

**Comment by GBKS** [comment]
Is this content now covered by the [Contribute](https://bitcoin.design/contribute/) page? If so, can we close the issue?
