### ISSUE TITLE
Bitcoin Core Design Call #6

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#40]
```meta
Date: 2020-11-06
Time: 9:00am
Timezone: UTC
Duration: 1h
UTCTime: 2020-11-06 9:00 UTC -7 
```

![File Cover Image](https://user-images.githubusercontent.com/55287964/97545516-1a66c200-1a06-11eb-867e-baa671f33e22.png)

### Agenda

1. [Bitcoin Core Design System](https://www.figma.com/file/0oqnohjahRtprjRyaetDOL/Website-Design-System?node-id=1831%3A14) 
    - Would be great to get some Bitcoin Core devs down to show them how this design system will be used by both designers and devs.
    - Bosch is after feedback on this on the design system.
2. [Bitcoin icon repo](https://github.com/Bosch-0/Bitcoin-Icons) - An open source icon set for Bitcoin centric applications.
    - This is not only Bitcoin Core related but want to use this icon set in the GUI once its developed. 
3. [Icon policy documentation](https://github.com/Bosch-0/Project-Muggle/blob/master/docs/icon_policy.md)
    - Bosch is after feedback on the icon policy. 
4. [Project Muggle](https://github.com/Bosch-0/Project-Muggle) update (Bosch's project).
5. Suggest your agenda items below...

### Check your timezone

https://everytimezone.com/s/80386f27

### Join the call

https://meet.jit.si/bitcoindesign (I will be joining 15 minutes earlier if anyone wants to have a general chat)

### Calendar invite

https://raw.githubusercontent.com/BitcoinDesign/Meta/calendar/events.ical

**Comment by Bosch-0** [comment]
Removed 'GUI' from the call title - any design related discussion around the Bitcoin Core project are welcome not just GUI related topics.

**Comment by promag** [comment]
Missed the call, is there a design system available to see?

**Comment by Bosch-0** [comment]
@promag yes though its still a WIP - https://www.figma.com/file/0oqnohjahRtprjRyaetDOL/Design-System?node-id=1830%3A608
