### ISSUE TITLE
UX Research Call #6: GetAlby User Feedback

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#404]
```meta
Date: 2022-10-04
Time: 2:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-10-04 14:00 UTC
```
![Group 2249 (1)](https://user-images.githubusercontent.com/90313394/191510875-49455269-25ce-42cd-b6df-4a36959e79f1.jpg)

### Agenda

This call will be with the GetAlby team. As an open source project:
- Where can we collect user data?
- How can we sort through that user data in a way that makes it useful to the development of the product?

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/e1f5c186)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/UXResearchBitcoinDesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
The recording is on [YouTube](https://www.youtube.com/watch?v=yOQs7uiyF7M).
