### ISSUE TITLE
Bitcoin Core App Call #43

### ISSUE THREAD

**Issue by jarolrod** [BitcoinDesign/Meta#405]
```meta
Date: 2022-10-05
Time: 14:00
Timezone: UTC
Duration: 1h
UTCTime: 2022-10-05 14:00 UTC
```

![bca-call-43](https://user-images.githubusercontent.com/23396902/193754804-3f63ed1f-fd0e-4c36-ac2e-fcc29a6b69c4.jpeg)

### Agenda

1. Recap of last call, because several of us were out

### Check your timezone

https://everytimezone.com/s/1c9da81f

### Join the call

https://meet.jit.si/BitcoinCoreAppDesignCall

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Love the cartoon.
