### ISSUE TITLE
Learning Bitcoin and Design: PayJoins

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#419]
```meta
Date: 2022-12-13
Time: 5:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-12-13 17:00 UTC
```

![learning-bitcoin-and-design_payjoins](https://user-images.githubusercontent.com/2414177/202260059-978ada2c-41cc-41ae-88a1-a7862933dc76.jpg)

### Agenda

This call is intended to help you learn new concepts about Bitcoin, Lightning, and design. The general format will be to focus on a specific topic or read-through a document together and discuss (like a chapter of the Design Guide, or something that will help us learn about Bitcoin and Lightning).

On this call, we'll focus on PayJoins, which is a technique for improving privacy on bitcoin. [Dan Gould](https://twitter.com/bitgould) will join us to help us discuss this topic.

### Check your timezone

https://everytimezone.com/s/f696ffe5

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the Bitcoin Design calendar. [More info here](https://github.com/BitcoinDesign/Meta#the-bitcoin-design-calendar).

**Comment by DanGould** [comment]
I got some feedback in the BOLT FUN design discord:

> Me: Any designer have ideas why payJoins might have relatively low software adoption so far?
>  617a7a: People shouldn’t even know they’re happening. Most people don’t care
> 617a7a: Any privacy benefits should be added without additional UX steps
> Me: Indeed this why I think PayJoin is a great solution. It works inside a unified QR code. Did you know that or is there some other experience you've had with PayJoin in the past that required more steps?

I have a feeling people might be misinformed that PayJoin is a synchronous protocol with lots of waiting like zerolink CoinJoins. Yes, it requires parties to be online, but that hasn't stopped lightning from taking off

**Comment by sbddesign** [comment]
We are going to reschedule this for same time next Tuesday (December 13th). Apologies for the last minute time change!

**Comment by DanGould** [comment]
In preparation here is a collection of language & experience records relating to PayJoin & P2EP

Please feel free to add more https://docs.google.com/document/d/1y5qiKEX2WXMoDgdNclKcZ2RHDIM8wX5OkhREA-Hmc0k/edit#

**Comment by DanGould** [comment]
Another idea we should touch on is the idea of pull-payjoins. The current bip 78/79 model requires a receiver to host a secure endpoint to establish sender-receiver communications. What if the sender is a service already and it's easier for them to host?
