### ISSUE TITLE
Node Management Interfaces: Collaboration

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#422]
# Node Management Interfaces

![Untitled design](https://user-images.githubusercontent.com/90313394/203266825-4825938d-e45c-4dca-89dd-062865c50466.png)

Making an issue to track details relating to the collaboration with  LNDg and Core Lightning and the community. We have a Slack channel called #lightning where discussions around this project are happening. Below are some details of the project:

 # Introduction
LNDg and Core Lightning are both Lightning Node Management Interfaces. Both projects are interested in optimizing the core experience of the user that is interested in running their own node. 

 # Project goals
Improve the User Experience of users of these interfaces by understanding:
✅ What are the components of a node which need management?
✅ How can the UI be designed so that it suits the needs of the core target group
✅ What purpose does the node serve?
✅ What are the motivations of the node manager?

Resources
[Research plan](https://docs.google.com/document/d/1DiHlDOxw9X-Rs37YcsM17mXax50Ay1vsqCZtsbMad5A/edit?usp=sharing)
[Design exploration](https://youtu.be/Pux_lXcPoso) by Christoph
[LNDg Github](https://github.com/cryptosharks131/lndg)
[Core Lightning](https://github.com/ElementsProject/lightning)

@johnsBeharry

**Comment by GBKS** [comment]
There might be a small hackday collaboration happening around new webLN/Alby features and the design explorations I did. Conversation happening [here in Twitter](https://twitter.com/Bumi/status/1603857961201328128?s=20&t=1xfDUFl0ZiYBcjppn2sOrA).

**Comment by GBKS** [comment]
This collaboration did not really take off, so let's close the issue. If you have reasons to keep it open, please share and we can re-open.

**Comment by mouxdesign** [comment]
100% agree with closing it.
