### ISSUE TITLE
Wallet Scrutiny: Call #3

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#423]
```meta
Date: 2022-11-29
Time: 3:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-11-29 15:00 UTC
```

![Group 2255](https://user-images.githubusercontent.com/90313394/203521098-864cfff3-56fa-4389-a88b-6609b7fa7f25.jpg)

### Agenda

During this call we will continue the collaboration with the Wallet Scrutiny team with the goal of redesigning their website.

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/8f1b4a8a)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Good conversation, all who joined. The recording is now up on [BitcoinTV](https://bitcointv.com/w/n2UguDtks6nSNFmDtreLNZ) and [YouTube](https://youtu.be/6OdUep9yYQ0).
