### ISSUE TITLE
🛒 Merchant Product Review > BTCPay

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#430]
```meta
Date: 2022-12-14
Time: 3:00pm
Timezone: UTC
Duration: 1h
UTCTime: 2022-12-14 15:00 UTC
```
![merchant-products-review-btcpay-server](https://user-images.githubusercontent.com/2414177/205385637-b74d0028-2119-4837-9ffa-10bcf73ba845.jpg)

### Agenda

This is part of our call series for reviewing bitcoin products and tools for merchants. This time, we'll be looking at [BTCPay Server](https://btcpayserver.org/).

### Check your timezone

https://everytimezone.com/s/225952ff

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by sbddesign** [comment]
Here's the recordings of today's call:
- [YouTube](https://youtu.be/4ktQPfkyM7c)
- [BitcoinTV](https://bitcointv.com/w/5sHoXwnJgUBdjXD96hXgBg)

And here are the [call notes](https://docs.google.com/document/d/10vVUJOm5k4KO9-PT6cCA2n5nor4lH5lKD6lxDVuAIPs/edit?usp=sharing).

**Comment by dstrukt** [comment]
Appreciate ya'll doing this - will check out the recording this evening!
