### ISSUE TITLE
Create a Nostr account for the community

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#470]
This was a request by a couple of peeps in Slack. A [#nostr](https://bitcoindesign.slack.com/archives/C04KRSC8RU5) channel was also created.

Ideally, we could set up a multi-sig so we could have multiple people control the account together. This would be more practical, so everyone with posting access could have their own key (we have this type of account management on Twitter via TweetDeck). Having a 2-of-x requirement would also help security (if there's only one private key and it gets leaked, we'd have to ditch the account). But, it's early days for Nostr, so we need to work with what we have.

A first step could be for someone to securely create a private key (very securely) and create the profile. We could then create a [NIP-05 identifier](https://github.com/nostr-protocol/nips/blob/master/05.md) (@bitcoin.design) by adding a `.well-known/nostr.json` to the guide repo.

Since Nostr is like Twitter (roughly, right now at least), I'd combine those two efforts. So when we post on Twitter, we also post on Nostr. Main thing would be to get started, get comfortable, and then see what we want to do.

How does that sound? How should we go about this? Anything against doing this?

**Comment by mouxdesign** [comment]
Sounds good to me. Have to admit I am totally new to Nostr but would love to learn more about it since it seems to be pretty much relevant for now. It was also suggested a while back by someone in the community to have a social media account with joint access so everyone/a few people could tweet. Seems like Nostr is the solution to that. Also inline with the question you asked on Slack a week or so ago if we should post to Nostr, this seems like a good start.

**Comment by sbddesign** [comment]
Sure. I'm not terribly well-versed in Nostr multisig. How about you @GBKS?

**Comment by paulosacramento** [comment]
Additionally: if the keys get compromised we can rotate to new ones and maintain the same NIP 05 identifier

**Comment by yashrajd** [comment]
https://github.com/nostr-protocol/nips/issues/99

might be a good idea to check with wallet scrutiny if/how they figured it out?

**Comment by GBKS** [comment]
I'd love to get comments on the linked [PR #980](https://github.com/BitcoinDesign/Guide/pull/980) that starts to implement this. Thanks.

**Comment by GBKS** [comment]
OK, the linked PR above was merged. You can now follow the community profile via @bitcoin.design in your favorite client (like [hamstr](https://hamstr.to/profile/npub13s5mxgws70rpxsug96jfvglggackjrxs2ehypwg0prjaxsek42sqd9l03e)).

Let's keep this issue open for a little bit for any updates we may need to make as we test things.

**Comment by GBKS** [comment]
I'd consider this one complete. The account is up and running and has 30+ followers. I've been posting updates around upcoming calls, the newsletters, etc.

**Comment by moneyball** [comment]
How do we expect people to discover this? My own journey:

1. Search twitter for bitcoin design / nostr
2. Clicked link then had to copy/paste pubkey from browser URL(!?) to enter into my nostr client (Damus)
3. 
<img width="898" alt="Screenshot 2023-03-06 at 11 23 53 AM" src="https://user-images.githubusercontent.com/326147/223210490-6d1d03bb-5376-4ffa-83f8-3345aaba220f.png">
<img width="616" alt="Screenshot 2023-03-06 at 11 24 01 AM" src="https://user-images.githubusercontent.com/326147/223210494-3687a994-434e-45e5-b41c-4f95fa958f49.png">

**Comment by GBKS** [comment]
Sorry, I should have posted a link here, there is info on how to find the profile on the [Follow page](https://bitcoin.design/social-media/). If you click the `@bitcoin.design` link on that page it will directly ask if you want to open it in your default Nostr client (if you have one installed).

As the image in the Tweet indicates, in most clients (except for Damus) you can also just search for `@bitcoin.design`, no need for a public key. Some clients expect `_@bitcoin.design`. I do hope Damus implements this soon and it becomes broadly implemented in a standardized way. 

How does that sound? Anything else we should do?
