### ISSUE TITLE
Design Review Call: Keeper

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#477]
```meta
UTCTime: 2023-02-27 16:00 UTC
Duration: 1h
```

![keeper-review-call-230227](https://user-images.githubusercontent.com/695901/217544001-e12d58e8-8274-4532-a224-aeb7fa02927d.jpg)

### Agenda

We will discuss the [Keeper](https://www.bitcoinkeeper.app) user experience with the team and provide feedback. Keeper is a multi-sig private vault with additional inheritance features.

To make the best use of the time, please download and try the app in advance and come prepared with questions and feedback. This is not mandatory, but it would be amazing if you could.

### Check your timezone

[Check your timezone](https://everytimezone.com/s/bb7cb0e1)

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by antuz123** [comment]
Here is the XD link. 

We will be looking at: 
1. Home Screen 
2. Vault creation flow 
3. Multisig signing flow 
4. Wallets screen 
5. Auto-transfer trigger flow

**Comment by GBKS** [comment]
Thank you Keeper team for sharing your work and being open to feedback, and thanks to everyone who joined the call. The recordings are now up on [BitcoinTV](https://bitcointv.com/w/wb4pRdErb3MmXT8ZcxXL72) and [YouTube](https://youtu.be/OXPVE3iPKRU).
