### ISSUE TITLE
BOLT12 UX Jam Session

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#480]
```meta
UTCTime: 2023-02-24 18:00 UTC
Duration: 1h
```

![bolt12-jam-session_2023-02-24](https://user-images.githubusercontent.com/2414177/224039336-9fc235ef-68ad-4ba7-9278-513df255e591.jpg)

### Agenda

We'll discuss work relating to the UX of BOLT12 lightning payments.

### Check your timezone

https://everytimezone.com/s/61430055

### Join the call

Check [#bolt12-async-ux](https://bitcoindesign.slack.com/archives/C04AQ49KK43) on Slack for call details day-of.

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by git-sgmoore** [comment]
I couldn't find the Slack channel #bolt12-async-ux so I wasn't able to join this call.

**Comment by sbddesign** [comment]
[Call notes here](https://docs.google.com/document/d/1s_GTHhdh9QfN3MV8oOkumJHm47Hwv_SozZL4IxhLdzY/edit?usp=sharing)

**Comment by sbddesign** [comment]
Video recording here:
- [YouTube](https://youtu.be/-fVvjQw-45g)
- [BitcoinTV](https://bitcointv.com/w/nYvwBBaqaxuyaGiHtRa4iQ)
