### ISSUE TITLE
Learning Bitcoin and Design: Nostr primer

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#484]
```meta
UTCTime: 2023-03-29 14:00 UTC
Duration: 1h
```

![learning-bitcoin-and-design_nostr-primer](https://user-images.githubusercontent.com/2414177/228303509-28778c41-e9ee-4fb6-aa68-62b2641e467b.jpg)

### Agenda

This call is intended to help you learn new concepts about Bitcoin, Lightning, and design. The general format will be to focus on a specific topic or read-through a document together and discuss (like a chapter of the Design Guide, or something that will help us learn about Bitcoin and Lightning). Other times, we may look at design tools.

This time, we'll look at Nostr. We're talk about how it works (at a super high level for beginners) and how it differs from other approaches to social media. Then, we'll go over some ways that this becomes relevant to designing experiences for bitcoin and lightning.

### Check your timezone

https://everytimezone.com/s/a086ac5c

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to all who joined. Recordings are now up on:
- [BitcoinTV](https://bitcointv.com/w/wCVtmzqYB1i3ogRE3bpcD3)
- [YouTube](https://youtu.be/EQCGFnhEdl4)
