### ISSUE TITLE
UX Research Call #18: Test Bitcoin Core App Together

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#494]
```meta
UTCTime: 2023-04-13 14:00 UTC
Duration: 1h
```

![Group 2334](https://user-images.githubusercontent.com/90313394/229116379-0a5b283b-9985-4dfa-ac30-db68ef95b43d.png)

### Agenda
This is going to be a practical call where we get hands on testing out bitcoin core app. 
It's going to be a fairly relaxed and fun experience. 

Please ensure that you're set up before the call:
1. Please download the latest version for your device [here.](https://github.com/bitcoin-core/gui-qml/tree/main/src/qml#bitcoin-core-qml-gui)

A note for Apple Silicon macOS devices
The application file must be signed before it can be run. To apply a signature, execute the following code in your Terminal (ensure you are in the same folder as the downloaded file):
codesign -s - ./Downloads/insecure_mac_arm64_gui

2. Install and click run.

During the call itself we will onboard ourselves and walk through the various screens where you'll be invited to share your feedback and so forth. 

### Check your timezone

[[LINK FOR TIMEZONE]](https://everytimezone.com/s/c726c1f3)

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by jarolrod** [comment]
ape together strong

**Comment by mouxdesign** [comment]
Links to call recordings:
[[Youtube](https://youtu.be/FR3y6AlrGdg)]
[[BitcoinTV](https://bitcointv.com/w/caxeLVuvxJp1hbHboWFBAR)]
