### ISSUE TITLE
BTC Prague conference participation

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#495]
![soc_cover 1](https://user-images.githubusercontent.com/695901/229298034-9db98322-60c7-428f-8290-7950aad340e9.jpg)

The design community is participating in [BTC Prague](https://www.btcprague.com/) this year. There will be a hack-day and a conference from June 8-10.

For hack-day, we are helping organize the design (aka "fun and creativity") track. The three other tracks are onchain, layer 2, and privacy & sovereignty (might still change). There's a small group of people currently thinking through how to create a space for bitcoiners to hang-out, discuss, collaborate, present, and have some fun activities to be part of (from design battles to soap box presentations).

For the expo at the main conference, we will have a booth (thank you to our sponsor). While the hack-day is more casual and "for the builders", this booth will be a bit more formal. We will have a 3x3m space and a few options for the basic setup, and then we need a group of people to be present at the booth, have conversations, etc.

This is a pretty great opportunity to represent the community and your work, meet people, hang-out and learn a few things. And it's the first time this community is so actively involved in shaping a real-world conference (we did have our virtual [Designathon](http://event.bitcoin.design) last year).

A lot of this is still in flux, but everything will take more shape in the next few weeks. I'll try to post updates as things happen.  If you're thinking of attending, volunteer for the booth, design materials we'll need, or help organize, please reach out. You can leave a reply here, or in the [#conferences Discord channel](https://discord.gg/XzCH8Bxc).

**Comment by HonzaMikula** [comment]
Hi @GBKS, I will be on BTC Prague, so I can help with something if you need. Let me know.

**Comment by GBKS** [comment]
Here is the final layout and design for the booth. It should be easy to pick out from a distance, create a nice atmosphere, and invite people to enter the space and gather around the table. We're planning to have a slideshow of projects running on the TV, with the option to pull up individual projects to discuss.

![BTC Prague final layout](https://user-images.githubusercontent.com/695901/232401089-8bb298fd-ea9e-47ee-bb0b-8048acf25165.jpg)

This booth is up for all 3 conference days, and we'd really like some help attending it. There should be always at least 1 person at the booth. If you'd like to help out, join the conferences channel on Discord ([here](https://discord.gg/XHGNS3HqNd)).

@HonzaMikula awesome that you'll be around. Are you also joining for the hack day on June 7? Would you be interested in helping attent the expo booth?

**Comment by HonzaMikula** [comment]
@GBKS I'm not participating on the hack day.

If it would beneficial, I would gladly help attending the expo booth.

**Comment by rabbitholiness** [comment]
I'll be there ✋

**Comment by tilltonystark** [comment]
Regrettably, I won't be able to attend the conference due to the distance, but I am willing to volunteer for it.

**Comment by elyanajhon** [comment]
Bitcoin, often dubbed 'digital gold,' continues to redefine finance. Its decentralized nature and limited supply make it a unique asset with vast potential. Whether you're an investor or simply curious, exploring Bitcoin's journey is a captivating ride through the world of cryptocurrencies. 💰🚀 #Bitcoin #Crypto<a href="https://btc-tools.cc/">btc tools</a>

**Comment by GBKS** [comment]
Time to close this issue. The conference was really great, and I think our initiatives worked out very well. For more detail, see the [newsletter](https://bitcoindesign.substack.com/p/bitcoin-design-newsletter-45) and the [community call recording](https://www.youtube.com/watch?v=gCyfRuOyp6E) from mid-June. Let's do this again sometime.
