### ISSUE TITLE
Fedimint Design Call #0

### ISSUE THREAD

**Issue by humansinstitute** [BitcoinDesign/Meta#497]
```meta
UTCTime: 2023-04-13 15:00 UTC
Duration: 1h
```

### Agenda

This is a Fedimint Dev Call that will discuss the development of UI components for the Opensource Fedimint project including:

- Federation setup UI.
- Lightning Gateway Management UI

There will be developers ready to work on coding up the output of these designs and explainers from Justin Moon on the concepts involved.

### Check your timezone

[https://everytimezone.com/s/c4027e25](https://everytimezone.com/s/c4027e25)

### Join the call

On Jitsi: [https://meet.jit.si/fedimintdevcall](https://meet.jit.si/fedimintdevcall) 

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by humansinstitute** [comment]
Note - updated to 3pm UTC

**Comment by GBKS** [comment]
Can we close this issue? Was there a recording or notes to share?
