### ISSUE TITLE
Accessibility Day Kick-Off Session

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#524]
```meta
UTCTime: 2023-05-18 7:00 UTC
Duration: 1h
```

![accessibility-awareness-day-23-230508](https://user-images.githubusercontent.com/695901/236841099-cc17340a-3be8-4f1f-8aff-61213ccc86a7.jpg)

### Agenda 

Let's discuss accessibility in bitcoin applications (also see [the guide page](https://bitcoin.design/guide/designing-products/accessibility/)). What we'll do:
- Give a basic introduction to accessibility and how it relates to bitcoin
- Discuss common issues
- Learn how to test for them
- Give pointers on fixing them

We're doing this as a morning session (europe morning for the organizers) as a kick-off so we can use the rest of the day to actively collaborate on accessibility things.

This for the larger initiative of the [Global Accessibility Awareness Day](http://accessibility.day). More on [this issue](https://github.com/BitcoinDesign/Meta/issues/492).

Join to get this sweet Nostr badge.

![image](https://user-images.githubusercontent.com/695901/236842481-1217e42d-9479-480b-8c84-ea20cae37acf.png)

### Check your timezone

https://everytimezone.com/s/c9e3d6c8

### Join the call

The call will be hosted via Jitsi. [Join here](https://meet.jit.si/bitcoindesign).

### Calendar

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by aassoiants** [comment]
Just want to confirm this is 7am UTC? Makes it hard to attend from the Americas

**Comment by GBKS** [comment]
Yes, that is intentional as this is a one-day event. Idea is to have an early kick-off for the day (early for the organizers), so people can continue to work throughout the day on accessibility things (for example, someone learns how to test in the session, then tests a few things, finds some issues that someone else later picks up, etc). We could also organize a second session is there's interest?

**Comment by GBKS** [comment]
Thanks to all who joined, it was a really good group and (I find) a great jam session on accessibility. Let's keep the momentum going through the day. Here are the recordings on [BitcoinTV](https://bitcointv.com/w/o2MFs3Ta1UtoXd5Djt9oyM) and [YouTube](https://youtu.be/9eiBVLIWF_Q).
