### ISSUE TITLE
Design Review Call: Damus

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#531]
```meta
UTCTime: 2023-05-25 15:00 UTC
Duration: 1h
```

![design-review-call-damus-230519](https://github.com/BitcoinDesign/Meta/assets/695901/9c634a2f-1648-4ddd-b68d-e950066dda66)

### Agenda

If you're familiar with [Nostr](https://nostr.com), the up-and-coming social media (and more) protocol, then you're probably familiar with [Damus](https://damus.io), the first iOS app built for it. In this call, the Damus team will present their design work and design system, and we'll then have a group discussion.

👨‍🎨[Review the Figma design file](https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=1907%3A42076&t=TA8ElIqwecSg8XUi-1)👩‍🎨

### Check your timezone

[Check your timezone](https://everytimezone.com/s/a17a6b5c)

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by alltheseas** [comment]
Targeting end of Monday for sharing design figma system.

**Comment by alltheseas** [comment]
@GBKS https://www.figma.com/file/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-iOS?type=design&node-id=1907%3A42076&t=TA8ElIqwecSg8XUi-1

**Comment by GBKS** [comment]
Thanks to all who joined. Recordings are now up on [BitcoinTV](https://bitcointv.com/w/c1WPrTXZAcs36sawq4j1ib) and [YouTube](https://youtu.be/ZxJuadgvrwQ). Let's keep the conversation going in Discord.
