### ISSUE TITLE
Design Review Call: Etta Wallet

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#532]
```meta
UTCTime: 2023-05-31 14:00 UTC
Duration: 1h
```

![design-review-etta-wallet-230523](https://github.com/BitcoinDesign/Meta/assets/695901/fe344ab5-120c-4529-8215-43719d2f3477)

### Agenda

Join us and learn about [Etta Wallet](https://github.com/EttaWallet/EttaWallet), a simple, open-source, and non-custodial bitcoin & lightning wallet with a strong bias towards usability, accessibility and good UX.

### Check your timezone

[Check your timezone](https://everytimezone.com/s/e3d27a21)

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by danielnordh** [comment]
Leaving some of the more minor feedback here to not take up too much time in the call.
All feedback shared to help, not criticize!

- Channels, maybe use Just in time channels?
- Backup of private key / seed? not clear to user how/if it is saved
- Do you need to show Start node screen? (There isn't really an option for the user not to start it)
- Some buttons don’t look native to iOS/Android (Language picker, back button)
- Only show network status if you go off line? (At the moment shows on every screen)
- Notifications of different designs (toast vs full drop-down)
- Block height might need a label, didn’t understand what it was at first. Does it need to be on main screen?

**Comment by crukundo** [comment]
Thank you so much @danielnordh. This so absolutely helpful. 

I especially like the idea of just in time channels. It's a simpler flow for users and UX in general and definitely ACK for everything else. Will make changes and check in for a review :)

**Comment by mouxdesign** [comment]
Links to recordings:
[Youtube](https://www.youtube.com/watch?v=mXrPAKIZe70)
[BitcoinTV](https://bitcointv.com/w/7KzM33KYAFqNNw8HCZhe4w)
