### ISSUE TITLE
UX Research call #23: Payjoin Case study & User Experience

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#548]
```meta
UTCTime: 2023-07-06 14:00 UTC
Duration: 1h
```

![Group 14088](https://github.com/BitcoinDesign/Meta/assets/90313394/282c99f6-482d-47e5-a83e-e11916d784de)

### Agenda
This call will be in 2 parts:
Part one; We will have a walkthrough and a bit of education about Payjoin, what it is and why it is important for privacy. This walk through will be done by Dan Gould.
Part two: Research was done in order to understand the Payjoin user experience. During this process the Payjoin user experience was explored in terms  of:
- The incentives and objectives for both senders & receivers
- The payjoin UX on both sides (sender and receiver)
Yashraj will walk us through this. 

Link to [case study](https://bitcoin.design/guide/case-studies/payjoin/) in Bitcoin Design guide. 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/f64f1cea)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/UXResearchBitcoinDesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to all who joined and the excellent presentations. Recordings are up on [BitcoinTV](https://bitcointv.com/w/r1AooDVD8YjAASQm6RoQco) and [YouTube](https://youtu.be/hJgHJsaCFcs).
