### ISSUE TITLE
Jam Session: European Bitcoiners

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#554]
```meta
UTCTime: 2023-07-04 12:00 UTC
Duration: 1h
```
![Group 14095](https://github.com/BitcoinDesign/Meta/assets/90313394/8cfc4a90-20e0-4d60-9e2a-286a919600d4)

### Agenda

During this session we will all jam together in Figma and come up with some design ideas for the Homepage of European Bitcoiners. This is a continuation of the initial call that we had here #533 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/65124621)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to Mo and Michael for jamming together, it was quite a fun session. Recordings are up on [BitcoinTV](https://bitcointv.com/w/htQEfx5Pip72LP2ga9Ermc) and [YouTube](https://youtu.be/1SX_cs4QgrA).
