### ISSUE TITLE
Liana Wallet Design Call

### ISSUE THREAD

**Issue by rabbitholiness** [BitcoinDesign/Meta#555]
```meta
UTCTime: 2023-07-06 12:00 UTC
Duration: 1h
```
![Liana](https://github.com/BitcoinDesign/Meta/assets/112604177/f4b9e360-f402-4932-b650-ee1539f15593)

### Agenda

In this call Kevin from the [Wizardsardine](https://wizardsardine.com/) team joins us to give us an intro about the [Liana Wallet](https://wizardsardine.com/liana/) and the way the team uses Miniscript and multisig wallets to improve Bitcoin custody and inheritance. We will discuss:

- What is Miniscript and why is it a powerful tool for Bitcoin custody and inheritance?
- Liana's approach and most important use cases
- (Design) challenges and lessons learned.
- What's next?

Kevin published two very nice, short [demo videos](https://twitter.com/Wizardsardine/status/1672290442199592960?t=UqL6mcEvareW4QnJzNx2Mw&s=19) on Twitter. Check them out.

### Check your timezone

(https://everytimezone.com/s/7977044c)

### Join the call

(https://meet.jit.si/bitcoindesign)

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to all who joined, especially Kevin from Wizardsardine. This was a very in-depth discussion into the technology. Recordings are now up on [BitcoinTV](https://bitcointv.com/w/86ccMhGhxK777bs7kdd9HD) and [YouTube](https://youtu.be/xzZCTzYSBY0). We may schedule follow-up calls, as a lot of topics and questions came up that we'd like to get into further.
