### ISSUE TITLE
Proposal for a FOSDEM 2021 presentation

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#58]
FOSDEM, a free event for open-source software, has a dev room dedicated to design at their conference in February. There was interest [on Slack](https://bitcoindesign.slack.com/archives/C015GFYSJNA/p1608029868072600) for putting together a proposal to present. We can do that in this issue.

Here's the description from the [devroom link](https://fosdem.org/2021/schedule/track/open_source_design/):

> The Open Source Design devroom showcases design work happening within free and open source projects, because yes, there is design live in FOSS. We mean "design" in a broad sense, and we include within that term typography, graphic design, interaction design, user experience, human-computer interaction, accessibility, information architecture, content strategy, service design, design research and add your favourite buzzword here.

The call for proposals is [here](https://lists.fosdem.org/pipermail/fosdem/2020q4/003147.html). They have to be submitted by Dec 21, only 6 days from now. Presentations are only 20 minutes, probably just enough time to cover one topic. However, as presentations are pre-recorded, we could get a bit creative with the format.

First thing, let's gather some topics to talk about. What do you think?

**Comment by johnsBeharry** [comment]
I think we should just continue to shill the tag line "Design bitcoin for everyone", what that means and how community and diversity means for open source projects.

It would be super cool to have a supercut of a bunch of the community members (doubt there's enough time to coordinate that) then highlighting some of the processes we're forming and also outputs.

Alternatively something more practical could be @Bosch-0 and your (@GBKS) experience contributing to heavily technical projects - and trying to make a space for designers.

**Comment by GBKS** [comment]
Alright, here's a start.

**Title:**
Design bitcoin for everyone

**Description:**
Since the middle of 2020, an open community has formed around the goal of making Bitcoin more intuitive and accessible. Our big project is a Bitcoin Design Guide to help both designers and developers create better Bitcoin applications faster. We also work to promote the idea of open design, to bring more designers into the space, and to help open-source projects adopt better design processes. This presentation will provide an overview of all these efforts, where we are (early) and what the future might hold.

**Comment by ConorOkus** [comment]
This looks good, might also be worth mentioning that we are designing the future of money and how we interact with it and so it might differ substantially from other types of FOSS projects.

**Comment by GBKS** [comment]
@johnsBeharry and I fleshed out a few more details in this [HackMD doc](https://hackmd.io/@BitcoinDesign/H1siDkChD).

Main thing, what should the subtitle be? Here are some options we came up with:
1. How we practice and spread open design to make Bitcoin more intuitive and accessible
1. Helping design for a global, digital currency in public
1. Decentralized, permissionless design

Share your feedback soon, as we need to submit this by the 23rd (in two days).

**Comment by GBKS** [comment]
Submitted it. Will update when I hear back. We can still update the proposal if anyone wants to make any changes.

This is the image I submitted for the event cover:

![bitcoin-design-fosdem-preview-square](https://user-images.githubusercontent.com/695901/102898861-6ebc7a00-446a-11eb-9fce-a956e82fcaad.jpg)

**Comment by GBKS** [comment]
Sweet, we got accepted, here's the email I got from the organizers:

---

Thank you for submitting your proposal and your contributions to design in Open Source software. Our devroom only exists with the help of our speakers.

**Good News!**
We are very happy to tell you that your proposal has been accepted!

**Your session time**

_Design Bitcoin for Everyone_

has been scheduled for Saturday 6th February at 14:00-14:20, Brussels time (UTC+01:00).

**What happens next?**

**1. Confirm by reply of email**
As soon as possible - please confirm by replying to this email, the time is suitable for you.

**Deadline to confirm this email by midnight (00:00 UTC) 4th January Tuesday, 2021.**

**This is important:** If we don't hear from you by then, we will assume you are not coming and we’ll remove your talk from the schedule.

**2. Devroom speaker point of contact**

Once you confirm your attendance at FOSDEM, we will email you the details of your Devroom Point of Contact. This is the person who will be your point of contact for all devroom related questions.

**3. Record you talk and upload the talk video**

As we explained in the Call for Proposals, FOSDEM’s organisers are requiring speakers to upload a recording of their talk. This is to make sure in the event of speaker Internet issues the talk can be streamed automatically.

Your Devroom Point of Contact will confirm the talk video quality is acceptable, and will provide help you if you need it when uploading the video.

** You must record and upload your talk. **    

**4. Write a short biography**

We also encourage you to write a short biography to introduce you properly before your talk. Please add it to the “person” page in Pentabarf:
https://penta.fosdem.org/ or send to me by email before the event.

**Devroom location**
The full details of the virtual devroom location will be shared with you closer to the date. 

**Session format**
You have 20 minutes in the spotlight that you can use at your discretion - you can either take all 20 to present or leave some time for more questions/discussion. There will be a virtual “hall” video room where discussions after your talk can continue.

Time for your session: 20 minutes
Time for questions, if you want: maximum 5 minutes

Out of respect to all attendees and speakers, we'll be enforcing the time.

**So make sure your content fits into those 20 minutes! We would hate to cut your talk short.**

**What happens next?**
You must reply to this email by midnight (00:00 UTC) 4th January Tuesday, 2021 confirming the time for your talk.

We will then send you details of your Devroom Point of Contact.

**Interested in volunteering with Open Source Design at FOSDEM?**
And last but not least - Open Source is made up of volunteers, there are lots of opportunities to contribute with Open Source Design collective.

**FOSDEM devroom**
Would you like to help at Open Source Design room?

This means helping with people attending the talks - helping people into the room and leaving safely, helping speakers get ready for their talk.

If you’re interested in contributing, let me know by reply of this email. 

**Organise the devroom for 2022**
If you're interested in organising our conference tracks, get in touch and let us know. You'll be very welcome!

Anything else?
Follow us on twitter, @opensrcdesign and be part of the community!

---

Let's start preparing that presentation :)

**Comment by GBKS** [comment]
The full FOSDEM schedule is available [here](https://fosdem.org/2021/schedule/track/open_source_design/). Good to see what topic others will be presenting on.

**Comment by GBKS** [comment]
Heard from our point of contact. We need to have our talk recorded and uploaded by January 13 (1 week from now, pretty tight). Our talk slot is 20 minutes, but they recommend the talk only being 15 minutes and leaving 5 minutes for questions. There's more info on the presentation format and upload requirements [here](https://discourse.opensourcedesign.net/t/fosdem-2021-support-for-speakers/2241).

**Comment by GBKS** [comment]
Summarizing info for the conference and our talk. First some details:

- The conference is on Feb 6 & 7
- Our talk is on Feb 6 at 14:00 CET ([see your local time](https://everytimezone.com/s/51522bce))
- Our talk will consist of a pre-recorded 15-minute video and then 5 minutes of Q&A. Conversation can continue afterwards in the conference chat based on interest

Now some links:

- [Page for our presentation](https://fosdem.org/2021/schedule/event/design_bitcoin_for_everyone/)
- [Schedule for the open-design track](https://fosdem.org/2021/schedule/track/open_source_design/)
- [How to participate in the conference](https://fosdem.org/2021/practical/online/)
- [Speakers manual](https://github.com/FOSDEM/video/blob/master/instructions/fosdem2021/speakers.md)

Would be great to have others in the community join for Q&A, I need to ask if I can somehow send invites to the speakers room (this setup is quite complex if you've seen the speakers manual).

Any questions? Let me know.

**Comment by GBKS** [comment]
The talk went well. I just uploaded the video to our Youtube channel. Now that the conference is over, we can share it freely. Here it is: https://youtu.be/LI-lpMgNSig

And the link to the [slides in Figma](https://www.figma.com/file/X2c9pGIr38rEzVuS0locAN/FOSDEM-slides?node-id=219%3A2292). We can use those as a foundation for future presentations.
