### ISSUE TITLE
Miami Bitcoin Design Club, first & in-person meetup

### ISSUE THREAD

**Issue by bitcoinphotographer** [BitcoinDesign/Meta#592]
Date: 2023-11-08
Time: 8am ET
UTCTime: 2023-11-08 8:00AM UTC -5

![DALL·E 2023-11-07 18 54 33 - Illustrate a 4K resolution flyer background that balances the 'grove feel' with the urban essence of Miami for a Bitcoin meetup  Feature fewer trees a](https://github.com/BitcoinDesign/Meta/assets/126423334/058009fb-6d11-41e0-b7e8-2d917a1c517c)

So excited to kickoff our first meetup, based in Miami, FL! 

### **Agenda**

We will start off with complimentary coffee & time for checking out the co-working space. 

Next we kickoff with:
- intros
- basic UX research principles and design tools
- discuss how this can be applied to enhance bitcoin adoption
- learn how we all can make contributions in the bitcoin space

We will conclude with a short presentation from Bitcoin Grove members and leave the remainder of time for open discussions.

_We will explore having calls for the virtual audience!_

### Check your timezone:
https://everytimezone.com/s/27112b85

**Comment by GBKS** [comment]
Very cool, looks like it already happened? How did it go? Would be cool to post earlier next time and promote it in the community for anyone local to join.
