### ISSUE TITLE
Design Review Call: 10101 Finance

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#593]
```meta
UTCTime: 2023-11-16 15:00 UTC
Duration: 1h
```

![design-review-call-10101-231110](https://github.com/BitcoinDesign/Meta/assets/695901/724401f1-8a12-47f1-afb3-93cff96d31ee)

### Agenda

The 10101 team would like your feedback on their app for decentralized finance on bitcoin. If you can, please [check out the project](https://10101.finance) and come prepared with notes. If not, all good as well, join the conversation.

10101 is also currently participating in the Legends of Lightning hackathon. Take a look at [their latest updates](https://bolt.fun/project/10101).

### Check your timezone

https://everytimezone.com/s/dbf4c2c1

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by SXBT69** [comment]
Hi everyone!!

**If you need access to the 10101 app**, feel free to send a DM to @get10101 on X, and we'll give you access (as it's still in closed beta as I write this).

**Comment by SXBT69** [comment]
Hi friends!

Here, you will be able to find the NEW designs ongoing : https://www.figma.com/file/5BgcmpxFA7AHN2bs8Cd8wC/10101-Mobile-app-design?type=design&node-id=0-1&mode=design

**Comment by GBKS** [comment]
Thanks to all who joined, what a good discussion. We dug up all kinds of complexities, much more than can be resolved in a single hour. But I think we ended up with a clear next step. 10101 wants to have a usable version of their "stabledollar" feature by the end of [Legends of Lightning](https://bolt.fun/tournaments/legends-of-lightning-vol2/overview) in a month. That means creating a clear UX for this feature for allowing users to smoothly peg in and out, understanding enough of what is happening to make good decisions and feel comfortable. Would be awesome to see some collaboration happening around this in the community. Let's continue the discussion in Discord. The call recordings are up on [YouTube](https://youtu.be/_3SjoGMdt3E) and [BitcoinTV](https://bitcointv.com/w/p9W75GqJK7GST3eb85jryo) and notes are [here](https://docs.google.com/document/d/19qBxXxPVWj4uQjVcyceEL5i3OMJpvNiDmo_wzcg-Isg/edit?usp=sharing).
