### ISSUE TITLE
Miami Bitcoin Design Club, Meetup #02

### ISSUE THREAD

**Issue by bitcoinphotographer** [BitcoinDesign/Meta#596]
Date: 2023-11-22
Time: 8am ET
UTCTime: 2023-11-08 8:00AM UTC -5

![bitcoinphotographer_bitcoin_art_for_designers_with_an_urgan_gro_cd1f8bc1-7739-4bba-a3ac-519de9bea8ab-2](https://github.com/BitcoinDesign/Meta/assets/126423334/02aba2f5-8a09-49ff-9d66-28be24f8f0f0)

Join us at the Bitcoin Grove in Miami to discuss user experience as it relates to Bitcoin adoption. Our discussions are meant to brainstorm and inspire us to build solutions, as we learn how to address needs of all types of users. Come and check out the co-working space, meet some folks, and share ideas!

Link to event on Meetup:
https://www.meetup.com/bitcoin-grove/events/297237531/?utm_medium=referral&utm_campaign=share-btn_savedevents_share_modal&utm_source=link

Check your timezone:
https://everytimezone.com/s/69af745d

**Comment by GBKS** [comment]
This event has passed, so going to close the issue.
