### ISSUE TITLE
Learning Bitcoin and Design #16: Silent Payments

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#622]
```meta
UTCTime: 2024-02-08 15:00 UTC
Duration: 1h
```
![Silent Payments Call (1)](https://github.com/BitcoinDesign/Meta/assets/90313394/6abf3cfe-05d4-49ae-95a4-92235a6b113f)

### Agenda

During this call we will have one of the bitcoin core devs who is working on silent payments. He'll help us to understand silent payments and it will be an open call to ask questions and learn. 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/10023a97)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Josi gave us a great introduction to silent payments in this conversation. We talked about the history of similar efforts, benefits and drawbacks, how it works, status of the project, adoption path, and lots more. I created an issue to follow up with exploring this feature set further in design with #635. Recordings are up on [BitcoinTV](https://bitcointv.com/w/pYvgq8xGg6oKQawKwcetx3) and [YouTube](https://youtu.be/Cqmk2cZ2IjM), and notes are [here](https://docs.google.com/document/d/1BEL0ANB4HupnWx1iv2oCK_lJdEHWCbeHCV-xBGFWvpg/edit?usp=sharing). Thanks to all who joined.
