### ISSUE TITLE
Learning Bitcoin and Design #15: Covenants Part 2

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#623]
```meta
UTCTime: 2024-02-02 14:00 UTC
Duration: 1h
```

![learning-bitcoin-and-design-covenants-2-240123](https://github.com/BitcoinDesign/Meta/assets/695901/4ceba544-24aa-4fcb-a00a-3ceb5fa0a981)

### Agenda

In our [first call](https://github.com/BitcoinDesign/Meta/issues/608) about covenants, we had a great discussion around the basics and certain use cases. Consensus was to have another call to go deeper into more individual use cases, which this call is for. This is meant to be a casual session where no prior knowledge is required, and we learn together.

Let's use the replies to decide on which uses cases to look into. I believe the suggestions so far were congestion control and scaling techniques (aka trees in trees in trees).

Also see [this issue](https://github.com/BitcoinDesign/Meta/issues/607) to track our covenants investigation. More from the [Learning bitcoin & design](https://github.com/BitcoinDesign/Meta/issues/269) series.

### Check your timezone

https://everytimezone.com/s/91c42568

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Continuing our discussion from our first call, we dove into how covenants might play out in scenarios around chaining transactions, payment pools, and cold lightning channels. We made good progress, but also still have questions. Recordings are up on [BitcoinTV](https://bitcointv.com/w/cpSD2oVGcrRibkBZZ1V8TF) and [YouTube](https://youtu.be/zk_EEKeAFuY).

**Comment by elenananana** [comment]
@GBKS - can you link the three threads you mentioned in the video? thank you!
