### ISSUE TITLE
BTC Prague 2024 hack-day

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#637]
We had a great time at [last years BTC Prague](https://github.com/BitcoinDesign/Meta/issues/495), and are in conversation again with the organizers. [The event](https://www.btcprague.com) is June 13-15.

Last year we organized a design track on hack-day, and also had a booth at the main conference.

From initial conversations with a few people, there is less interest in a booth. While it was fun to hang out and meet, it was not deemed to be so effective at reaching designers and builders. People attending the booth and speaking with visitors also stated that they got really worn out after 2-3 days. If we primarily want to have a space for designers to hang out together, we could think of different ways of making this happen.

For the hack-day design track, we got good feedback from the organizers. They are happy for us to organize another one this year, and possibly do more.

All of this is in super early conversation, so it's best if we come up with ideas and a plan of what we'd like to do. What do you think?

**Comment by rabbitholiness** [comment]
The [dev/hack/day](https://www.btcprague.com/dev-hack-day/) will take place on June 12 and it will be held in a different location than the main conference.

We have put together a [Google doc](https://docs.google.com/document/d/1nd9tlwpKnj--PuLRacJA8YJXiZZ5zgkgeDs6wm-TydE/edit#heading=h.wpzdaytwgg1) to gather ideas and as a working document. Feel free to chime in.

**Comment by GBKS** [comment]
We spent the latest community call chatting all about BTC Prague. Here's the [issue](https://github.com/BitcoinDesign/Meta/issues/631) and the [recording](https://www.youtube.com/watch?v=Xy5cheiNhkI).

Generally, there is a good amount of interest, so I think we can commit to doing this. For questions and more, join the conferences channel in the Bitcoin Design Discord.

**Comment by mouxdesign** [comment]
We had some fun today during the design huddle. We jumped into a [figma](https://www.figma.com/file/syZVyz0gAuXZTXGpi4Hud3/BTC-Prague-Hack-Day-2024?type=design&node-id=0-1&mode=design&t=cMpbYQWsijFMImTd-0) and all started to think about the layout of the room for BTC Prague.
- We grabbed some furniture ideas to make the room cosy
- We estimated what the floor size would be that we'd have to work with
- Idea: Walk the UX journey. 
A red carpet in the middle of the room and pit stops along the way. This could for example only part of the day and then the rest of the day allowing for talks and workshops, card games and a design duel which was a favorite last year.

**Comment by GBKS** [comment]
Since this thread here is a pretty quiet, there's a lot in the works for the conference. The furniture and layout concept for the space is set, several talks are confirmed and we're looking for more speakers, and lots of little organizational things are also getting discussed and moving forward. Check the [#conferences](https://discord.gg/XHGNS3HqNd) channel to stay in the loop and participate.

**Comment by GBKS** [comment]
The event turned out great. The room design worked out very well and we had a lot of interesting talks with good attendance. [The newsletter](https://bitcoindesign.substack.com/p/bitcoin-design-newsletter-61) has some photos and a brief summary.

The only thing that did not go well were the afternoon activities and design battle. We were in audience competition with some other really good talks and panels at that time. Especially for the design battle, I think it would be helpful for us if we sign up people for it beforehand to ensure we have participants ready to go. On the other hand, I've heard from people that they were exhausted in the afternoon after listening to lots of talks and would have liked to hang out in our design lounge if they had known about it.

We're gathering feedback on the event to inform future planning.

**Comment by GBKS** [comment]
We did a bit of a retro and gathered thoughts on how it went [in this doc](https://docs.google.com/document/d/1iqU1-48mZqfYRbLUOdlzBWDAKxJ6lUPL8150HJqQ0jU/edit?usp=sharing), which will help us improve future events like this.
