### ISSUE TITLE
Global Accessibility Awareness Kick Off Session

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#655]
```meta
UTCTime: 2024-05-16 07:00 UTC
Duration: 1h
```

![303594583-2316b9c3-d6c6-4004-867f-a0a75310f907](https://github.com/BitcoinDesign/Meta/assets/90313394/4c63ff31-e877-4850-8c07-a2b7aba03486)

### Agenda

We'll have a deep dive into accessibility to celebrate [Global Accessibility Awareness Day](https://accessibility.day/). This call invites builders to get hands on with learning and testing for accessibility. The call will include:
- How to improve accessibility
- How to test for accessibility

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/fe1e4d01)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to all who joined the call, I think we had a group of 13. We did a quick round of introductions, I gave an intro to accessibility, Mo an overview of our prior testing efforts, and Czino a presentation on the technical side of web accessibility. After some brief conversation, we went off to go about our days (and maybe test and file issues with projects).

Recordings are on [BitcoinTV](https://bitcointv.com/w/3aHxqvCGyXstPy5iE4baV8) and [YouTube](https://youtu.be/wHvtnfuRBzs).
