### ISSUE TITLE
Bitcoin Design Guide: Use Cases and Interviews

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#673]
![Screenshot 2024-04-22 094631](https://github.com/BitcoinDesign/Meta/assets/90313394/11c97aa5-44e9-40f5-8dae-112a5584df9d)

The Bitcoin Design Guide is an extensive resource used by builders. Like any resource collecting user feedback and documenting this will provide insight as to:
- Use cases: Understand how the guide is being used by builders
- Areas for improvement: Which areas of the guide can be improved

## Interview method
The data in the repo will vary and be collected from various sources:
- One-on-One interviews using the following [script](https://docs.google.com/document/d/1tiMAhtbs2A5z_lamDbUMtGoLXIfat4QcZahwcJJJd0o/edit)
- Publicly available information

## Consent privacy
People who are interviewed are asked for their consent to place an edited version of the interview in a public repository where all private information is removed.

This will help to build a higher level overview from various resources. 

## Previous research done
In 2022 a survey was done on the Bitcoin Design Guide, the survey results can be found [here. ](https://github.com/BitcoinDesign/Meta/issues/320)

**Comment by mouxdesign** [comment]
Interview 1

[Transcript](https://docs.google.com/document/d/1N7fISo5KAAxPPlUrQyhK7EG1oRN8b4IH/edit)

## Background
X is a developer building and designing a bitcoin lightning wallet, this is a solo wallet builder that also contributes to various initiatives in the ecosystem. A lightning wallet is being built that has more advanced features. 

## Resource/s used
- Bitcoin Design Guide
- Bitcoin UI kit

## Most used part of the guide
- Daily spending wallet
- Glossary

## How is it used?
1. Daily spending wallet:
The daily spending wallet is used as a reference design as he is building the lighting wallet. He uses it to envision how the user flow is going to look like from the design side. he uses it as a starting point to understand what the first screen should look like in a particular part of the user flow. 

2. Glossary
The glossary is used as a educational tool to explain seemingly complex topics to others. It is also used at bitcoin meetups to explain concepts to less technical people. When the code in the repo does not make sense to someone to understand he'll go over to the guide to see if there is an explanation or glossary entry about that topic.

## Areas for improvement
None

## How was research done to build the wallet?
The builder started using himself as the main user of the wallet, building a wallet for people like himself. The wallet is being built with the following thoughts in mind:
- What does the user exp feel like?
- Do I trust putting my bitcoin in this wallet?

## Main takeaways
The Bitcoin Design guide is being used by a solo builder who is building a lightning wallet with more advanced features. The daily spending wallet is the most highly used part during the building process and it is used as a starting point for the builder to understand what the starting point of a design would look like in a particular part of a user flow.

The glossary of the guide is used as an educational tool to explain technical concepts in a more human way to others.

**Comment by mouxdesign** [comment]
Discord chat 2

[Link to chat record](https://docs.google.com/document/d/12HvPbrW6qmbFlZr71G4r-LLeWwiTmJc9YsNYpGf50dg/edit)

## Background
The following info was collected in the Discord server of a wallet team. The wallet is a self-custodial lighting wallet. The wallet is being built by a small team. The front end-developer also has the role of UX designer. The builder was in the process of re-designing the wallet and spoke specifically about what was useful during this re-design phase in terms of resources and help received. 

## Resource/s used
- Bitcoin Design Guide
- Bitcoin Design Community Newsletter

## Most used part of the guide
Daily spending wallet
The following parts of the guide were referenced during the conversation
- [Backup and Recovery: recovering with a manual backup](https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/recovery/#recovering-with-a-manual-backup)
- Contacts 
- Activity 

## Other resources and help received
Other apps and wallets:
- Venmo
- Signal
- Other wallets
- Fantasy redesign: A design problem was presented to an engineering cohort and a redesign was done using that problem, this design was then presented by the UX designer in the cohort and he used quite a lot from that fantasy re-design. 

## Reasons the guide may not be used
- Time constraints
- Guide has more screens and steps
- Used design directly from another wallet or designed something he really likes

## Main takeaways
The wallet builder has used the Bitcoin Design Guide from time to time during the re-design of the wallet. The most used section was the daily spending wallet. 

During the redesign process the designer consulted with various sources to refine the design, it is usually a mixture of referring to other wallets, using a fantasy re-design done by another UX designer and referencing the guide.

The Bitcoin Design Community Newsletter was also mentioned as being discussed during meetups in the city of the builder.

**Comment by GBKS** [comment]
Minor thing, this could be an issue in the repo of the guide. Thank you for doing these interviews.

**Comment by mouxdesign** [comment]
Good idea. Moved over to the [guide repo.](https://github.com/BitcoinDesign/Guide/issues/1097)
