### ISSUE TITLE
MyMattress app

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#68]
![mymattress-brief-cover](https://user-images.githubusercontent.com/695901/106491006-b2b58c80-64b6-11eb-8089-ac240dfb386e.png)

**Goal**
Improve the user experience of the MyMattress mobile app and add a new multisig feature.

**Project context**
MyMattress is the demo/reference implementation for the [Photon SDK](https://photonsdk.org/), a library to build mobile wallets using cloud backup for private key management.

**Collaboration type: [#3 New project](https://docs.google.com/document/d/1vHHauCktbITPqKApQ5h-i7cFh4W5Y-qqVcpUvlZKKFY/edit?usp=sharing)**
There are a few collaborators working on the Photon library, with no focused work going on for the MyMattress app. So the design needs to be built from the ground up.

**Team**
- Tankred (dev lead until March)
- @ConorOkus
- Leon
- @GBKS (design)

**Notes**
- Tankred, Conor, Leon and Christoph discussed an approach on Jan 22, 2021.
- Tankred will stop working fulltime on Photon in March. He will be involved, but not lead.

**Suggested process**
- Design the wallet experience in Figma first
- Evaluate with the team ?
- Build ?

**Timeline**
- Design to be complete by the middle of February ([issue](https://github.com/photon-sdk/photon-app/issues/15))
- ?

**Next steps**
- Christoph to iterate design, see if other designers want to help

**Links**
- [Website](https://photonsdk.org/)
- [Github repo](https://github.com/photon-sdk/photon-app)
- [Design progress issue](https://github.com/photon-sdk/photon-app/issues/15)

**Comment by johnsBeharry** [comment]
What are the technical constraints? If its open, there was some way for two users to communicate within the app through some messaging protocol, or Tor (even lightning) it could streamline the setup quite a bit. Of-course the limitation is the devices all needing to have an internet connection.

Got a slide on it here https://docs.google.com/presentation/d/1qIhzGTTFxwRZlvu33Fuwkv70YtJoj-tMHNmS_dt1n6M/edit#slide=id.ga33ab74ac7_0_56

Looking forward to seeing this process unfold, really exciting stuff folks.

**Comment by GBKS** [comment]
@johnsBeharry the scope will be really limited for this first version - restyling and adding multisig via Coldcard. Afterwards we'll just have to see what everyone wants to do.

**Comment by GBKS** [comment]
MyMattress was discussed during the [Design Review #9](https://github.com/BitcoinDesign/Meta/issues/47) call. [Watch the video](https://www.youtube.com/watch?v=a-uXxXSzCmg).

**Comment by GBKS** [comment]
This project is currently on hold and may get picked up again if there are more development resources (interested? make it happen), or priorities change. The design is now archived in a [dedicated Figma file](https://www.figma.com/file/GoXVUJV1mgJiSc4S974Jdh/MyMattress?node-id=812%3A0).

**Comment by MPL14** [comment]
How could I help with this ?

**Comment by GBKS** [comment]
@MPL14 thanks for your interest. There is currently nobody working on the project, but you are more than welcome to kick things off again. The design is in good shape, the basic tech (Photon SDK) as well, so there's a lot of app development and UI implementation work that needs to happen. Is that something you're interested in?
