### ISSUE TITLE
Design Review Call #38: 10101

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#681]
```meta
UTCTime: 2024-05-23 14:00 UTC
Duration: 1h
```
![Group 14277 (1)](https://github.com/BitcoinDesign/Meta/assets/90313394/e0832255-d10e-4073-95e0-6afa7a629ad4)

### Agenda

[10101](https://10101.finance/index.html) have redesigned the user activating flow and this community call we'll look through the flow. 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/7437382c)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by Science-G** [comment]
The mockup for the new design is here!
https://www.figma.com/design/5BgcmpxFA7AHN2bs8Cd8wC/10101-Mobile-app-design?node-id=1397-8262&t=BDpdQQVIDFkDiFQQ-0

**Comment by GBKS** [comment]
Was there a recording for this call? Can we close this issue?

**Comment by mouxdesign** [comment]
[Youtube](https://www.youtube.com/watch?v=ZUOM__6yM3s)
[BitcoinTV](https://bitcointv.com/w/7wnN5EPVUGgAP2Dc26NhmE)
