### ISSUE TITLE
UX challenges building a lightning wallet

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#682]
```meta
UTCTime: 2024-07-02 13:00 UTC
Duration: 1h
```

![Group 14281](https://github.com/BitcoinDesign/Meta/assets/90313394/65783cc8-e5ea-4d27-b437-9fe60830312a)

### Agenda

During this call we will discuss the UX challenges involved in building a Lightning Wallet. 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/638cb0d6)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by arteepa** [comment]
Excited to participate in this conversation!

**Comment by mouxdesign** [comment]
[Youtube](https://www.youtube.com/watch?v=bYSparT07g4)
[BitcoinTV](https://bitcointv.com/w/ueSDZES8ci5HFYXXhxc64v)

**Comment by GBKS** [comment]
Here are the [call notes](https://docs.google.com/document/d/1S3pEf0FmY8mrkgXc76UdIvxBZ0n2-uiaXwYteyTolkE/edit?usp=sharing).
