### ISSUE TITLE
UX Research Call #38: Gen Z

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#695]
```meta
UTCTime: 2024-07-11 14:00 UTC
Duration: 1h
```

### Agenda
![Group 14288 (1)](https://github.com/BitcoinDesign/Meta/assets/90313394/6776e2c5-de02-4dbc-9094-63e74fcb303e)

Adoption: What research can we do to understand the psychology of GenZ when talking about money and their futures? What is drawing them to Bitcoin? Why are they hesitant to use bitcoin?

Bridging: How can we educate GenZ on using their existing skill sets to work in different disciplines of Bitcoin jobs?

This call idea was initiated by Autumn from [Generation Bitcoin](https://x.com/GenBitcoiners) who is keen to conduct the research and share it with the community. 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/e3d9bb11)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/UXResearchBitcoinDesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Timezone link is not correct on this one (it uses 14:00 UTC, but the event description above uses 16:00 UTC).

**Comment by mouxdesign** [comment]
Thank you for spotting that. Edited UTC time to 14:00. CET time for time zone link at 16:00 CET.

**Comment by GBKS** [comment]
This was a really nice collaborative call where we first discussed the topic based on Autumns experience with her university initiative. Then we had several rounds of brainstorming sessions to narrow in on what to research more specifically. Recordings are up on [BitcoinTV](https://bitcointv.com/w/iz13hhZ7JSJxmqwUCSMGrE) and [YouTube](https://youtu.be/fQ0ue8stkpQ). Thanks to all who joined.
