### ISSUE TITLE
Zeus

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#70]
![zeus](https://user-images.githubusercontent.com/695901/107341034-cb2d3480-6abe-11eb-9779-cbdfc3009732.jpg)

[Zeus](https://zeusln.app) is a mobile Lightning wallet for advanced users who run their own nodes.

**Project Context**

Zeus was started by Evan to scratch his own itch. It is still a side-project next to this main job. 

**Collaboration type: [#3 Redesign](https://docs.google.com/document/d/1vHHauCktbITPqKApQ5h-i7cFh4W5Y-qqVcpUvlZKKFY/edit?usp=sharing)**

Evan mentioned in the design review call that we is very open to various design contributions. A good opportunity to design a project from the ground up.

**Team**

- Evan (Project lead)
- Liaison ?
- Design - @Bosch-0 and Gabor started contributing ([Figma file](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=5%3A2))

**Notes**

This could be a huge amount of work. It needs to be split up so it can be tackled with the available resources. 

A linear approach could look something like this:

- Recreate current screens and site in Figma as a base for design work
- Revise brand and create a general style guide
- Create a UI style guide
- Implement revised UI elements
- Revise onboarding flow
- Revise main wallet experience screen-by-screen
- New features and larger changes

Another approach could be to split the work up by deliverables/specialization, for example:

- User research
- Iterate the brand
- Website redesign
- UI style guide
- Interaction design

This will likely be a slower design process as Zeus is a side-project. It is fully open-source though and might be a good opportunity to run it very publicly, regularly posting updates, to create broader design conversation.

**Suggested process**

**Timeline**

**Next steps**

- Find interested designs
- Discuss best approach with Evan

**Links**

- [Project website](https://zeusln.app)
- [Design review call video with introduction & discussion](https://youtu.be/h5QtVVJS1zY?t=4031)
- [Github repo](https://github.com/ZeusLN/zeus)

**Comment by Bosch-0** [comment]
As @GBKS mentioned I have started doing some design work on Zeus. Most my focus is on the on-boarding flow as well as making a rough style guide / UI elements as I've been going through the process. 

I'm happy to recreate the current wallet / website screens on Figma as I've already started this also. My current design work on Zeus can be found here - https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=5%3A2. Send me a message on Figma if you want to collab on this file.

Going forward here is my suggestions in the order they should be done:

**Stage 1**
- Develop a more established style guide alongside other designers. I have various elements laid out in my Figma file that need cleaning up / discussed more in depth (still not fixed on a color palette for example). 
- Revise the branding of Zeus, this should be done a alongside developing the style guide. Gabor from BDC is currently working on a new logo and various other designs I'm very excited to see. 

**Stage 2**
- Design and implement new website whilst applying newly established style guide - any takers on this? Need someone who can develop and someone who can design or someone who can do both. I can do both and will likely start working on this if there are no takers by the time we get to this stage. 
- ([WIP](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/?node-id=5%3A2)) Design new on-boarding flow whilst applying newly established style guide.
- Begin work on the internal wallet. This has some very complex UI/UX issues to solve that I would be very keen to collab with someone on solving. Very interested in learning more about Lightning and this is my way of doing so. 

**Stage 3**
- Conduct user testing on the newly designed wallet / website. 

**Stage 4**
- Dev hand over of wallet designs to Evan / Zeus contributors for implementation.
- Have all the design contributors work on a case study that can be utilized by the BDC

**Comment by mgaborr** [comment]
hello, 
here is the link to the [design explorations](https://docs.google.com/presentation/d/1KZ11fjSTJXQa1cuSRXiK4DcEhfbjZs3oXkCqqYJ2-Ds/edit#slide=id.g44f5c35144_0_0)

all the elements are modular and interchangeable.
for the winning route, we might consider creating a sleek transition animation from the loading screen to the landing page.

![ce000_zeus app redesign-1](https://user-images.githubusercontent.com/77788329/107621728-4a6e6400-6c89-11eb-8cfb-d5b2c62ff2f6.png)
![ce000_zeus app redesign-2](https://user-images.githubusercontent.com/77788329/107621745-4fcbae80-6c89-11eb-9a4c-9f5b7419517e.png)
![ce000_zeus app redesign-3](https://user-images.githubusercontent.com/77788329/107621751-50fcdb80-6c89-11eb-9e4e-0afd41bb003a.png)
![ce000_zeus app redesign-4](https://user-images.githubusercontent.com/77788329/107621755-51957200-6c89-11eb-9d4a-aacf60477966.png)

**Comment by Tiana01** [comment]
> As @GBKS mentioned I have started doing some design work on Zeus. Most my focus is on the on-boarding flow as well as making a rough style guide / UI elements as I've been going through the process.
> 
> I'm happy to recreate the current wallet / website screens on Figma as I've already started this also. My current design work on Zeus can be found here - https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=5%3A2. Send me a message on Figma if you want to collab on this file.
> 
> Going forward here is my suggestions in the order they should be done:
> 
> **Stage 1**
> 
> * Develop a more established style guide alongside other designers. I have various elements laid out in my Figma file that need cleaning up / discussed more in depth (still not fixed on a color palette for example).
> * Revise the branding of Zeus, this should be done a alongside developing the style guide. Gabor from BDC is currently working on a new logo and various other designs I'm very excited to see.
> 
> **Stage 2**
> 
> * Design and implement new website whilst applying newly established style guide - any takers on this? Need someone who can develop and someone who can design or someone who can do both. I can do both and will likely start working on this if there are no takers by the time we get to this stage.
> * ([WIP](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/?node-id=5%3A2)) Design new on-boarding flow whilst applying newly established style guide.
> * Begin work on the internal wallet. This has some very complex UI/UX issues to solve that I would be very keen to collab with someone on solving. Very interested in learning more about Lightning and this is my way of doing so.
> 
> **Stage 3**
> 
> * Conduct user testing on the newly designed wallet / website.
> 
> **Stage 4**
> 
> * Dev hand over of wallet designs to Evan / Zeus contributors for implementation.
> * Have all the design contributors work on a case study that can be utilized by the BDC
> 
> Something else worth noting is that any designers looking to get on board is that all their design work will be FOSS.

@Bosch-0 Really nice work on the onboarding designs so far. I'd like to contribute to the design of the website if that would be possible

**Comment by Bosch-0** [comment]
@Tiana01 send me a DM on slack, would you want to get with ironing out a style guide first? Just so the app / website are on the same page

**Comment by Tiana01** [comment]
I'm currently working on the Zeus style guide. You can view my progress here
https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=182%3A39

**Comment by Tiana01** [comment]
### **Update**
**plans for the next period of work**
I intend to start working on the website design for Zeus

**progress since the last update**
Added more components to the style guide. We decided that we will keep expanding the style guide as the design progresses

**Comment by Tiana01** [comment]
https://www.notion.so/Zeus-website-redesign-9cc7583c15184f1bba5df23416562c78

documenting some ideas, observations, plans, etc for the website design

**Comment by Tiana01** [comment]
### Update
**plans for the next period of work**
I intend to round up the first version of the HI-FI Design

**progress since the last update**
started working on the Hi-Fi after the wireframes

**Comment by GBKS** [comment]
If you don't mind me asking, how long is the next period of work, what is involved in creating a high-fidelity design and would you like any help or feedback?

**Comment by Tiana01** [comment]
> If you don't mind me asking, how long is the next period of work, what is involved in creating a high-fidelity design, and would you like any help or feedback?

@GBKS 
I've added some comments to the Figma file with some questions on certain aspects I'd like to get feedback on
https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=702%3A0

![zeus home](https://user-images.githubusercontent.com/40744535/112492644-b8767280-8d81-11eb-8a4b-0f1345dee9b0.png)

**Tasks moving forward**
- Status update and feedback from Evan on the scheduled call 
- Revisions based on the feedback 
- Presenting on design review
- Include application screenshots once redesign is finalised
- Design review 
- Design mobile and responsive versions

**Comment by Bosch-0** [comment]
Few updates:

- Going to start some basic user testing of the onboarding flows this week: https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/?node-id=5%3A2. General feedback on the design user flows would be much appreciated! 

- Meeting schedule with Tiana and Evan, we will be doing fortnightly Jitsi calls on [Wednesday 22:00 PT](https://everytimezone.com/s/aae903ba ), pop me a DM on slack if you'd like to join. Stephen DeLorme will be joining in to discuss working on some fresh branding / graphic designs for Zeus. 

- Began research / rough designs of the internal wallet UI/UX, keep an eye on this Figma page for updates: https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/?node-id=134%3A661.

- Myself and Tiana have also began integrating the [Bitcoin Icon set](https://github.com/BitcoinDesign/Bitcoin-Icons) into our designs. I think we are the first so Zeus should be a great example of this set out in the wild.

**Comment by Bosch-0** [comment]
Notes from last weeks Zeus meeting:

**Attendees:** Evan, Tiana and Bosch

**Running time:** 60 minutes

**Agenda:** 

1. General dev update from Evan
    - Preliminary research on integrating messaging into Zeus using LN key sends underway.  
2. Evan and Stephans discussion on branding / graphic designs.
    - Stephan DeLorme is coming on board with the project to work on branding / general graphic design work. 
3. Website update ([Link](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/?node-id=135%3A1))
    - Tiana completed F.AQ and downloads page designs
    - Bosch made some suggestions around copy / general design ([Link](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/Zeus?node-id=1040%3A1684))
4. Wallet update
    - Internal wallet designs underway ([Link](https://www.figma.com/file/TqAM4LvuqvY7FBzFoaezJC/?node-id=134%3A661)) 
5. Zeus Documentation
    - Planning for detailed Zeus documentation underway. Will be similar to [BTCPay docs](https://docs.btcpayserver.org/) design wise.
    - Bosch and Tiana will start working on this more in-depth once website / wallet designs are completed.

**Comment by GBKS** [comment]
Going to close this issue as there is no current collaboration happening. We can re-open or open a new issues if things change.
