### ISSUE TITLE
Voltage Block Clock Web Component

### ISSUE THREAD

**Issue by sbddesign** [BitcoinDesign/Meta#704]
```meta
UTCTime: 2024-08-12 13:00 UTC
Duration: 1h
```

![image](https://github.com/user-attachments/assets/d4ecc792-d420-4fca-9380-e8a2c258e010)

### Agenda

The Voltage team has implemented the Bitcoin Core App's Block Clock as a Web Component. On this call, the Voltage frontend crew will demo how to use the Web Component in a web dev project and discuss some of the nuances of going from the Block Clock design to the Block Clock code.

### Check your timezone

https://everytimezone.com/s/37e8cb45

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by mouxdesign** [comment]
Video Recordings:
[Youtube](https://youtu.be/igKZ-IPlADY)
[BitcoinTV](https://bitcointv.com/w/a6ae4afAdUbJiTCKWbPCQy)
