### ISSUE TITLE
Ecash PR review 

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#706]
```meta
UTCTime: 2024-09-05 14:00 UTC
Duration: 1h
```

![Group 14303 (1)](https://github.com/user-attachments/assets/f568513c-cef0-47ab-ab8e-bd4891996aaa)

### Agenda

During this call we will review the [Ecash PR](https://github.com/BitcoinDesign/Guide/pull/1093) which Erik is working on.

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/aa8e4d68)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by swedishfrenchpress** [comment]
Perfect timing! I just completed the first version of the ecash guide . You can check out the deployment here: https://deploy-preview-1093--bitcoin-design-site.netlify.app/guide/how-it-works/ecash/introduction/

If anyone spots anything that could be improved or clarified, please let me know. You can either reply here or directly comment on the draft PR: https://github.com/BitcoinDesign/Guide/pull/1093

Really looking forward to this review so we can take this to the next level!

**Comment by mouxdesign** [comment]
Closing issue as we are setting up one more PR Review call.
