### ISSUE TITLE
Proposal for a Figma Config 2021 presentation

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Meta#71]
After [the awesomeness](https://www.youtube.com/watch?v=LI-lpMgNSig&feature=youtu.be
) of FOSDEM 2021, shall we participate in [Figma Config 2021](https://config.figma.com)? It's a virtual design conference, and there's a [call for speakers](https://sessionize.com/config2021).

The suggested topics are as follows;

> **In the file**: A deep-dive into the tactics, processes, and systems that keep teams running
> 
> **Embracing the mess**: Stories about the challenges, obstacles, and difficult moments that ultimately make products better
>
> **Shifting team culture**: A look at how teams shift from a culture of "my ideas" to "our ideas," and why bringing more people into the design process moves the work forward

Some other details:
- If we decide to participate, the deadline is `2021-02-21 07:00 UTC +7` to respond with a proposal for the talk.
- April 21st @ 9am PT
- $1000 honorarium (we can donate it, or if they pay in bitcoin we can use this to kick start a community fund)
- Free for attendees
- Packed with designers, but unlike FOSDEM are probably unaware of open design, or bitcoin

Anyone up for this? If yes, how would we structure such presentation?

[Presentation Planning Document](https://hackmd.io/@BitcoinDesign/S1-dLZz-_/edit)

**Comment by Bosch-0** [comment]
Keen to help out, embracing the mess topic seems to fit well with BDC. we could discuss the challenges, obstacles, difficult moments and opportunities of designing in the open source space and how we as a community hope to set some open source design standards that can be applied outside of just Bitcoin. Things we could discuss: 

- How Bitcoin is a great for setting open source design standards, Very large FOSS project (top 100 globally), blank slate with regards to design, globally impactful project. 
- The unique UX challenges Bitcoin offers - big topic with lots of potential areas we could go into. 
- Benefits of open source design - no barriers to entry, meritocracy based, non-discriminate, potential for big impact with little work, border less - anything else to add? A random note here is that I think as a new designer contributing to open source projects is the best way to get experience whilst also doing work that has some value in the real world. Mocking up fake case studies and projects for a design portfolio just seems like a waste of resources that could be applied to some much need open source projects. 
- Challenges of working with open source projects - maybe use a case example? @pavlenex with BTCPay or myself with Bitcoin Core maybe? 

I'll update this as I have more thoughts!

**Comment by Tiana01** [comment]
Is the presentation more focused on open-source design, what it means, how it works, benefits, etc than designing for bitcoin itself?

**Comment by johnsBeharry** [comment]
> Mocking up fake case studies and projects for a design portfolio just seems like a waste of resources that could be applied to some much need open source projects.

This is a really good point @Bosch-0 we should definitely mention this. I've created this planning document also  https://hackmd.io/@BitcoinDesign/S1-dLZz-_/edit

@Tiana01 given the audience I think we will have to give some foundations on open design as the audience may not be familiar with it. We should still put everything in the context of bitcoin design and the work we are doing though.

**Comment by GBKS** [comment]
We had the call yesterday, here are our notes:

- Unfortunately only two speakers, Johns and Christoph. This did not go the way we wanted and what we had discussed together. Going to weave more personal stories in the presentation, see if we can do another community intro video and get more people involved during the presentation via chat, breakout rooms, etc
- Next week we will be doing tech checks with the producers of the conference.
    - Find out how we can use pre-recorded video
    - Learn more about using polls during the presentation
    - Are there options for breakout rooms where more of us can participate

After the conference we can follow up with attendees
- Figma is able to distribute a message with a call to action to the particpants as a follow up after the conference. Idea: We can write up a welcome letter with a link to the newsletter and website.
- The Youtube description on the uploaded video will be timestamped, and can have additional links and information included.

Other details
- Anyone is free to sign up, watch all talks, and join chats.
- They like our rough [presentation outline in Figma](https://www.figma.com/file/aWb4a85YPlKhucQNAMt45P/Figma-Config-slides?node-id=165%3A0) (work-in-progress, a variation of the FOSDEM presentation).

How can you participate?
- Help come up with some short poll questions to send out during the talk. [Edit the poll ideas document](https://hackmd.io/@BitcoinDesign/ByNBXngNu/edit).
- Register for the conference as an attendee and attend the talk. [Fill out this form to be notified when registration opens](https://docs.google.com/forms/d/e/1FAIpQLSdx8-ouptgaSoET_R4ICKIizIB0ns7Kw6t03_r5LUqngGkDfA/viewform).
- Help [review the presentation](https://www.figma.com/file/aWb4a85YPlKhucQNAMt45P/Figma-Config-slides?node-id=165%3A0).
- Attend the work session on [Tuesday @ 9:00am PST](https://everytimezone.com/s/67974f1f)
- Have some people from the bitcoin design community hang out in the chat room for the talk with "(bitcoin.design)" in their name to help answer questions. Please state your interest.

**Comment by johnsBeharry** [comment]
> Challenges of working with open source projects - maybe use a case example? @pavlenex with BTCPay or myself with Bitcoin Core maybe?

@Bosch-0  since we got more collaborations with projects this is going to be a even more important topic. Curious what are some of those challenges you faced?

**Comment by GBKS** [comment]
Figma Config happened. The talk went great with 400 new people joining in Slack and chatting up a storm. @johnsBeharry and I did a more casual re-recording, which you can [watch here](https://youtu.be/30E65z9v9S0) until the official talk recording is live in 30 days.

- [Our talk on the Config site](https://config.figma.com/talks/design-bitcoin-for-everyone/)
- [Talk slides on Figma community](https://www.figma.com/community/file/966708683009348504/Design-bitcoin-for-everyone)

Big thanks to everyone who helped with this talk. It was a lot of work, but I think it was worth it.

The speaker fees were donated to the Human Rights Foundation.

For future talks, it'd be great to give it another try to get others in the community to present. Good to keep in mind how much work the preparations can be though. I think we had 5 calls with the Figma team and surely spent 20 hours each preparing.
