### ISSUE TITLE
Open Design Guide Reading Club #3: The Designer's Role

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#714]
```meta
UTCTime: 2024-09-26 12:00 UTC
Duration: 1h
```

![open-design-guide-reading-club-2-designers-role-240924](https://github.com/user-attachments/assets/d1b4716a-aa86-45ed-be60-9363229ef664)

Welcome to the third session of our reading club for the [Open Design Guide](https://opendesign.guide/) ([background](https://github.com/BitcoinDesign/Meta/issues/696)). We meet weekly and discuss one page in every call. It's best if everyone also reads it before, thinks a little about it, and prepares some notes. We will gather all our notes in the call, and ideally have a list of improvements to the content at the end.

For this third call, we will tackle Chapter 2, which discusses the role of the designer. After the previous pages being more introductory and laying groundwork, we are getting more into the unique material of the guide now.

A few notes:
- The group will decide whether to record the call or not ([previous recordings](https://www.youtube.com/playlist?list=PLpV0KfVOMojY7XdKa8UouHcKEVDG_uUnv)).
- If you cannot make it, but would like to add your thoughts on the content, you are welcome to share notes.
- You're welcome to join and just listen in
- Main communication for this reading club happens in the [#education](https://discord.gg/a2KzKc7BYk) channel in the Bitcoin Design Discord. 
- There's also a [thread](https://discourse.opensourcedesign.net/t/open-design-guide-reading-club/3954/4) in the Open Source Design Discourse forum.

### Check your timezone

https://everytimezone.com/s/d4ee800f

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by dulcedu** [comment]
It's 5am my time, sorry I cannot make it!!

**Comment by GBKS** [comment]
@dulcedu that is very unfortunate. I threw out the idea of a second reading session, for those on different schedules and time zones. You are welcome to make that happen if you'd like.

Alternatively, you can follow along with the [notes here](https://docs.google.com/document/d/1z4yleS74L4ldXRLMLDOJMo5mNfMpGW1v_5pXXHe8q4E/edit?usp=sharing), we also [recorded](https://www.youtube.com/watch?v=1dlNlF1vrcE) the last session, or you could just read through the pages and send over your feedback. It's like a choose-your-own-adventure.

**Comment by GBKS** [comment]
Thanks to all who joined. This call was interesting as I think that, now that we've worked through a few pages, we're getting a good sense now for the weaknesses of the AI-generated material. It's just a bit too generic and wordy with not enough real-world, relatable examples. And I think we visual people would like some illustrations and visuals mixed in. Let's whip this in shape. The [recording](https://youtu.be/Leto3voPoPI) is up on the 'tube.
