### ISSUE TITLE
ECash PR Review

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#717]
```meta
UTCTime: 2024-10-03 14:00 UTC
Duration: 1h
```
![Group 14313](https://github.com/user-attachments/assets/36246056-a852-4d92-ac50-1495c85bcdc9)

### Agenda

During this call we will review the final section of the [Ecash PR](https://github.com/BitcoinDesign/Guide/pull/1093). 

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/93064c81)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoindesign)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to all who joined the call, your feedback is extremely helpful. The recording is now up on [the 'tubes](https://youtu.be/hjgpNVRe4uY).
