### ISSUE TITLE
UX Research Call: BDK Research and Process #40

### ISSUE THREAD

**Issue by mouxdesign** [BitcoinDesign/Meta#718]
```meta
UTCTime: 2024-10-24 16:00 UTC
Duration: 1h
```
![Group 14316](https://github.com/user-attachments/assets/e755efb6-c67d-405f-9346-a1a25ecf28fe)

### Agenda

Research was conducted on [BDK](https://bitcoindevkit.org/) using the [Jobs to be Done](https://bitcoinresearch.xyz/jobs-to-be-done) method of the UX research toolkit. During this call Manuel who did the report will share the work and we'll also speak about the method used. 

This call is being done in collaboration with the [Bitcoin Product Community](https://x.com/i/spaces/1OdKrXbkoByJX/peek).

### Check your timezone

[[LINK FOR TIMEZONE](https://everytimezone.com/s/3ff5fe44)]

### Join the call

[[LINK FOR CALL](https://meet.jit.si/bitcoinproductcommunity)]

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Great overview of the research results and process. Here's [the recording](https://www.youtube.com/watch?v=BjeDZC59tiM).
