### ISSUE TITLE
Bitcoin Icons

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#72]
![File Cover Image](https://user-images.githubusercontent.com/55287964/107617568-1dbb4c00-6c8b-11eb-96ae-a8f461e15af3.png)

**What is Bitcoin Icons?**

[Bitcoin Icons](https://github.com/Bosch-0/Bitcoin-Icons) is an open source set of icons made for Bitcoin centric applications.

**Project Context** 

Many great open source icon libraries exist though many bitcoin focused icons are not present (an icon representing a node, the bitcoin network, the lightning network etc). Having an open source bitcoin centric icon library that wallet developers could use in their applications would help speed up the design and development process. 

**Collaboration type: [#4 New Project](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md)** 

Currently no icons exist in this repo. Some foundations need to be set around what general style the icon set will have before it can be open for people to contribute their own icons. This is an opportunity for those with experience in icon design to assist establishing these foundations as well as contribute icons to the set.

**Team**

- @Bosch-0 
- @GBKS 
- Icon expert to help establish icon style foundations.
- Icon designers once foundations set.

**Notes**

- Thoughts on having this as an official bitcoin design community icon set? Icon could be referenced and used in the Guide.  I see this as a great project we can all take part of as a community.

**Timeline**
**Next Steps**

- Establish some icon foundations as a community that can be used for the set.
- Design icons - feel free to open an issue on the repo with an icon you think should be in the set. 
- ???
- Profit

**Links**

- [Bitcoin Icons repo](https://github.com/Bosch-0/Bitcoin-Icons)

**Comment by Bosch-0** [comment]
Added @GBKS to team, also gave contributor access to the Icons repo

**Comment by GBKS** [comment]
I think the project is in pretty good shape at this point. We have a Figma community file with the icon sources, and a Github repo with implementation-ready assets (SVGs). There's over 40 icons that cover a lot of ground already. There's of course a lot of refinement to do, I think that will come over time.

I think a really good next step is to find projects that want to implement these icons and identify what hurdles still exist (missing icons, incorrect sizes or file formats, styling issues, etc).

**Comment by Bosch-0** [comment]
Yep it is going well thanks to you! Really love the icons that have been designed so far. I'm planning on using the set in my [Zeus](https://github.com/BitcoinDesign/Meta/issues/70) designs - happy to have this as an application to show the icon set 'in the wild.' 

As projects adopt the set we could also have a list somewhere in the repo with these projects so people can see how they have been used in different contexts.

**Comment by pavlenex** [comment]
Epic work, love it! ❤️ 

@Bosch-0 Would it make sense to add it to the Bitcoin Design organization repository to make it more visible? Whoever is managing that repo (I suppose it's you, can maintain full access to it). It's really a cool project and would be great if more people knew about it. Additionally, we should probably add it to the `Projects` page on the website.

In my opinion, the "ideal" user-friendly experience here would be that:
1. John comes to the website, sees the project 
2. Call to action `download icon set` is clearly displayed
3. John is able to get access to tons of icons and download the icon set

On another note, managing new icons and adding them can be handled through GitHub by the community where people could submit theirs or create icons based on issues we have opened. Overall, IMO managing this kind of stuff is better when the community is gathered around certain projects already, but just an idea of course!

**Comment by GBKS** [comment]
As a bit of a reality-check, and to see if Specter would realistically consider using them, I mapped all the Specter icons against this set. [Here's a video summary](https://youtu.be/W4h59fTExzc). Hopefully that helps get a common understanding whether this is a worthwhile switch. We could do the same for Zeus, if you haven't done so yet.

There were about 18 icons still missing, so I created those and added them to Figma (still need to export them). There were only a few that were unique to Specter (snowflake, sh*tcoins...), most of them were generic (transfer, link...) and should also be helpful for other projects.

Overall, I think the icons need a lot of polish. It's a lot of really small stuff. Making line caps consistent, slightly tweaking sizes so the visual weight across the set is similar, adjusting size variations, etc. But this is minor stuff overall, and a project could easily update the set as changes come up by simply overwriting the old files with the new ones.

Totally agree with @pavlenex on building this project out further (along with the Wallet UI Kit, hardware illustrations, and anything else we come up with), so it's super easy to get into and use.

**Comment by Bosch-0** [comment]
> @Bosch-0 Would it make sense to add it to the Bitcoin Design organization repository to make it more visible?

Yes I am fine with this, I always intended this to be a BDC focused project we all take part in - @GBKS are you able to move the repo there and make me a mod?

>  we should probably add it to the Projects page on the website.

Also yes, I'll open a PR for this once the repo has moved to BDC org account.

Thanks for the input @pavlenex, all great points! Having new icons added via GH was always the intention! 

> perhaps we can have a bitcoinicons website

Also something I want to do eventually, great suggestion!

**Comment by GBKS** [comment]
It looks like I need more rights to transfer the repo... could you please take a look? Here's the Github info about [transferring repos](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository).

**Comment by GBKS** [comment]
Here's a 6-minute video update on the status of the project. [Check it out](https://youtu.be/W4h59fTExzc).

**Comment by GBKS** [comment]
The repo now lives under the Bitcoin Design organization. [Check it](https://github.com/BitcoinDesign/Bitcoin-Icons).

Apparently, Figma will revamp how teams work in upcoming changes they will announce at their conference on April 21. I hope that this will make teams work better for us so we can also move the Figma file to a community-owned account.

**Comment by GBKS** [comment]
Created a first-draft mockup for a potential website for this project. [More here](https://github.com/BitcoinDesign/Bitcoin-Icons/issues/32).

**Comment by Bosch-0** [comment]
Closing this issue as it isn't really a collaboration anymore - it is a full-fledged BDC project with it's own repo: https://github.com/BitcoinDesign/Bitcoin-Icons
