### ISSUE TITLE
Dana wallet - Project Exploration Call

### ISSUE THREAD

**Issue by yashrajd** [BitcoinDesign/Meta#722]
```meta
UTCTime: 2024-10-09 14:00 UTC
Duration: 1h
```

![Dana-wallet-call-banner-0](https://github.com/user-attachments/assets/6ee3a90c-2d0c-4bf7-b88d-c58ac47c66e4)

### Agenda

[Dana wallet](https://github.com/cygnet3/danawallet) is a silent payments-based mobile wallet project for accepting bitcoin donations. In this introductory call, we'll get to know the team, learn about Dana wallet's vision, what has already been done and where the project is trying to go.

### Check your timezone

https://everytimezone.com/s/16a2ea96

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
Thanks to all who joined. The recording is uploaded on [the 'tube](https://www.youtube.com/watch?v=5eS3OPWBK8k).

I think this project is a great opportunity for a designer to come in right at the start and work with a small team and do some really good and interesting work.
