### ISSUE TITLE
Dana wallet - Design Call #1

### ISSUE THREAD

**Issue by yashrajd** [BitcoinDesign/Meta#725]
```meta
UTCTime: 2024-10-23 14:00 UTC
Duration: 1h
```

![Dana-wallet-call-banner-1](https://github.com/user-attachments/assets/abf92ee6-332a-497a-a761-1b871a01e37e)

### Agenda

This is the first call in a new series of bi-weekly with the [Dana wallet](https://github.com/cygnet3/danawallet) team.

### Check your timezone

https://everytimezone.com/s/d496a6b1

### Join the call

https://meet.jit.si/bitcoindesign

### Calendar invite

Subscribe to the [Bitcoin Design calendar](https://bitcoin.design/calendar/).

**Comment by GBKS** [comment]
This was a nice intro call to the Dana Wallet project and team. The recording is available [here](https://www.youtube.com/watch?v=5eS3OPWBK8k).

If you want to contribute on the design side, reach out. The team would be super happy to have someone help out.
