### ISSUE TITLE
Create a collaboration issue template

### ISSUE THREAD

**Issue by Bosch-0** [BitcoinDesign/Meta#73]
Similar to how we have a community call template for issues it would be handy to have a design collaboration template. Christoph has already laid out one that I think works pretty well below. This way project owners can come to us and make these issues instead of us make it for them. 

**_[insert incredibly well-designed cover image, see other collaboration issues for inspiration but feel free to put your own touch on it. Landscape formats work best.]_**

### Collaboration type: [Pick from this list](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md)

_[The Bitcoin Design community has laid out several collaboration types in the above linked playbook, please choose and link to the one that fits your project needs.]_

### Goal

_[What is the goal of this collaboration?]_

### Project context

_[Give some context to the project. Why was it started? What is its purpose? Is it FOSS, OSS or closed source?]_

### Team

_[Who is currently working on the project and what are their roles? What roles are you looking to fill, if any?]_

### Timeline

_[What steps, if any, do you have outlined to take to achieve your design goal?]_

### Notes

_[Add any extra notes that may be relevant to this collaboration.]_

### Links

_[Include any relevant links, such as links to your projects GitHub repo, website, app etc.]_

**Comment by GBKS** [comment]
ACK. Good idea.

**Comment by Bosch-0** [comment]
A link should be included in [COLLABORATION.md](https://github.com/BitcoinDesign/Meta/blob/master/Collaboration.md) to this issue template once its created

**Comment by Bosch-0** [comment]
Something relevant to add here is that if projects come to us they might not know what kind of collaboration type they require. For these types of projects it might be useful to list some steps to take and we can help them decide what their needs are. I would propose the three steps outlined in collaboration type #1 below as steps to take BEFORE deciding on a collaboration type:

1. Review the guide to find a direction or solution
2. Engage in Slack conversations to share ideas and get feedback
3. Participate in a design review session
4. Decide what type of design collaboration is suited for your project.

This would only be targeted towards projects that have no design focus whatsoever which is relatively common in open source projects.

**Comment by GBKS** [comment]
@Bosch-0 TBH, my assumption is that projects won't just show up and create issues, but some of us regular contributors will create them after talking to the team and figuring out what the right plan of action is. They can, of course, but some conversation beforehand would be healthy to clarify what's needed and get support in the community.

**Comment by Bosch-0** [comment]
Yeah you're assumption is most likely correct, this concept is still quite new so I guess we can see how things proceed and adjust accordingly.

**Comment by GBKS** [comment]
Going to close this issue, as it's been 2+ years without activity. Collaborations seem to be going fine without a template. We can re-open if someone feels strongly about it.
