### ISSUE TITLE
Printable Bitcoin banknote for chinese red envelop "HongBao" 🧧

### ISSUE THREAD

**Issue by sbounmy** [BitcoinDesign/Meta#738]
Hello,

For Chinese New Year (upcoming) I've built https://hongbaob.tc

The project is open source https://github.com/sbounmy/hongbao_bitcoin

It will be great to add it to https://bitcoin.design/projects/

Cheers,

**Comment by GBKS** [comment]
Hi, thanks for sharing. The projects page on the website is not a general list of projects, but only about projects that have started and are carried by member in the Bitcoin Design Community, or where there have been collaborations with existing projects. I don't think I've seen your project around the community, so I don't think it's a good fit for listing on the site (this repo is also not the repo for the website). Why don't you start by posting it on Discord?

I'll also include it in the Bitcoin Design newsletter that will go out this week.

**Comment by sbounmy** [comment]
Thanks @GBKS ! I will post on discord then :)
