### ISSUE TITLE
Bitcoin Core GUI discussion

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#8]
```meta
Date: 2020-08-20
Time: 8:00am CEST for 1 hour
```

### Agenda

Larger discussion around Bitcoin Core GUI as a project and design contributions.

### Check your timezone

- https://everytimezone.com/s/cbb042cf

### Join the call

- [Calendar invite](https://calendar.google.com/calendar/r/eventedit/copy/N3I2M2NscjZwYTdqZmtybzZsY3BhNm8xbXAgYml0ZGV2c2xhQG0/a251ZWZmZWxidW5kQGdtYWlsLmNvbQ?sf=true)
- https://meet.jit.si/bitcoindesign

**Comment by michaelfolkson** [comment]
@GBKS presentation on revamping Monero GUI: https://www.youtube.com/watch?v=Aarzsiwc5_g

Bosch WIP wallet frames: https://www.figma.com/file/FJ02rY3m8V9ZCDvoXjW39W/Bitcoin-Core?node-id=281%3A0

Bosch WIP onboarding wizard: https://www.figma.com/file/FJ02rY3m8V9ZCDvoXjW39W/Bitcoin-Core?node-id=462%3A655

Marco Falke on separating the Bitcoin Core GUI: https://github.com/bitcoin/bitcoin/pull/19071

Who is the Bitcoin Core GUI being designed for?: https://github.com/bitcoin-core/gui/issues/45

**Comment by ecurrencyhodler** [comment]
Hey @michaelfolkson Thanks for all those links. It was helpful to get up to speed. One question I have is what is a Blank Wallet? I've never heard of that before. How can you create a wallet with no private key? It sounds like it's not a watch-only wallet either.

**Comment by hebasto** [comment]
@ecurrencyhodler 
> Hey @michaelfolkson Thanks for all those links. It was helpful to get up to speed. One question I have is what is a Blank Wallet? I've never heard of that before. How can you create a wallet with no private key? It sounds like it's not a watch-only wallet either.

https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.18.0.md:
> `createwallet` now has an optional blank argument that can be used to create a `blank` wallet. Blank wallets do not have any keys or HD seed. They cannot be opened in software older than 0.18. Once a blank wallet has a HD seed set (by using `sethdseed`) or private keys, scripts, addresses, and other watch only things have been imported, the wallet is no longer blank and can be opened in 0.17.x. Encrypting a blank wallet will also set a HD seed for it.

**Comment by ecurrencyhodler** [comment]
Hey @hebasto Thanks. I'm still not sure what a blank wallet could be useful for or why it would be an option. But maybe we can discuss that on the call.

**Comment by Bosch-0** [comment]
It is like a watch-only wallet but it can have HD seeds / private keys imported at a later date unlike a watch-only which permantely disables private keys. I'm sure it only serves some niche cases but I'm sure there is some - ill do some digging.

**Comment by ecurrencyhodler** [comment]
Thanks @Bosch-0. That makes sense.
