### ISSUE TITLE
LDK Website

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Meta#89]
The team behind the [Lightning Development Kit](https://lightningdevkit.org) is looking to improve their website. It is currently using the [Docusaurus](https://docusaurus.io/) default theme.

The initial ask was to replace the icons on the landing page, as well as the logo, which then turned into a larger branding and web design exercise.

References:
- [Design progress Figma file](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=219%3A12020)
- [Video update on layout architecture & responsiveness](https://vimeo.com/549676881/b838141b88) by @sbddesign on May 17, 2021
- [Video of design discussion](https://www.dropbox.com/s/nc11flk89xlzzty/bitcoindesign%20on%202021-04-06%2016-59.mp4?dl=0) on April 6, 2021
- [Video update on brand concepts](https://youtu.be/0ZU1NAAaUY0) by @GBKS on March 29, 2021
- [Design update](https://vimeo.com/549676881/b838141b88) by @sbddesign on May 15, 2021

**Comment by pavlenex** [comment]
It's good to note that this issue is blocked by the branding. First, we'd need a logo and branding, website, as is, could be improved, but for any major overhaul, it would probably be a good idea to wait, as there may be some architectural changes to the site, however, the mocks/designs shouldn't be influenced by that.

**Comment by maxgeor** [comment]
When you say "replace the icons", do you mean these ones?

<img width="1276" alt="Screen Shot 2021-03-20 at 1 36 58 PM" src="https://user-images.githubusercontent.com/73665502/111880362-731d0400-8981-11eb-87e9-58703a7ee164.png">

**Comment by johnsBeharry** [comment]
hey @maxgeor yes those are the illustrations.

**Comment by GBKS** [comment]
@pavlenex set up a [board for this project](https://github.com/BitcoinDesign/Meta/projects/3) to track activities and progress.

**Comment by ConorOkus** [comment]
Basic site migration and design implementation happening here - https://github.com/lightningdevkit/lightningdevkit.org/pull/46

**Comment by GBKS** [comment]
To provide an update on this. Both the LDK and BDK sites are live with the new logo and theme.
- https://lightningdevkit.org/
- https://bitcoindevkit.org/

The Figma file with the latest design source is [here](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=219%3A12020).

@ConorOkus are there any outstanding tasks, or anything coming up you can think of?

**Comment by ConorOkus** [comment]
Thanks for updating @GBKS. 

Nothing in the short term, but updates will be being made to the landing pages to include some case studies e.g BlueWallet for LDK.

So we should start thinking about designs for that soon.
